### ISSUE TITLE
proxyUrl type endpoint, or something like it.

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#101]
For client to server interactions, it might be necessary to defer to a server to fetch an item for you that your server-user has access to, but isn't public.  For instance, maybe I check my inbox, where I may receive something like for example a "Like" object that is inReplyTo an item my server-user has access to, but which doesn't currently appear in the feed.  So, my client will need access to that.  But if I just visit the URL, there's no way for me to get that item.  If we define a proxyUrl endpoint, our server could get this on behalf of our authenticated user and deliver the object back to their client.

I believe pump.io has something of this sort, and it's called proxyUrl there?

**Comment by cwebber** [comment]
I'd also be okay with postponing this and leaving it as an extension.

**Comment by jankusanagi** [comment]
> defer to a server to fetch an item for you that your server-user has access to, but isn't public.

Just for the record, on Pump.io it doesn't matter if the object is public. A remote server will not provide (directly) the data to you via API if you're not authenticated with it, regardless of the "publicness" of the object.

So a client needs to access remote servers (to check for all comments to a post, for instance) via proxyURL in all cases.

**Comment by cwebber** [comment]
Thanks for the clarity, @jankusanagi :)

**Comment by cwebber** [comment]
(Note that if we had a signatures approach, we could do this without needing a proxy URL.  But that infrastructure will not be ready/stable enough in time for ActivityPub's release, so I think we'll have to rely on this for now.)

**Comment by sebilasse** [comment]
@cwebber @rhiaro 
just btw: In https://www.w3.org/TR/activitypub/#actor-objects
> Endpoint URI so this actor's clients may access remote ActivityStreams objects which require authentication to access.

As an ordinary user it was not clear to me (until I read the phenomenal description on top) that "clients may access remote ActivityStreams objects" by the clients' server-user.
Not sure if there is space for one more sentence ;)
