### ISSUE TITLE
Mention for JSON-LD @Context

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#102]
I suggest to add below mention to section 3 for explaining JSON-LD context.

---

JSON-LD stands for JSON for Linking Data. It uses familiar JSON structure but contains specific reserved names, prefixed by the ‘@’ symbol such as ‘@context’.
The reader can interpret the meaning of name-value in JSON data by the ‘@context’. 
In the below JSON-LD example, the person type can be interpreted concisely by the instruction of the ‘@context’ “http://www.w3.org/ns/activitystreams” URL. And also the URL tells what the meaning of ‘name’ and ‘born’ exactly is. 
{
"@context": "http://www.w3.org/ns/activitystreams",
“@type” : “person”,
“name” : “John”,
“born” : “1980-10-10
}
You can see more about the JSON-LD in json-ld.org.

**Comment by cwebber** [comment]
Hm.  I wonder if it's the role of ActivityStreams and json-ld itself to clarify what the `@context` is?  Though maybe you're saying that `@context` is likely to be the most "foreign-looking" thing to developers (ie, JSON is already familiar, so the rest of the examples should be self-evident, but `@context` isn't?)

I'd be okay with adding a bit of text explaining what the `@context` is, but I wonder if we could keep it as short as a sentence or two and point off to the json-ld documentation for those who want to look in detail?

**Comment by cwebber** [comment]
This is done.  I mentioned the ActivityPub context specifically, and while I didn't include a full explaination of what a json-ld context is, I linked to it.
