### ISSUE TITLE
"source" field

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#107]
It would be good to have a "source" field, so if your "content" on a Note, Article, or whatever had markdown, restructured text, or org-mode formatting which you used to render the html "content", clients could let you update using the original.  @xray7224 and I have talked about this multiple times, but somehow I never filed an issue.

Anyway, it could look something like this:

```
{"type": "Note",
 "content": "<p>Checking out this <a href=\"http://foo.example/\">cool website</a>",
 "source": {
    "content": "Checking out this [cool website](http://foo.example)",
    "mediaType": "text/markdown"}}
```

**Comment by cwebber** [comment]
Note: look at prov vocabulary

**Comment by cwebber** [comment]
So various concerns were: should this be rendered on client, or on server?  What if a client which doesn't know this format edits it, and the source form is lost?  And maybe you can just convert from the content to the preferred form anyway (from markdown->html back via html->markdown).

These things were discussed, as brief response to each: clients rendering from source to html is already what's done currently in the pump.io world and this is also what both editors want; you might use org-mode or some other format that the server doesn't know how to work with.  As for source being lost, good point, we should address it (discussed below).  For just converting from html -> source, that's not always possible; it's very lossy and is effectively reverse engineering (try going from latex -> html -> latex!)

So about "losing" source, after some discussion: when editing in a client that can't support this source, we want to add a non-normative note that says that clients ought to add a warning letting the user know that they're not editing in the original source form.

So we'd do the above, and make it at-risk.

**Comment by cwebber** [comment]
Additionally: Jessica has suggested that the source MAY be a list, ordered newest first, and that source objects SHOULD have a date field from when they were written, so you can have a history of source.

**Comment by cwebber** [comment]
Feedback is that we should add source property (without history), mark it at risk, and add a SHOULD that clients ought to inform/warn the user that a user would lose source, if editing with something that cannot work with that source.

**Comment by jaywink** [comment]
As a person working on platforms with markdown content, having an example in the spec with pre-rendered Markdown into "content" looks a bit scary and is sure to cause interoperability problems. I would certainly expect "content" to be what the user typed out, not rendered into HTML.

I would suggest removing the `source` content and instead having the following if people really want to push pre-rendered content around. Content should _always_ contain the original content, IMHO.

```
{
  "@context": "https://www.w3.org/ns/activitypub",
  "object": "Note",
  "id": "http://postparty.example/p/2415",
  "content": "I *really* like strawberries!",
  "contentType": "text/markdown",
  "rendered": "<p>I <em>really</em> like strawberries!</p>",
}
```

Even if there would not be a `rendered`, `contentType` would still be helpful. I guess it was dropped, I remember there was discussion?

Shall I open a new issue regarding this or do you think the case is closed re `source`?

**Comment by cwebber** [comment]
@jaywink so, you _could_ do markdown as the thing pushed around and set a contentType for that.  But I really don't think it's a good idea.  Markdown is an especially clear example of why that's a bad idea: there are _so many_ variants of Markdown that you can't trust two servers to render things the same way!  We're typing right now on a platform that has a totally unique flavor of Markdown, after all...

So there's good reason why the HTML-rendered version of content is preferred, even though you _could_ make the content be markdown.  (Other servers might not recognize it though.)

**Comment by jaywink** [comment]
The problem with sending rendered content around is that different servers might clean it differently. I mean, everyone will clean the content always before rendering, I certainly hope so ;) Different cleaning libraries will default to different tags they allow, sometimes just the basic emphasis and link. But maybe it is a lesser problem than the rendering, sure.

Anyway, I didn't remember AS2 objects have `mediaType`, which addresses my concerns.
