### ISSUE TITLE
'Actor' and language/direction

### ISSUE THREAD

**Issue by aphillips** [w3c-social/activitypump#126]
https://w3c.github.io/activitypub/#actor-objects

The 'Actor' object contains several fields that can contain natural language text. It would be useful to indicate in the spec how to add language and direction information to these. Specifically, name, preferredUsername, and summary.

The first two (name and preferredUsername) might be questionable: these are opaque Unicode strings that might be considered language independent. The summary, though, is more interesting. Language and base direction should be documented, even if only to refer to JSON-LD mechanisms and/or the bidi text in ActivityStreams 2.0.

Language often makes a presentational difference for strings, even if the language information isn't used for other purposes. In particular, it is helpful in selecting fonts to avoid the ransom note effect in CJK languages.

**Comment by aphillips** [comment]
This is an I18N WG comment sourced from [i18n 227](https://github.com/w3c/i18n-activity/issues/227) and discussed in [teleconference](https://www.w3.org/2016/09/29-i18n-minutes.html)

Please add the `i18n` label so this is tracked. I don't have permission to label here.

**Comment by cwebber** [comment]
"name" is the same "name" as in AS 2.0, just called out because many actors will need it.  "preferredUsername" I think should follow the same rule, though we should make that explicit.

As for summary, pleasantly I don't think we have the same limitations we have with "name".  It can be full markup, no problem, and is probably expected to be HTML.  I think it's also reasonable to assume that the language and base direction inherit from the json-ld mechanisms.  We should make that explicit.

Thanks for the useful feedback!

**Comment by r12a** [comment]
Sorry for the noise. Just re-applying the i18n label so that it notifies our list.  I had somehow forgotten to set up the notification beforehand.

**Comment by cwebber** [comment]
I added information on this in c28c7f3 though I wasn't sure if the bidirectional text part of my original note was redundant, so I trimmed it a bit in 745b23c.  Basically, we follow the same patterns as ActivityStreams.  Again, I'm not sure if this is already implied by depending on ActivityStreams, but I'm not against making it explicit.

I'm open to rewording.  Here's a [link to the note](http://w3c.github.io/activitypub/#actor-text-direction) for convenience.

**Comment by aphillips** [comment]
@cwebber This looks okay to me. My only comment is that:

> Properties which contain natural language values follow the same rules as in ActivityStreams

... reads kind of odd to me. Perhaps:

> Properties containing natural language values, such as `name`, `preferredUsername`, or `summary`, 
> make use of natural language support defined in ActivityStreams.

**Comment by cwebber** [comment]
Great, I think that resolves things then!
