### ISSUE TITLE
establishing 'id' uniqueness/identity

### ISSUE THREAD

**Issue by aphillips** [w3c-social/activitypump#127]
https://w3c.github.io/activitypub/#obj-id

This document mentions:

>    All Objects in [ActivityStreams] should have unique global identifiers. ActivityPub extends this
>   requirement; all objects distributed by the ActivityPub protocol MUST have unique global identifiers

And section 4 mentions that only "valid URIs" are accepted. There is a note in the current ED, though, that mentions deciding whether a missing scheme is considered valid (the example given is `tantek.com`).

As id portion of the identifier is a URI (by which is meant an IRI), some considerations that might be necessary include classic IRI identity-matching ones:
-    should punycoded domain names be escaped/unescaped/matched to percent-encoded?
-    how should path components be normalized? using URI rules?

Note that ActivityPub makes no reference, normative or otherwise, to URI, IRI, (whatwg) URL, so the term URI is somewhat opaque here.

**Comment by aphillips** [comment]
This is an I18N WG comment sourced from [i18n #226](https://github.com/w3c/i18n-activity/issues/226).

Please add the `i18n` label.

**Comment by cwebber** [comment]
The example of "tantek.com" being entered without a scheme is not for actual activitystreams objects (where it would definitely be invalid), but for a user interface where someone enters in the address of a remote user interface.  The question is open for "should the user interface try to guess the scheme" since that isn't currently allowed if following the text preceding it.

**Comment by cwebber** [comment]
Note that in bb1649a and 8ed885c I've clarified the previous "URI without scheme" question by adding it to the ID normalization rules.

**Comment by cwebber** [comment]
Ooops, that didn't mean this was done.  Closing this was an accident.

**Comment by cwebber** [comment]
So I think we clarified the text around the "URI without scheme" bit.  The part that's left is clarifying whether we mean "URI" or "IRI".  Admittedly I'm uninformed on this front.  I'm reading up now so we can clarify better.

Probably we should do whatever ActivityStreams does, though.

**Comment by cwebber** [comment]
[AS2 uses IRIs](https://www.w3.org/TR/activitystreams-core/#urls) so we should make it clear that we do the same.

**Comment by cwebber** [comment]
So I've made it explicit in 4a080f4 that we use the same URI / IRI conventions as in ActivityStreams, but is this really necessary, since ActivityPub builds itself on ActivityStreams?

**Comment by cwebber** [comment]
I believe I satisfied this request.  Let me know if more work needs to be done and I'll reopen.
