### ISSUE TITLE
Jan's typos and small errors, Volume 1

### ISSUE THREAD

**Issue by jankusanagi** [w3c-social/activitypump#129]
As discussed with @cwebber, here's a list of small typos or redundant sentences I found in the spec:
- Redundancy at the end of the third paragraph of point 3 https://w3c.github.io/activitypub/#obj:

> (However, if other generally agreed upon mechanisms for handling verification become available **in the future**, servers are welcome to use those methods, **in the future**.)
- At the end of https://w3c.github.io/activitypub/#source-property, right before point 4, at the end of the sentence:

> "and decides to make the update when **whe** gets home."
- At the end of the first paragraph of point 6 https://w3c.github.io/activitypub/#binary-data:

>  that can be posted to the **users** outbox.

IIUC, that should be "user's outbox".
- In point 7.8, at the end of the first sentence https://w3c.github.io/activitypub/#block-activity-outbox:

> The Block activity is used to indicate that the actor does not want a user (defined in the object property) to be able to interact with objects posted **by the user**. 

Sounds a little confusing. I think the last instance of "user" is supposed to be "actor".
- Point 8, beginning of the second sentence https://w3c.github.io/activitypub/#server-to-server-interactions:

>  An Activity sent over over the network SHOULD

There's a double "over", unless there's a specific sense I'm not getting.
- Point 9.2, second paragraph https://w3c.github.io/activitypub/#authorization-lds:

> When Linked Data Signatures **in combined** with ActivityPub

This sounds weird. I imagine "in combination" or "are combined" was intended.
- Point C, at the end of the second question, https://w3c.github.io/activitypub/#security-and-privacy-review:

>  Similarly, no normative mechanism for authentication between servers is exposed, though **similar issues with exposure of data such as OAuth tokens could be exposed**. 

Seems a little redundant, particularly the second half.

Cheers!

**Comment by cwebber** [comment]
Incorporated all these edits.  Thanks, Jan!
