### ISSUE TITLE
Get AP terms in AS2 context/namespace

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#132]
The following terms are defined in ActivityPub, and we need to get them in the ActivityStreams namespace / context:
- inbox
- outbox
- following
- followers
- streams
- preferredUsername
- endpoints
- uploadMedia
- proxyUrl
- oauthClientAuthorize
- provideClientKey
- authorizeClientKey
- source

See also #131 which is about switching the context over in the AP document itself.

**Comment by cwebber** [comment]
Note that "inbox" should be an alias to ldp:inbox.

**Comment by cwebber** [comment]
This is something that @rhiaro and I will have to work on together, though probably AP should hit CR first.

**Comment by rhiaro** [comment]
Done!

Sanity checks welcome, reopen if I messed something up: https://www.w3.org/ns/activitystreams
