### ISSUE TITLE
Change 'ActivityStreams Vocabulary' to 'Activity Vocabulary'

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#135]
In the section '3. Objects'
Objects are the core concept around which both [ActivityStreams] and ActivityPub are built. Objects are often wrapped in Activities and are contained in streams of Collections, which are themselves subclasses of Objects. See the ActivityStreams Vocabulary document...

I think 'ActivityStreams Vocabulary' should be changed to ''Activity Vocabulary'.

It's minor editorial thing...:-)

**Comment by cwebber** [comment]
You're right, that's what was meant.  Thanks!
