### ISSUE TITLE
Privacy of followers/following/likes collections

### ISSUE THREAD

**Issue by jaywink** [w3c-social/activitypump#139]
I don't see in the spec any mention regarding the privacy of the followers/following/likes collection though I looked through a few times.

Is there a requirement either way for these? Trying to understand the federation between servers flow I came to the conclusion that there is no need for these collections to be public at least.

I'd recommend marking them with something like a "SHOULD be controlled by access controls to limit the objects in the collections to the user". In the end, the application can then offer the user choice whether to make these collections public (outside spec really).

If server to server requires these collections to be public then we have a larger problem :)

**Comment by cwebber** [comment]
Since it's optional, and it might be that some implementations (and hopefully, some users in those use cases), how aboutwe say "MAY be access controlled"?  It's not necessarily SHOULD, because for instance Twitter leaves all that stuff public I think.  But most social networks are not as public as Twitter, and yeah I think they would want to control access.

**Comment by cwebber** [comment]
@jaywink Could you look at the above update and see if it's satisfactory?

**Comment by jaywink** [comment]
> and MAY be filtered publicly or on privileges of an authenticated user

Shouldn't this be "privileges of an authenticated user" - because an unauthenticated user wouldn't really be able to have any privileges? Unless I misunderstood :)

I'm fine with MAY though. It's an important clarification to not give the indication that the specification declares these as public content. Thanks :+1:

**Comment by cwebber** [comment]
@jaywink I agree the text was confusing; I meant to say that you'd still possibly filter when there's no authentication ("public").  I hope this is clearer:

```
-          and MAY be filtered publicly or on privileges of an authenticated
-          user.
+          and MAY be filtered on privileges of an authenticated user
+          or as appropriate when no authentication is given.
```

Anyway, it sounds like you're good on the general point, so I think that means we can close this.  If you have additional language tweaks I'm open to them though!
