### ISSUE TITLE
Clarify 'to' vs 'cc'

### ISSUE THREAD

**Issue by brooksn** [w3c-social/activitypump#141]
In #45, it is specified that `cc` and `bcc` specify an audience for an activity. However, while an actor's followers are notified by [an activity's `cc` field here](https://github.com/w3c/activitypub/blob/6536d264750fa364886a80124c77937783211160/index.html#L863), another activity [notifies followers by the `to` field](https://github.com/w3c/activitypub/blob/6536d264750fa364886a80124c77937783211160/index.html#L924). Should there be a normal place to reference your followers when you create an activity?

**Comment by cwebber** [comment]
You're right that it appears inconsistent, and I guess we could adjust it.  I'm not sure it's an error... the difference between to and cc in practice is mostly informative.

I guess we could specify how to and cc are used, but I feel like [ActivityStreams already explained how targeting works](https://www.w3.org/TR/activitystreams-vocabulary/#audienceTargeting).  I really don't want to reproduce the work that ActivityStreams has already done, but maybe we could link to it more prominently.

**Comment by cwebber** [comment]
See commit 83d8f22 which more prominently addresses ActivityStreams addressing early on.  Does this help make clear how `to` and `cc` are used?  Do you feel that this satisfies the issue you raised?

**Comment by brooksn** [comment]
Thanks, 83d8f22 makes it very clear.

**Comment by cwebber** [comment]
Great!
