### ISSUE TITLE
Minor problems potentially affecting implementations

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#143]
Similar to #142, but this issue contains minor problems that I judged to run the risk of not being purely editorial. All of these should be very quick to resolve.
- 4.1 Actor Objects, in the description of `icon`: "media link" is unclear; is this supposed to be a plain URL link or an AS2 Link object? Or either?
- 4.1 Actor Objects: "A mapping..." is a smidge unclear; perhaps change to "A JSON object mapping additional special-purpose resources to endpoints..."
- 6. Binary Data: the _should expect_ in "A client should expect that it must be..." is unclear; perhaps add to the sentence, i.e.: "A client should expect that it must be properly authenticated in order to be able to upload media; exactly how to authenticate will depend on what authentication scheme the ActivityPub server implements."
- 7.3 Delete Activity: change "...if a `Tombstone` is used, otherwise..." to "...if a `Tombstone` is used (with the `Tombstone` as the body), otherwise..." - seems to me that this is what the spec mandates but it's subtle enough to be worth calling out explicitly
- 8.6 Remove Activity, list item 2: "added" should clearly be "removed"
- A.2 Accessing localhost URIs: "accessing as used throughout this section is kinda vague. Accessing how? You mean letting AS2 objects reference it? Loading it in a browser? Allowing distribution to it?
- A.2 Accessing localhost URIs: "assumed to be protected to be usable by localhost-only" doesn't make sense

**Comment by cwebber** [comment]
Heya!  Great catches.  I've pushed fixes for all of these except the Binary Data section.  I'm not sure I agree that we should add a "depends on the authentication scheme" since that's called out multiple times elsewhere.  Nonetheless I'll be refactoring that entire section shortly and will keep it in mind while doing it.

Great readying, thank you so much!

**Comment by strugee** [comment]
:thumbsup: of course! Thanks for working so hard on this spec :)
