### ISSUE TITLE
Shouldn't the actor `following` and `followers` collections be references?

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#144]
The spec specifies that implementations SHOULD provide a `following` property:

> An [ActivityStreams] collection of the actors that this actor is following. 

and a `followers` collection:

> An [ActivityStreams] collection of the actors that follow this actor. 

It's not clear to me whether these collections can be embedded directly within the actor object (i.e. the full collection object is the value of the `following`/`followers` key). My instinct is that implementors SHOULD NOT do this, and instead only reference these collections with a URL.

**Comment by cwebber** [comment]
Yes, they should be references.  I guess that wasn't necessarily clear.  Fixed now... thanks!
