### ISSUE TITLE
preferredUsername vs. name

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#145]
It's not clear to me how `preferredUsername` and `name` are intended to be used, particularly in relation to each other. Perhaps some example use-cases?

**Comment by cwebber** [comment]
So for example in your case, your preferredUsername might be "strugee" (what you use to log in as), whereas your name might be "Alex Jordan".  I'm not sure what to write in addition to what we already have in the specification.  There is an example (though now it's in Japanese).

It's not clear if preferredUsername is particularly useful though.  Maybe it's more useful when all instances were using webfinger.  Right now webfinger is just one URI type, and even less preferred over HTTP(s).  Maybe we should mark it as "at risk" or even drop preferredUsername?  What do you think?

**Comment by strugee** [comment]
Whoops, somehow didn't see the example. Thanks.

> It's not clear if preferredUsername is particularly useful though.

Agreed. From a user perspective, I'm not sure what the use-case here is. Take Pumpa - if I type @ in Pumpa, what autocompletes? Is preferredUsername supposed to be a "username nickname", and the Webfinger ID is the actual "username" - such that Pumpa would autocomplete any user whose preferredUsername matched the entered text? I'm really not sure.

I think you should mark it as At Risk, see if any implementor has use for it, and if not get rid of it.

**Comment by cwebber** [comment]
Sounds good.  Okay, done!  Thanks for the feedback :)
