### ISSUE TITLE
Public collection URI is specified in an example which isn't normative

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#146]
5.6 Public Addressing defines what the "Public Collection" looks like in an example, however:

> As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative. 

(http://w3c.github.io/activitypub/#conformance)

**Comment by cwebber** [comment]
Ah you're right.  Thanks, I identified the URI outside of the example as well!
