### ISSUE TITLE
Add/Remove activity permission rules are wonky

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#148]
7.5 Add Activity and 7.6 Remove Activity both contain similar language about when _not_ to perform side effects which is a little wonky. "Add Activity" talks about the "receiving user" which maybe should be changed to "receiving server" to match similar language in the rest of the spec? If not, this doesn't really make sense to me. Unless by "can't update it" you mean "are not authorized to update it"?

Also, am I correct in thinking that access control is intended to be implemented on the basis of the second bullet point? For reference:

> the object is not allowed to be added to the target collection for some other reason, at the receiver's discretion.

Finally, "receiver" is a little ambiguous, perhaps "receiving server" or just "server"?

**Comment by cwebber** [comment]
Made all those changes, thanks!  And yes, there is some assumption that there's access control in the system, but that's up to the server to keep track of.
