### ISSUE TITLE
To what extent are Follow activities Undone?

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#149]
7.9 Undo Activity states:

> Side effects (such as adding activities to a user's inbox after a Follow) should be undone, to the extent possible. 

The example in this quote doesn't quite sit right with me. Is this implying that any activity that was delivered to a user's inbox as a result of a Follow should be removed? That seems pretty invasive and hard to actually get right (particularly because of notification targeting).

**Comment by cwebber** [comment]
You're right, previous delivery shouldn't be undone.  That deserves clarification.

**Comment by cwebber** [comment]
I put in a better example that's not as far-reaching.  Thank you for noticing this!

**Comment by strugee** [comment]
No problem! :)
