### ISSUE TITLE
Suggest delivery retry mechanisms

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#152]
The spec says that servers "SHOULD additionally retry delivery to recipients if it fails due to network error" but doesn't specify how this should be done. Seems like there should be a suggestion (i.e. a SHOULD or maybe just a note) on how this should be done, e.g. an exponential backoff kind of thing.

**Comment by cwebber** [comment]
We should suggest such a thing.  I think it would fit best in the security mechanism, which I _think_ makes this non-normative.  https://github.com/w3c/webmention/issues/48 and https://github.com/w3c/ldn/issues/32 both do this but I'm confused as to whether linking to Social Web Protocols handles this.

**Comment by cwebber** [comment]
Thanks, I did add text, as you can see above!  Between that and the reference to Social Web Protocols I think we're fine.
