### ISSUE TITLE
Incrementing like counts is a MAY

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#154]
8.4 Like Activity:

> The side effect of receving this in an inbox is that the server MAY increment the object's count of likes.

Why is this a MAY? Seems better as a SHOULD; this is what anyone would reasonably expect to happen and I don't really see a reason to not do this.

**Comment by cwebber** [comment]
Good point... done, and for servers that don't keep an integer but instead show a list of who has liked the object, widened the possibility of the effect a bit.
