### ISSUE TITLE
Let the "endpoints" actor property either be an inlined mapping or a link

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#157]
Many actors on a server will share all the same endpoints anyway.

**Comment by cwebber** [comment]
This is done in 9c5d67e.  I wouldn't mind someone reviewing it for sanity though... @rhiaro?

**Comment by rhiaro** [comment]
So this could look like...

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@id": "https://rhiaro.co.uk"/#amy,
  "name": "Amy",
  "inbox": "https://rhiaro.co.uk/ldn.php",
  "outbox": "https://rhiaro.co.uk/pub.php",
  "endpoints": "https://rhiaro.co.uk/prefs"
}
```

or

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@id": "https://rhiaro.co.uk/#amy",
  "name": "Amy",
  "inbox": "https://rhiaro.co.uk/ldn",
  "outbox": "https://rhiaro.co.uk/pub",
  "endpoints": {
    "@id": "https://rhiaro.co.uk/prefs",
    "uploadMedia": "https://rhiaro.co.uk/media",
    "proxyUrl": "https://rhiaro.co.uk/proxy"
  }
}
```

or

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@id": "https://rhiaro.co.uk/#amy",
  "name": "Amy",
  "inbox": "https://rhiaro.co.uk/ldn",
  "outbox": "https://rhiaro.co.uk/pub",
  "uploadMedia": "https://rhiaro.co.uk/media",
  "proxyUrl": "https://rhiaro.co.uk/proxy"
}
```

The maybe-problem being that the first two result in 

```
<#me> as:name "Amy" ;
...
<#me> as:endpoints <https://rhiaro.co.uk/prefs> .
<https://rhiaro.co.uk/prefs> as:uploadMedia <https://rhiaro.co.uk/media> .
<https://rhiaro.co.uk/prefs> as:proxyUrl <https://rhiaro.co.uk/prefs> .
```

and the last one is:

```
<#me> as:name "Amy" ;
...
<#me> as:uploadMedia <https://rhiaro.co.uk/media> .
<#me> as:proxyUrl <https://rhiaro.co.uk/prefs> .
```

I don't know if these two different places to check for a particular endpoint (the profile document _and_ the value of `as:endpoints`) is too much of an annoyance or not.

I like being able to push the endpoints off into a separate document in general, and the extra hop is fine. It's just when it may or may not be an extra hop that it's extra work.

**Comment by cwebber** [comment]
Ah, so maybe I didn't make clear what I meant by "inlined".  I meant the first two, but _not_ the last one.

By "inlined", I meant that the document was included inline, _or_ a separate link.  I didn't mean that you'd take the inline parts of the enpoint stuff and put them in the Actor object.  I guess that wasn't clear?

**Comment by cwebber** [comment]
Okay, I pushed what's hopefully some clearer text!
