### ISSUE TITLE
"Object creation without a Create Activity" transformation could use more precision

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#159]
All it really says about how to do this is

> The server then must attach this object as the object of a Create Activity.
> ...
> The audience specified on the object must be copied over to the new Create activity by the server.

What does this mean? There are at least 5 properties related to this: AS2#{to,bto,cc,bcc,audience}

The examples also imply more transformation than the text specifies:
1. in Example 11 '.published' and '.object.published' are the same value. Is this because the published value must be copied during transformation to a Create activity? Or because the Note and Activity creation happened within the same second? I hope the latter.
2. In Example 11, where did .object.id come from? Other sections talk about generating ids for activities, but not for sub-objects
3. In example 11, the addition of .object.attributedTo, .actor, and the inclusion of '@language' in the Note's @context (but no description of how/why it was modified from the original value in Example 10) distract from the point of this section and make it hard to know what's required of an implementation

Will you just enumerate the properties that must be copied, or otherwise more clearly specify the transformation algorithm? Ideally the two examples in that section can be used as minimal test cases for a simple implementation

**Comment by rhiaro** [comment]
Good shout. I think the answers are: 
- Audience properties are: `to`, `cc` and `bcc`. `bto` and `audience` were deprecated.
- The server SHOULD generate the current time as the `published` value for the new `Create` activity. This MAY be different from the `published` value of the object itself (in case this was set through the UI).
- The client posts the object, the server generates an `id` for it as you'd expect, _then_ generates the whole `Create` activity and uses the object `id` inside, as well as generating an `id` for the `Create` itself. At the point it hits the server, it's not a sub-object, it's top level. The wrapping happens second.
- I think we should add the `@context` and `@language` to example 10. They're supposed to be on every example as good practice. We should be clear about which values the server should generate if the client doesn't bother with them, like `actor` from the authenticated user who posts the creation request. But that belongs somewhere dedicated, not fogging up this section.

@cwebber should confirm this though, especially the `published` one.

**Comment by cwebber** [comment]
Will respond to the details shortly, but I've been somewhat uncertain of the usefulness of this.  This was mostly added when we thought we would definitely hit convergance with MicroPub.  It's somewhat somewhat of a tricky issue for another reason because determining what is/isn't an Activity requires having some idea of heirarchy which isn't actually expressed anywhere other than in the ActivityStreams Vocabulary document's text.  (It's not even marked up using RDF's "inheritance" mechanism!)

So I've marked it "at risk"!

**Comment by gobengo** [comment]
@rhiaro 

> bto and audience were deprecated.

... where/how? They still appear in activitystreams-vocabulary with 'MAY' descriptions. 'deprecated' doesn't appear anywhere in activitystreams-vocabulary, and only related to AS1 in -core.

> The client posts the object, the server generates an id for it as you'd expect,

ok now I see "a server receiving an object with no specified id should allocate an object ID in the user's namespace and attach it to the posted object."

But it's still ambiguous to me... should a server always generate IDs for every object (including nested ones) if they're missing? Or only for the originally-top-level object in this "double-pass" situation of posting a non-Activity to the outbox? If the latter, then it would be helpful to move/copy the above quote I missed from section 3.1 (Object Identifiers) to 7.1.1 (Object Creation without an Activity)

> I think we should add the @context and @language to example 10

I'm not sure what you mean. They're already in example 10? My complaint is that having them here also fogs up edifying the transformation, because the 'right way' of hoising the @context but leaving the '@language' in the .object is some pretty advanced JSON-LD fu that isn't germane to the section.

I agree it's best practice, but think clearly illustrating what's being specified should be a higher priority for these examples than 'best practice' in JSON-LD (which other editorial decisions are trying to steer clear of having to explain too much, right?).

---

> It's somewhat somewhat of a tricky issue for another reason because determining what is/isn't an Activity requires having some idea of heirarchy which isn't actually expressed anywhere other than in the ActivityStreams Vocabulary document's text.

Hmm. The non-normative ontology used to be linked to from the human-readable spec, but I guess isn't anymore. But it is still int he github repo, and does describe things with rdfs:subClassOf
https://github.com/w3c/activitystreams/blob/master/vocabulary/activitystreams2.owl#L721

In my implementation, I just did:

```
const activityTypes = [
  'Accept', 'Add', 'Announce', 'Arrive', 'Block', 'Create', 'Delete',
  'Dislike', 'Flag', 'Follow', 'Ignore', 'Invite', 'Join', 'Leave', 'Like',
  'Listen', 'Move', 'Offer', 'Question', 'Reject', 'Read', 'Remove',
  'TentativeReject', 'TentativeAccept', 'Travel', 'Undo', 'Update', 'View'
]
```

I for one kind of like this feature as its much more common in other APIs I've used to "POST an object to a Collection to create/add it there" than to "POST an object representing an intent to create another object to a Collection of Intents to have the side effect of creating it". I remember reading an early version of ActivityPub a year ago and I don't think this feature was there and my first reaction was just like "srsly I can't just POST an Article to the Outbox!?"

I also think this section is easily salvageable by simplying the examples and enumerating the properties that should be copied (which Amy started to do).

However, if there's no really compelling reason to have it, and it makes the spec simpler, I can understand cutting it.

**Comment by cwebber** [comment]
Just for clarity, marking "at risk" doesn't mean we're dropping it, just that it _might_ be dropped... as you know. :)

I agree it's generally helpful.

**Comment by cwebber** [comment]
> The server SHOULD generate the current time as the published value for the new Create activity. This MAY be different from the published value of the object itself (in case this was set through the UI).

We don't really say anything in the document about adding a `published` property to anything, except in examples.  I guess I kind of feel like it's implied.  There's a ton of fields in ActivityStreams and we don't always say when to attach each property exactly.  A lot of the fields go by example.  We could add text if it makes people happy though?

Anyway, there's no requirement that the wrapping `Create` and its embedded `object` have the same `published`, and I think readers can assume that by it not being explicitly mentioned.

> But it's still ambiguous to me... should a server always generate IDs for every object (including nested ones) if they're missing? Or only for the originally-top-level object in this "double-pass" situation of posting a non-Activity to the outbox? If the latter, then it would be helpful to move/copy the above quote I missed from section 3.1 (Object Identifiers) to 7.1.1 (Object Creation without an Activity)

I added some text to clarify this one.

> I'm not sure what you mean. They're already in example 10? My complaint is that having them here also fogs up edifying the transformation, because the 'right way' of hoising the @context but leaving the '@language' in the .object is some pretty advanced JSON-LD fu that isn't germane to the section.

Okay, I agree that it's a bit unclear as to how this would be done as an implementor here.  I think this is a case in point of the `@language` being embedded in the `@context`, which results in better RDF, but I think can end up making things much more confusing.

What I was trying to demonstrate here was that the upper level `@context` was the same for the wrapping activity and the wrapped `object`, so there was no reason to embed it twice.  But the `@language` didn't apply to the wrapping `Create`... the `Create` wasn't necessarily in English, or in any language.  So the `@language` property stayed on the `object` where it was.

Does that make sense?  What would make it clearer?  Maybe I could just leave the actual activitystreams context in the embedded `object`, which would be silly in its own way.

Sorry, I agree this part is confusing, but in satisfying the i18n group's request to have an `@language` here is hard when you also try to address the issue in https://github.com/w3c/activitystreams/issues/354

If we ignore the above linked-to issue, we could put `@language` as a separate property, and it'll make this whole thing _way_ less messy.  But the language property won't make it to the RDF, in that case.

Advice?  What do you think?

**Comment by gobengo** [comment]
> Does that make sense? What would make it clearer? Maybe I could just leave the actual activitystreams context in the embedded object, which would be silly in its own way.

That would address the issue of having to be quite knowledgeable about JSON-LD to understand why the examples are the way they are. Leaving the context in there would be redundant but not necessarily silly or invalid IMO.

I personally think the absolute clearest thing in this section would be to exclude '@language', .object.attributedTo, and .actor alltogether from example 11. To appease the i18n group, you could have a note underneath example 11 explaining that while it's best practice for clients to determine what language the user is submitting in, and include as @language, that it has been omitted from this example to more clearly illustrate the transformation being specified. Surely the i18n team would understand.

Either way, the @language and extra properties aren't _that_ big of a deal. So do what you think is best, including leaving as is.

---

**but**, the bigger issue here that I think really needs a change (i.e. I wasn't sure how to implement) is with:

> > The audience specified on the object must be copied over to the new Create activity by the server.
> 
> What does this mean? There are at least 5 properties related to this: AS2#{to,bto,cc,bcc,audience}

@cwebber Do you agree that the spec should "enumerate the properties that must be copied"?

@rhiaro , you said "bto and audience were deprecated". I asked "how/where"?

**Comment by cwebber** [comment]
@gobengo I'm fine with enumerating the properties that must be copied.  I'll do that.

**Comment by cwebber** [comment]
@gobengo re: `bto` and `audience` being dropped, I remember it happening due to a resolution, but I don't see it captured in the ActivityStreams issues.

I wish we could search through the SocialWG resolutions more easily. :(

**Comment by cwebber** [comment]
Huh... `to` and `bto` were removed [here](https://github.com/w3c/activitystreams/pull/101), though I don't remember `to` being removed.  But for whatever reason, `to`, `cc`, `bcc`, `bto`, and `audience` [are all properties in AS2 according to latest WD/ED](https://www.w3.org/TR/activitystreams-vocabulary/#audienceTargeting).  Though `audience` is not used for targeting AFAICT.

@jasnell or @evanp, do you remember what happened here?

**Comment by jasnell** [comment]
`to` and `bto` were never dropped. I had a proposal to do so but withdrew it.
`audience` _is_ used for targeting.

For example, suppose I have an activity that everyone in my company should see show up in their activity feeds, but only certain specific people should be notified, I would end up with something like:

``` js
{
  //...//
  "audience": {
    "type": "Organization",
    "id": "http://example.org",
    "name": "My Organization"
  },
  "to": ["http://jane.example.org", "http://joe.example.org"],
  "cc": ["http://sally.example.org"]
}
```

Here, the `audience` property provides a scoping of the overall audience, while the `to` and `cc` fields identify specific individuals within that audience that should be notified more directly of the activity.

**Comment by jasnell** [comment]
`to`, `bto`, `cc`, `bcc` and `audience` are definitely **not** deprecated and all deal with audience targeting.

**Comment by gobengo** [comment]
Given all this, I propose the following change:

Replace

> The audience specified on the object must be copied over to the new Create activity by the server.

With

> Any 'to', 'bto', 'cc', 'bcc', and 'audience' properties specified on the object must be copied over to the new Create activity by the server.

(if any of these properties _are_ dropped from AS2 later, we can ammend the section again. But in the interim this section will be more implementable)

@cwebber if you ack yes on this but don't have time to make a PR, I can attempt to so

**Comment by cwebber** [comment]
@gobengo Thanks for the clarification.  I can do it, but really appreciate the offer!  I want to make sure other sections of the doc also have caught up to new understanding of audience targeting as exposed in this issue :)

**Comment by cwebber** [comment]
Okay, added `bto` and `audience` to all relevant areas, and also gave a direct reference to the [ActivityStreams targeting section](https://www.w3.org/TR/activitystreams-vocabulary/#audienceTargeting), which I think is helpful information.  Thanks for your help on this!
