### ISSUE TITLE
Example of Public Content Addressing? And should an impl attempt to target/deliver to that URL?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#160]
AFAICT there are no examples of an Activity that is addressed to the public Collection. And I think one of these would be more useful than the current Example 4 in [that section](https://w3c.github.io/activitypub/#public-addressing), which is an example of serializing an object that _is_ the Public Collection.

Is this a good example of "Activities may additionally be addressed to the special "public" collection"?

``` json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "type": "Like",
    "object": "https://rhiaro.co.uk/2016/05/minimal-activitypub",
    "bcc": ["https://www.w3.org/ns/activitystreams#Public"]
}
```

When an outbox receives an activity that is addressed to the public collection, should it be a special case that skips targeting and delivery to this special URL (precluding that URL from ever receiving activities in its inbox), or is it just added semantic meaning and targeting/delivery to that place on www.w3.org should be tried as well (...meaning w3.org could eventually have a big cache of all the public activities flowing across ActivityPub implementations)?
- This above question most impacts my current implementing. Currently I am not delivering to this URI.

Also, it's surprising to me that you chose a URI that is a fragment of the activitystreams specification, which doesn't really seem like ActivityPub's namespace to claim frags on. Did you mean for the URI to be https://www.w3.org/ns/activitypub#Public ?
Oh, I see you have a TODO below that implying you were hoping to get it under the activitystreams specification. Perhaps one of the editors could weigh in on that request to move it forward (@evanp or  @jasnell).
I kind of think that the editor's draft of ActivityPub shouldn't claim that URI until the editor's draft of ActivityStreams defines it. Though I do think that it's a very important constant for the AS2 ecosystem to have around, since AS2 audience targeting is now in core.

**Comment by jasnell** [comment]
The actual identifiers for addressing are largely undefined. See https://github.com/jasnell/vocabs/tree/master/social for an experimental effort that I had been exploring...

**Comment by gobengo** [comment]
@jasnell That document clarifies a bunch of AS2 properties I frequently found ambiguous. Thank you for sharing it. What do you think about adding to AS2 (before it becomes a PR) the semantic equivalent of s:Public (or is it s:Everyone? I don't fully understand the difference, but think your definition of s:Everyone is most similar to what ActivityPub has proposed as https://www.w3.org/ns/activitystreams#Public?

Also, do you know the etymology of as2#audience relative to all this?

## 

@cwebber, of particular note in James' link above

> The key relationship between "scope" and audience targeting is that "scope" defines the population to which the object is visible while to/bto/cc/bcc define specific subsets within that scoped population to direct targeted notifications or special attention.

What do you think about having ActivityPub only using as2#scope property for Public Addressing instead of letting it be anywhere amongst the 4/5 other properties, which creates the ambiguity I asked above about whether I should actually send delivery traffic to that w3.org URL.

**Comment by jasnell** [comment]
as2#audience was originally as2#scope ... which is what I believe the documentation in the link I referenced still uses.

**Comment by gobengo** [comment]
@jasnell Ah, I should have seen that in the AS2 changelog. Sounds good. Thank you James.

You're kind of dodging my solicitation of a +/-1 for actually adding some of these terms to the current AS2 editor's draft, which is fine. :) I'll see what socialwg thinks about it next week. @evanp your thoughts before that are also appreciated

**Comment by jasnell** [comment]
heh... given that it took so long to get the current CR finished, I'm hesitant to add additional terms :-)

**Comment by rhiaro** [comment]
@bengo, we're not adding AP properties to the AS2 _spec_, but rather than namespace and JSON-LD context. So the namespace has terms defined across two specs in, in the end. That's my todo to actually carry that out.

**Comment by cwebber** [comment]
So I think @rhiaro answers all the questions about namespacing above.  That just leaves adding `as#Public` to some examples, yes?  I can do that.

**Comment by cwebber** [comment]
I guess one thing your bug specifies here is that we should clarify that you don't deliver to the Public endpoint; it's a special case.

**Comment by cwebber** [comment]
I added the Public collection to two more examples.

**Comment by cwebber** [comment]
Okay, and I added that servers MUST NOT deliver to the `Public` endpoint, since it isn't a real endpoint.

**Comment by cwebber** [comment]
How's that?  Does that sufficiently cover things to close this issue @gobengo?

**Comment by gobengo** [comment]
Yes that clarifies a lot, thanks.

On this issue and [#162](https://github.com/w3c/activitypub/issues/162#issuecomment-255446259) I've pointed out that it seems irresponsible to me for activitypub to be claiming frags/names in the activitystreams namespace. It's a separate issue from the practical issue you just clarified, and if I want to press it I'll file it separately. So I'll close this out.
