### ISSUE TITLE
in the section 7.9, change reference.

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#167]
In the section 7.9 Undo Activity, 
The Undo activity is used to undo a previous activity. See the ActivityStreams documentation on Inverse Activities and "Undo".

The 'Undo' activity is described in 'Activity Vocabulary' not in 'ActivityStreams'.
So, it should be changed like below 
See the Activity Vocabulary documentation on Inverse Activities and "Undo".

**Comment by cwebber** [comment]
Hm, good point... I always find "Activity Vocabulary" to be a bit unclear... it feels like it would be nicer if it were "ActivityStreams Vocabulary".

But anyway, yep, pushed an update!
