### ISSUE TITLE
Improve wording about default Activity addressing

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#170]
Section 7:

> Clients MAY address new Activities to the user's Followers Collection and/or the Public Collection by default. 

I understand why this is in here, but it's kind of confusing since it's kind of saying "clients MAY have a default" which doesn't make sense. Clients will pretty much always have defaults. It might be better to eschew the normative terminology and instead simply say:

> The Followers Collection and/or the Public Collection are good choices for the default addressing of new Activities.

**Comment by rhiaro** [comment]
I'm +1 this change, what say you @cwebber ?

**Comment by cwebber** [comment]
Sounds good, making the change now.  Thanks @strugee!

**Comment by strugee** [comment]
Sure thing @cwebber! <3
