### ISSUE TITLE
Clarify Exit Criteria Feature: "Discovering an actor's profile based on their URI."

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#173]
as annotation: https://hyp.is/8uDPZNfYEea37jceN1hGJQ/www.w3.org/TR/activitypub/

> 2.2 Candidate Recommendation Exit Criteria
> ... 
> * Discovering an actor's profile based on their URI.

For the purposes of an implementation report or test suite, what does this mean? Elsewhere in the document, the only time 'discovering' is used is wrt discovering an inbox or outbox, not a 'profile'. Do you mean something different than 'profile'. If not, what do you mean other than 'sending an HTTP GET request to a profile URI'?

**Comment by rhiaro** [comment]
I think that's probably what it means.. ie. do a GET request on the URI and expect a `as:Profile` type JSON object with the various attributes listed.

**Comment by cwebber** [comment]
Yes... I think it's also acceptable for it to simply pull down the actor as an actor type.  I'm adding clarification.
