### ISSUE TITLE
ActivityPub encourages use of jsonld profile with slightly different string than AS2 says

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#175]
excerpt from ActivityPub:
> To submit new Activities to a user's server, clients must discover the URL of the user's outbox from their profile and then must make an HTTP POST request to to this URL with the Content-Type of application/ld+json; profile="https://www.w3.org/ns/activitystreams#"

from AS2
> Because Activity Streams 2.0 can be considered a restricted profile of JSON-LD, Implementations should consider the `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` media type as being equivalent to `application/activity+json`.

Note that the profile parameter in ActivityPub ends with '#', while AS2 does not.

I think maybe this was a typo, and it would be best if ActivityPub removes the '#'. It hindered interop/testing between distbin.com and https://linkedresearch.org/ldn/tests/

**Comment by akuckartz** [comment]
Yes, the '#' does not make sense to me.

**Comment by rhiaro** [comment]
Looks like Chris fixed this in the ED in Feb but didn't close, so I'm labeling you satisfied.
