### ISSUE TITLE
github hosted spec is blank for me?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#176]
When I access the spec here: https://w3c.github.io/activitypub/

As the page is loading, I see the markup. But once the JS kicks in to apply the w3c styles, everything goes blank. This happens in chrome and safari for mac. There are no JS console errors.

Is it just me?

**Comment by gobengo** [comment]
This is happening to me with other specs too, not just yours. I assume it's my internet connection or shady Borneo ISP...

**Comment by cwebber** [comment]
Yeah I noticed I was having the same problem with the [json-ld community group report](http://json-ld.org/spec/latest/json-ld/) recently.  I'm not sure if it's the same issue.  It eventually loaded, but it took a really long time, and for a while it was blank.

Regardless it seems to be open here.  I don't think it's a problem on our end, but it may be a problem.
