### ISSUE TITLE
How do categories/tags work?

### ISSUE THREAD

**Issue by lumenwrites** [w3c-social/activitypump#177]
I have a blog that publishes articles, organized into major categories, with additional tags. I am submitting my articles into a reddit-like social network, and I want the tags of the reposted articles to match the tags of the original ones.

Tags seem like an important concept in general too.

What is the right way to implement them with ActivityPub?

**Comment by gobengo** [comment]
@raymestalez You could describe the tags using as2:tag https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tag

**Comment by lumenwrites** [comment]
Awesome, thank you!
