### ISSUE TITLE
Is anyone working on Python implementation?

### ISSUE THREAD

**Issue by lumenwrites** [w3c-social/activitypump#178]
Hey, everyone! I'm trying to figure out how to implement ActivityPub in python. I've never done anything like this before, so it would be really awesome to see some examples. If anyone is working on it - let me know!

**Comment by jaywink** [comment]
Hi @raymestalez . I've been wanting to implement ActivityPub in Python for some time, unfortunately time has been stopping me from doing that. I'm planning on adding ActivityPub support to my Python [federation library](http://federation.readthedocs.io/en/latest/), which currently has support for the Diaspora protocol. Would love some help or at least discuss some ideas. `federation` is a multi-protocol library, so it might not be what you want though, as the idea is not to implement pure ActivityPub, but create a library to abstract several protocols under one API.

Note for the actual ActivityStreams2 part, there is https://github.com/w3c-social/activipy already.

**Comment by lumenwrites** [comment]
Thank you for your reply! It would be really awesome if you'd add ActivityPub support, that would be perfect for my project. I'm still just beginning to figure things out, but I'd love to discuss ideas. 

Activitpy should be really helpful, thanks!

**Comment by lumenwrites** [comment]
By the way, I've made [ActivityPub](https://www.reddit.com/r/ActivityPub/) subreddit, figured it would be a good place to talk about this stuff. Nobody's there yet, but I think there'll be more people interested in the subject as the time goes by.

**Comment by rhiaro** [comment]
Hi @raymestalez, thanks for your interest. I'm gonna close this issue now since you have some answers, but feel free to open new ones if you run into trouble while you're implementing. You can also get us in #social on irc.w3.org.
