### ISSUE TITLE
"Latest editor's draft" link points to oldre version

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-social/activitypump#179]
A minor editorial issue

https://www.w3.org/TR/activitypub/ is
W3C Candidate Recommendation 17 November 2016

has a link: Latest editor's draft: 
https://w3c.github.io/activitypub/, which is
W3C Editor's Draft 02 November 2016

Is there a point to link to an earlier version, and using the word "Latest"?

**Comment by rhiaro** [comment]
Sorry for the delay in replying Vladimir! Well spotted. Editors need to remember to update the date on the ED when they make a new change.. I've updated it for @cwebber's latest commit now anyhow. Thanks!
