### ISSUE TITLE
Typo in `icon` property definition which affects implementations

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#180]
Section 4.1 Actor objects specifies that the `icon` property is a URI, but according to the AS2 vocabulary spec, it's a full-blown AS object (which _could_ be but is not necessarily just a URI).

**Comment by cwebber** [comment]
Argh, this one's a good point.

Arguably we could just remove the `icon` property, since AS2 already has it and has defined it for us.  I'm not sure if that would be less of a normative change.

**Comment by cwebber** [comment]
Suggested change (which I accidentally committed but reverted, see above, oops):

``` diff
-            A URI to an image which represents the user's profile picture
-            (this may be a thumbnail).
+            A link to an image or an Image object which represents the user's
+            profile picture (this may be a thumbnail).
```

What do people think?

**Comment by cwebber** [comment]
It could be that since this adds an option but doesn't break existing implementations which just used the URI that this is still normative.  Not sure.  (Or, again, we could just drop it and rely on the AS2 term... we rely on everything else from AS2 anyway.)

**Comment by rhiaro** [comment]
Alternatively we could remove any properties that are duplications of AS2, and make it clear that any properties on Actor in AS2 are also allowed.

**Comment by cwebber** [comment]
On that note, in a certain sense since it's already true that any properties on actor in AS2 are allowed, the spec isn't totally at odds with AS2's icon usage here, but it is a bit misleading.

**Comment by sandhawke** [comment]
Duplication betweens specs is generally best avoided...   I know it's a pain to follow references all the time, but it's better than having specs disagree.

**Comment by cwebber** [comment]
Also for context, I'm fairly certain this is a holdover from the earliest versions of what was ActivityPump; that's also before AS2 had gotten so far along in its standards process. I'm +1 on dropping the icon reference from this spec.

**Comment by strugee** [comment]
:thumbsup:

**Comment by cwebber** [comment]
The agreement of the group was that AS2 properties are considered the canonical, functional definitions, so it's fine to do one of the following for all of these:

* either drop them from the document, and just lean on AS2's definition
* or move them to an explicitly non-normative section saying as just clarifications on how the AS2 items may be used.
