### ISSUE TITLE
`oauthClientAuthorize`, etc. should be a SHOULD when relevant

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#181]
Section 4.1 Actor objects defines several URLs in the `endpoints` mapping having to do with authentication.

These should be SHOULDs if the relevant authentication scheme is implemented. E.g. for `oauthClientAuthorize`, instead of:

> If OAuth 2.0 bearer tokens [RFC6749] [RFC6750] are being used for authenticating client to server interactions, this endpoint specifies a URI at which a browser-authenticated user may obtain a new access token.

it should be:

> If OAuth 2.0 bearer tokens [RFC6749] [RFC6750] are being used for authenticating client to server interactions, this endpoint SHOULD specify a URI at which a browser-authenticated user may obtain a new access token.

Wording it this strongly guarantees better interoperability among servers implementing the same auth profile. It also allows clients to expect that if the relevant property is available, the server allows that authentication method (in other words, it lets the client efficiently discover the authentication profile used by the server as long as it's well-known enough).

**Comment by cwebber** [comment]
We don't shave SHOULD's on these other properties, and there's another side effect of adding a SHOULD here: it makes a stronger implication that OAuth 2.0 should be chosen as the auth profile, which isn't the case.  I think the OAuth 2.0 section already handles that, so I'm closing this.
