### ISSUE TITLE
Editorial bugs

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#183]
All of these are purely editorial and would not change implementations.

* Section 1 Overview: " In addition, certain activities posted by a user to their outbox may trigger certain operations on the user's behalf. Finally, activities may have side effects as they propagate throughout the social graph by being posted to the inboxes of other actors on the network." might be worded better/condensed as any operation triggered by an activity posted to the outbox is also regarded and referred to as a "side effect"
* Section 1. Overview, first example: "This activity causes the user's server to perform deliver of an activity on behalf of the user; in particular, it adds the specified object to the collection of objects the user has liked." - use of "in particular" is confusing since the side effect with the Likes collection in principle doesn't really have a lot to do with delivery.
* Same sentence, typo "perform deliver" instead of "perform delivery"
* Section 2.1 Specification Profiles: "it is called out whether they apply to the client or server (for the client-to-server protocol) or which of a pair of servers in the server-to-server protocol." - the end of this sentence is a bit awk and inconsistent
* Section 3. Objects - "A server should do something at least as robust as checking that the object appears as received at its origin" is a bit confusing at the end, probably better as "A server should do something at least as robust as checking that an object received by the server looks the same at its original location" or something
* Section 4.1 Actor objects - the `uploadMedia` description should probably link to the Uploading Media section

I gotta go to sleep, but that's what I've got. Good luck with CR! :tada:

**Comment by cwebber** [comment]
I updated all of them except the second to the last one, which is a bit awkward but I think that wording improvement isn't necessarily better.  Thanks!
