### ISSUE TITLE
Tracking likes and shares of an object

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#185]
[This was raised via a GNU Social user](https://social.heldscal.la/notice/1665592):

> is there any standard for saving the amount of likes / favorites on an object in ActivityPub?

Yikes, I did notice this at one point and I guess forgot to file it.  I guess it got lost in the shuffle.

Anyway, what we *should* do is the same thing that Pump.io does.  Here's an example object:

```json
{
"author":{"preferredUsername":"jankusanagi_test",
           "url":"https://pump.strugee.net/jankusanagi_test",
           "displayName":"Jan @ strugee's",
           "links":{"self":{"href":"https://pump.strugee.net/api/user/jankusanagi_test/profile"},"activity-inbox":{"href":"https://pump.strugee.net/api/user/jankusanagi_test/inbox"},"activity-outbox":{"href":"https://pump.strugee.net/api/user/jankusanagi_test/feed"}},
           "objectType":"person",
           "followers":{"url":"https://pump.strugee.net/api/user/jankusanagi_test/followers"},
           "following":{"url":"https://pump.strugee.net/api/user/jankusanagi_test/following"},
           "favorites":{"url":"https://pump.strugee.net/api/user/jankusanagi_test/favorites"},
           "lists":{"url":"https://pump.strugee.net/api/user/jankusanagi_test/lists/person"},
           "updated":"2016-08-29T13:11:13Z",
           "image":{"height":90,"url":"https://pump.strugee.net/uploads/jankusanagi_test/2016/8/26/R-Es-Q.gif","width":90},
           "location":{"displayName":"Hidden @ strugee's server, next to the DIMMs!","objectType":"place"},
           "summary":"Hey there =)\\n\\nTest account, to check the latest Pump.io server core development branch.",
           "id":"acct:jankusanagi_test@pump.strugee.net"},

"image":{"url":"https://pump.strugee.net/uploads/jankusanagi_test/2016/10/15/DAXEpQ_thumb.png","width":320,"height":230},
"fullImage":{"url":"https://pump.strugee.net/uploads/jankusanagi_test/2016/10/15/DAXEpQ.png","width":805,"height":581},
"objectType":"image",
"published":"2016-10-15T21:53:29Z",
"updated":"2016-10-15T21:53:29Z",
"links":{"self":{"href":"https://pump.strugee.net/api/image/iD3HX8jeRJKnnZQzjh1QSg"}},
"likes":{"url":"https://pump.strugee.net/api/image/iD3HX8jeRJKnnZQzjh1QSg/likes"},
"replies":{"url":"https://pump.strugee.net/api/image/iD3HX8jeRJKnnZQzjh1QSg/replies"},
"shares":{"url":"https://pump.strugee.net/api/image/iD3HX8jeRJKnnZQzjh1QSg/shares"},
"url":"https://pump.strugee.net/jankusanagi_test/image/iD3HX8jeRJKnnZQzjh1QSg",
"id":"https://pump.strugee.net/api/image/iD3HX8jeRJKnnZQzjh1QSg"
}
```

As you can see, each object has a `likes` attribute (a collection of objects that have liked the object), a `replies` attribute (which we have!), and a `shares` attribute.  For likes and shares, these are collections that point to all the objects representing the liking of sharing.  Collections of course can list their number of items as a cached "count number", but if instances decide they don't trust this, they can always verify by traversing the collection themselves (at the cost of additional network activity).

(Note that we have a `likes` already, which is really for Actors, the equivalent of Pump API's `favorites`... I think it might have even been called that before we moved ours to reflect `Like` being the canonical AS2 verb name.  That left out that there are two places that we'd want to record collections of `Like` objects though...)

**Comment by cwebber** [comment]
As an aside, I wish we had caught this earlier before it risks resetting the clock on CR.  Well, given increased attention of ActivityPub in the OStatus fediverse w/ Mastodon, GNU Social, and postActiv, I guess we might catch some things, which I guess is part of the whole process.  We *could* just do this via an extension, but that may well be the wrong thing to do; it seems like something that most instances will need.  Despite putting the risk of getting a shiny foil star that says "W3C approved standard" I think it's worth figuring out what's the right thing to do here.

**Comment by rhiaro** [comment]
We could add to 5.3:

```
Every object MAY also have a likes collection.
```

and 8.8 is almost there anyway:

```diff
The side effect of receiving this in an inbox is that the server should increment 
the object's count of likes
- , or perform other appropriate indication of the like being performed, such as 
- listing the liking actor amongst actors who have liked this object.
+ by adding the received activity to the object's like collection if this collection is 
+ present.
```

**Comment by cwebber** [comment]
We should also mention about whether you trust the number for security considerations

**Comment by cwebber** [comment]
Per amy's suggestion I think we'll rename actor's "likes" to "liked" and add "likes" and add "shares" to objects

**Comment by cwebber** [comment]
Okay, this should be taken care of now!
