### ISSUE TITLE
What activity represents sharing objects?

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#186]
Since #185 has already pulled out the concept of maybe adding a `shares` attribute; this leaves open the question, how do we represent "sharing" or "boosting" (or if you absolutely must, "retweeting") a message?  It's an extremely common social activity.

I believe we had a `Share` ActivityStreams and dropped it in favor of [Announce](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce).  IMO that's a mistake since Announce can be easily overloaded (the example shown doesn't look like a `Share`).

We can settle on `Announce` as that verb definitively in AP, but we should document it.  Anyway, if #185 is happening either in a way that issues a new CR or adds an extension, this issue should follow that one's lead.

**Comment by wilkie** [comment]
It was decided that Announce + Audience Targeting ("to": "your followers url", I suppose) was a clearer "Share"

https://github.com/w3c/activitystreams/pull/124
https://github.com/w3c/activitystreams/issues/179
https://github.com/w3c/activitystreams/issues/196

**Comment by cwebber** [comment]
Ah ok, I vaguely remember this.  Urgh.  I guess the reason it doesn't sound like Sharing is that it sounds like you're the original, active person on Announce, and that sounds like stealing credit.  But if that's hidden as a type that people don't see, I guess it's okay.

Okay, even if that's it though, we should call it out somewhere, even non-normatively (it shouldn't have any side effects other than being posted to the timeline anyway) so people know what to use.

**Comment by wilkie** [comment]
I think another idea with Announce is that it is more obviously extensible? Announce simply draws attention to an existing object... the targeting lets you "boost" to just 1 person, or to your private circle, etc. Whereas a "Share" type would be less clear that you could do something like this "privately".

**Comment by cwebber** [comment]
Seems like Share is really a subtype of Announce then.

**Comment by wilkie** [comment]
Yeah. Pretty much.

**Comment by cwebber** [comment]
ok, Announce is "share", will add side effects
