### ISSUE TITLE
Inbox required on actors but not used by non-federated servers

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#189]
All actors are required to have the `inbox` property, but only federated servers are required to implement the ability to receive things to an `inbox`. So having the property attached to profiles on non-federated servers is redundant. We should probably qualify that `inbox` is only a MUST for federated servers.

**Comment by rhiaro** [comment]
Or we add a feature that allows non-federated servers to receive things to an Inbox and carry out local side effects (updating collections) but aren't required to carry out server-to-server side effects (ie. sending out things to other people's inboxes).

**Comment by cwebber** [comment]
Note that a non-federated, client-to-server server still usefully has a purpose for an inbox on actors anyway... doing a GET on an inbox is how you see the stream of notifications coming to your client.  This could either mirror the posts you made to the site, or they could be some stream of notifications generated by the site.

Adding a feature for non-federated servers to have side effects without server to server side effects is confusing me... do you mean, not propagate on distribution?  Wouldn't that be solved by simply not including any addressing?

**Comment by rhiaro** [comment]
Okay, keeping `inbox` for GET is fine but there might be somewhere we need to make it clear that's what's going on?

>  Wouldn't that be solved by simply not including any addressing?

But clients take care of addressing, and they don't necessarily know if they're sending to a federated server or not?

I mean there's no reason a federated server with an inbox can't receive POSTs and then if it's say a Follow or a Like, update its own local collections. But it wouldn't distribute that to its followers. Maybe having a followers collection that it doesn't post out to is useless though?

**Comment by rhiaro** [comment]
Hm.. So you're saying stuff (notifications) can get into the inbox by some other means than being POSTed to?

**Comment by cwebber** [comment]
> But clients take care of addressing, and they don't necessarily know if they're sending to a federated server or not?

I'm confused... clients don't POST to inboxes, they POST to outboxes.

> Hm.. So you're saying stuff (notifications) can get into the inbox by some other means than being POSTed to?

Sure, from the same origin as the server... reading from the inbox via GET is for the benefit of sending something to the client.  You might play a game running on your own server, and get game notifications.  Or you might have a notification saying "your media storage is nearly full".  Imagine if you're doing client to server only... is it write-only, or is the server showing things?  If it's a blog, it's probably showing blogposts (things *you* posted to your outbox, even though they aren't federated anywhere).  And it's not surprising that "system notifications" of some sort might show up there too.

**Comment by rhiaro** [comment]
Okay so I forgot about the case where there are multiple users on a non-federated server, and the server uses its own internal mechanisms to put things in the inbox, which is still useful for clients to read. So a read-only inbox on a non-federated server is a thing.

Might I suggest the following non-normative clarifications:

5.5:

```diff
- The inbox accepts HTTP POST requests, with behaviour described in Delivery. 
+ The inbox of actors on federated servers accepts HTTP POST requests, with behaviour 
+ described in Delivery. Non-federated servers SHOULD return a 405 Method Not Allowed 
+ upon receipt of a POST request.
```

8.1:

```diff
An HTTP POST request (with authorization of the submitting user) is then made 
to the inbox, with the Activity as the body of the request. This Activity is added by 
the receiver as an item in the inbox OrderedCollection. 
+ Attempts to deliver to an inbox on a non-federated server SHOULD result in a 
+ 405 Method Not Allowed response.
```

**Comment by cwebber** [comment]
I'm in support of doing this.  Would be a normative change, but that's ok; now's the time to do it.

**Comment by cwebber** [comment]
Group decided to add this text, so I'm going to do it.  (I'm also going to check if any other GET / POST on inbox/outbox need to say 405 Method Not Allowed if not implementing, but will file that as a separate ticket.)

**Comment by strugee** [comment]
Submitted a PR adding the proposed text but didn't do the checking Chris mentioned above, so leaving open.

**Comment by cwebber** [comment]
I opened #217 to handle to handle other endpoints, as we discussed on the call, so I'm closing this one.
