### ISSUE TITLE
Remove the NOTIFY method

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#19]
The NOTIFY method can and should wait until we're ready to deal with the federation protocol.

In addition, adding a new HTTP verb is a really big deal. It's hard for a lot of servers to implement. It's also functionality that can easily be handled with a webhooks pattern.

**Comment by xray7224** [comment]
I spoke to @oshepherd in in the WG social channel today and he seems fine with removing this. I think we should go ahead and do this then.
