### ISSUE TITLE
OAuth 2 token endpoint missing

### ISSUE THREAD

**Issue by puckipedia** [w3c-social/activitypump#191]
Currently, an `Actor` object's `endpoints` contains a `oauthClientAuthorize`, which I would read as the authorization endpoint from RFC 6749. However, this doesn't allow the ActivityPub client to use the authorization code grant. Adding a token endpoint to the `endpoints` would allow people to properly implement the entire OAuth 2.0 flow.

**Comment by cwebber** [comment]
Thanks for the comment!  I'm less familiar with OAuth 2.0 than I should be.

@aaronpk, does this seem right to you?  See the endpoints section in [Actor objects](https://www.w3.org/TR/activitypub/#actor-objects) and the [current recommendations around OAuth 2.0 and JSON Web Signatures](https://www.w3.org/TR/activitypub/#authorization-oauth).

**Comment by aaronpk** [comment]
Yes, there needs to be a token endpoint specified which is where the app will exchange the authorization code it got from the authorization endpoint for an access token.

Here's a brief intro to the concepts: https://aaronparecki.com/oauth-2-simplified/#web-server-apps

**Comment by aaronpk** [comment]
Here are the names of the endpoints used by the OAuth 2.0 Discovery spec: https://tools.ietf.org/html/draft-ietf-oauth-discovery-06#section-3.2

Specifically, `authorization_endpoint` and `token_endpoint`

**Comment by sandhawke** [comment]
Should this be in AS, AP, or just a mapping of oath into URIs, so it can be used in JSON-LD?

**Comment by erincandescent** [comment]
Part of me thinks we should drop the oauthClientAuthorize parameter and instead link to an OAuth 2.0 discovery document (see the soon-to-be-RFC IETF draft @aaronpk linked to above).

That discovery document also tells you how to register a client (using OAuth 2 Dynamic Client Registration)

**Comment by cwebber** [comment]
> Should this be in AS, AP, or just a mapping of oath into URIs, so it can be used in JSON-LD?

I'm ok with dropping the endpoint parameters if that's the right thing?
Is there another json-ld context somewhere which has these defined?
