### ISSUE TITLE
Profile's usage could be described better

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#192]
The possible usage of an AS2 [Profile](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-profile) object is mentioned in the exit criteria section:

>  Discovering an actor's profile based on their URI (either the representation of the actor itself, which is probably an Actor Type, or a Profile object describing the actor). See the Actors section of this document for more information on what information is expected.

But in the [actors section](https://www.w3.org/TR/activitypub/#actors) it doesn't come up again.  @rhiaro, I wonder what you think about this, since you've put some thought into actors having multiple "profiles", eg as possibly different identities in different contexts?

**Comment by cwebber** [comment]
This is may be non-normative but I'm not sure.

**Comment by rhiaro** [comment]
Hm, I did't quite realise that `Profile` is not an 'actor type'. Which is fine. I'd support:

```diff
Actors are [ActivityStreams] Objects, generally one of the ActivityStreams Actor Types, 
+ or a Profile object,
and are retrieved like any other Object in ActivityPub
```

This reads like informative text to me.

**Comment by cwebber** [comment]
We agreed to accept this w/ adding a new test case
