### ISSUE TITLE
Delivering to actors on the same server, including the activity's actor

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#198]
It's never mentioned that activities can be distributed to actors on the same origin without having to resort to an HTTP POST.  I guess anyone could figure this out if they wanted to, so it probably doesn't matter.

But these bits are awkward because of it:

> Servers MUST de-duplicate the final recipient list. Servers MUST also exclude actors from the list which are the same as the actor of the Activity being notified about. That is, users shouldn't have their own activities delivered to themselves. 

> An HTTP POST request (with authorization of the submitting user) is then made to to the inbox, with the Activity as the body of the request. This Activity is added by the receiver as an item in the inbox OrderedCollection. 

That first paragraph's MUST around excluding the actor which is the same as the actor from the activity is maybe strange... an actor's own activity may realistically end up in their own inbox, if we consider how Twitter or Facebook or nearly anything have it so that your own posts end up visible in your own stream.

**Comment by cwebber** [comment]
I'm okay with closing this and taking no action on it, since I think it seems probably obvious enough that it's a non-issue with the current text, but I thought I'd raise it while we were considering resetting the clock on CR anyhow.

**Comment by rhiaro** [comment]
> may realistically end up in their own inbox

But definitely shouldn't be `POST`ed there!

Although... unless... the inbox is on a different server to the sending outbox..... (don't mind me)

We could add

> The following is required by federated servers communicating with other federated servers only. 

and add a 

> **Note**: Activities being distributed between users on the same origin may use any internal mechanism, and are not required to use HTTP.

**Comment by cwebber** [comment]
We resolved to include the text Amy suggested here.
