### ISSUE TITLE
change explanation about Actor objects in the section 4.1 Actor objects

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#199]
I'm a little bit confused of the explanation about the  Actor objects in the section 4.1.

> 4.1 Actor objects
> Actor objects are ActivityStreams objects which are subclasses of the Actor type. 

There is no mention or explanation that Actor objects are the subclasses of the Actor type in AS2 document. 
Activity Vocabulary document tells only that Actor type includes 5 Actor types : application, group, organization, person, service.
And AS2 explains about actor object like this : 
Actor objects are specializations of the base Object type that represent entities capable of carrying out an Activity.  

So, I recommend to use above explanation in AS2 for the first sentence of section 4.1.

**Comment by strugee** [comment]
Related: #193

**Comment by cwebber** [comment]
We dropped the mention of actors as subclasses when resolving #193 so I believe we resolved @PaulJeong14's request.  Please feel free to reopen if I'm wrong!
