### ISSUE TITLE
Authorization out of scope?

### ISSUE THREAD

**Issue by xray7224** [w3c-social/activitypump#2]
I believe the WG has decided that authorization is out of scope, if that's the case should we remove authorization considerations from the specification?

**Comment by xray7224** [comment]
I have removed the section on authorization as I believe it falls out of scope however I have left sections in which say a server may implement their own authorization and that they should fail requests that don't pass their authorization for private objects. I have also left methods which require authorization.

**Comment by xray7224** [comment]
This was a misunderstanding, I have reverted it now. I think we should go ahead with OAuth 2.0 as the authorization framework.

**Comment by gobengo** [comment]
@xray7224 I agree, though I think that oAuth2 alone isn't normative enough to implement in an interoperated, federated way. I've had a pleasant experience working with [OpenID Connect](http://openid.net/specs/openid-connect-core-1_0.html) (OIDC, different than old OpenID, OIDC is on top of oAuth2) in the last few months at @Livefyre, as we've been implementing our own oAuth2 provider.

I think it's healthy to work on SocialWG without the burden of auth{n,z}, I'm mostly just sharing for others who may be in a similar position.

**Comment by evanp** [comment]
I really think this section should be gone.

**Comment by xray7224** [comment]
@evanp You don't think there should be section on authorization at all?

It does't really make sense without one, how would two servers speak to each other if this section isn't there.

**Comment by cwebber** [comment]
Originally I thought we had agreed at the Face 2 Face that this was out of scope to be even mentioned in here, but it lead me to wondering: how could interoperability *actually happen*?  So I was surprised to see that Micropub had OAuth 2 as a required authorization system via IndieAuth, but Tantek clarified that it was out of scope for the group to do any work on defining authorization standards, but that it made sense to reference them in our specs.

So, if we're going to remove it, what would that mean for interoperability?

**Comment by xray7224** [comment]
This hasn't had any activity for a while, I think authorization is very important for interoperation and it seems all the others also agree on OAuth 2.0 bearer. I think I'll close this for now, if you think you have more to add please re-open.
