### ISSUE TITLE
SVG version tutorial Illustrations

### ISSUE THREAD

**Issue by ghost** [w3c-social/activitypump#202]
I just realized I missed some feedback regarding the illustrations on mastodon. So I put them here as preview and and attach the source files

### *preview*
![1](https://cloud.githubusercontent.com/assets/164785/25296473/bc286e64-26e8-11e7-8cc8-efae1347d2a2.png)
![2](https://cloud.githubusercontent.com/assets/164785/25296471/bc26a912-26e8-11e7-9803-1b28f1b51f74.png)
![3](https://cloud.githubusercontent.com/assets/164785/25296472/bc26d0f4-26e8-11e7-9960-9613890a5241.png)
![4](https://cloud.githubusercontent.com/assets/164785/25296470/bc244b5e-26e8-11e7-84c3-24e31793d044.png)
![5](https://cloud.githubusercontent.com/assets/164785/25296474/bc291936-26e8-11e7-97e2-ffb8fa2ea7de.png)
[ActivityPub-Illustration-source.zip](https://github.com/w3c/activitypub/files/948341/ActivityPub-Illustration-source.zip)

**Comment by strugee** [comment]
Wowza. These look great.

**Comment by cwebber** [comment]
These look super good @mray !  THANK YOU so much!

So, we just need one of two things from you: either authorization to publish under [the permissive document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) that ActivityPub itself is published under, or for you to ACK releasing these images under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) (or I think [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) also works).  Your choice!

**Comment by ghost** [comment]
I go with what I expect to be your preference here then: the permissive document license.
No hard feelings though.

**Comment by cwebber** [comment]
I hate to raise this, but quoting carven from irc:

> &lt;csarven&gt; cwebber: I hate to be that guy (well sometimes) but I suggest running those illustrations through colour accessibility tests. Some of the foreground/backgrounds don't have sufficient contrast in my opinion. I would also lean on them being monochrome friendly so that if the spec is printed in greyscale, it'd be still legible =)

I don't know, what do you think @mray?  The drawings look really good as-is, but I understand that someone who has vision issues may have problems with it.  I wonder if such a change could be made without a large loss in image quality?

**Comment by ghost** [comment]
I think the contrast isn't that bad - it could be better. Color is carrying information here, and while there may be ways to do that monochromatically I also think it is ok as is. That said I don't really share the concern unless accessibility is of particular interest. @cwebber do you think spending more time on this is necessary?

**Comment by cwebber** [comment]
I think it's not absolutely critical personally, mainly because the images are optional in the tutorial anyway... all that information is in the text too (which is necessary for its own accessibility reason, in case someone is completely visually impaired).  If you don't feel motivated to do it, I'm okay with including them as-is.

**Comment by ghost** [comment]
I've invested enough time for now - if this being W3C and all turns out to be important after all: ping me.
It is also freely licensed, so...

**Comment by cwebber** [comment]
Your time on it is really appreciated @mray :)
