### ISSUE TITLE
activitypub profile discovery

### ISSUE THREAD

**Issue by donpdonp** [w3c-social/activitypump#204]
I'm trying to piece together the activitystream steps and I havent seen a spec for finding someone's "Person" object from a homepage url. I looked at an existing identifier I had on my homepage

```html
<link rel="alternate" type="application/ld+json" href="webid.json"/>
```

and fixed it up to look more like something an activitypub service might discover.

```html
<link rel="me" type='application/ld+json; profile="https://www.w3.org/ns/activitystreams"' href="as-person.json"/>
```

I'm not sure if the profile part of the mime-type belongs in the type field. I put indieweb's "me" rel in place of "alternate" because its friendlier. I dont expect anything to consume this tag today, I just added it to my site (donp.org) to see how it might work.

**Comment by csarven** [comment]
Wouldn't the relation be along the lines of primaryTopic/creator/maker?

**Comment by donpdonp** [comment]
there was some discussion on the w3c irc meeting today
https://socialwg.indiewebcamp.com/irc/social/2017-04-25#t1493136042420

with the conclusion being 

```html
<link rel="alternate" type="application/activity+json" href="as-person.json"/>
```
would be an acceptable <link> tag.

**Comment by cwebber** [comment]
I think the conversation from today is that those are acceptable link relations and are informative / welcome for people to put places.  Our official way of moving from a link describing an actor to their profile is via content negotiation though.  That said, a client might even know how to look up a profile based on finding that on a uri, but we aren't putting that in the official spec, doing so would be an extension... but maybe defining such an extension would be good work to do through the [community group](https://www.w3.org/community/swicg/).

Does that answer things @donpdonp?  Thanks! :)

**Comment by donpdonp** [comment]
given "donp.org", and needing a json Person document for activitypub operations, doing a GET with `Accept: application/activity+json` seems ok as one way to get this document. 

As a recommendation for someone trying to add an activitystream identitiy to their website, using content negotiation seems like a rocky path. The average php hosting service for example, does not have a paradigm in its UI for a document per mime type. Even with full control of an nginx config, its an unusual kind of configuration entry.

Having link rel="alternative" as a fallback is a great alternative. Anyone who knows how to edit html will be able to add an extra tag linking to the url of the json document for that person.

**Comment by strugee** [comment]
I've added this to the list of possible AP extensions: https://www.w3.org/wiki/ActivityPub_extensions
