### ISSUE TITLE
Required properties for actors

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#22]
There are a lot of required properties. Couldn't they just be discovered using the actor's ID?

**Comment by akuckartz** [comment]
I am not sure I unterstand the question. Do you want information about required properties to be made available in a machine readable format? (I would agree with that.)

**Comment by cwebber** [comment]
This bug is unclear... I have no idea what it means.  I'm closing it for now, but feel free to open if you can clarify what you meant.
