### ISSUE TITLE
Add a Tag type

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#235]
We resolved on the Community Group call today to add a Tag type to the ActivityPub spec.  Multiple implementers found it frustrating that there's a specific object type for Mentions, but not for everyday text-style tags.

**Comment by nightpool** [comment]
Question about details—is this something we need to do with ActivityStreams? Or can we just say that ActivityPub extends ActivityStreams in this way?

My understanding is that so far we don't extend AS2 anywhere—AP says "ActivityPub uses [ActivityStreams] for its vocabulary". Are we comfortable with this change? What are the other options?

As far as the standardization process goes, what's the best move here?

**Comment by cwebber** [comment]
ActivityPub already extends ActivityStreams.  The `inbox` and `outbox` are terms not in AS2 itself.  Per past resolutions of the group we have permission to do this.  (Good question though!)

**Comment by cwebber** [comment]
We're going to wait on James Snell's comments on this to hear why it wasn't in AS2.  Also Evan and AJ both say that *if* we did it, it shouldn't go in ActivityPub because it's not an AP specific extension, it should be an independent extension

**Comment by tantek** [comment]
Links to where the use-cases are documented for this?

**Comment by cwebber** [comment]
Don't have time at the second to pull up notes, but @gargron said that Mastodon went ahead and added a Tag object.

BTW, I think we should get an answer from James on this, but I think this may fall under the "this should be an extension because it's not a requirement for the protocol to work" aspect.

**Comment by rhiaro** [comment]
What would `Tag` actually help with that isn't possible already? I realise I missed the discussion on this.

Off the top of my head, if you follow the `as:tag` relation and find an `as:Object`, the UI is going to want that object's `name` I expect, which it can get regardless of the type of that object. Anything else?

In my implementation (sloph), tags are `as:Collection` types, and every post tagged with them is discoverable through `as:item`.

Or maybe this is for tags which don't have a URI, only a string, which would be a value for `name` on an `as:Object`? (ie. blank nodes). Still, if you go from an `Activity` or `Object` through the `as:tag` property, and find a generic `Object` there, you can infer that it's a tag...

**Comment by cwebber** [comment]
Part of the rationale was that Mention has its own type, very specifically for this type of thing, but "Hashtag" type string identifiers doesn't have a type which is weird, and maybe even not helpful for people who are trying to map this to localized types clearly?  But I may be forgetting; perhaps @Gargron can refresh our memories on their motivation?

**Comment by tantek** [comment]
I have the same questions (confusion?) as @rhiaro I think. But I'm also ok with a "tag-of" type parallel to "mention" (assuming that's pre-existing).  For reference, indieweb posts have had this specific response for a while: https://indieweb.org/tag-of which is a type under consideration in Post Type Discovery https://www.w3.org/TR/post-type-discovery/#othertypes (Update: added https://github.com/tantek/post-type-discovery/issues/28)

**Comment by Gargron** [comment]
I have added type: "Hashtag" to Mastodon because when I'm parsing the "tag" attribute and iterating over the items I'd like to know what the item is. A "Mention" type exists so there should be a "Hashtag" type as well.

**Comment by cwebber** [comment]
[Proposed as an extension](https://www.w3.org/wiki/Activity_Streams_extensions#Hashtag_type) to the SocialCG (and we'll be talking about the process for getting things in at the SocialWG this week, and raising it on the SocialCG call).

**Comment by cwebber** [comment]
I asked @jasnell about this and got the following response:

> I think at this point if they have found a solid use for it then ++

Let's make it happen!

**Comment by rhiaro** [comment]
To clarify, is the proposal for `Hashtag` or `Tag`? `Hashtag` seems to me a bit twitter specific, but `Tag` is more generic and doesn't imply a microsyntax requirement.

**Comment by Gargron** [comment]
@rhiaro I believe "Tag" would be at least slightly confusing due to the presence of the "tag" property. "tag" containing Mention and Tag vs "tag" containing Mention and Hashtag. In the end, I do not really want to push a specific wording as long as the meaning is the same. Tag, Hashtag, even Category, would all fit the task.

**Comment by jasnell** [comment]
Hello all! Really quite happy to see progress moving forward on real implementations!

I wouldn't get too hung up on the `Tag` vs. `tag`, developers will adapt to whatever works. I also wouldn't worry so much about `Hashtag` vs. `Tag` given that the two are generally synonymous these days.

**Comment by nightpool** [comment]
i would be 👎 on Hashtag personally, but it's also a pretty weak opinion. the meaning is what matters

**Comment by cwebber** [comment]
I was leaning towards `Tag` but @evanp made the case on a call iirc for `Hashtag` indicating that it was a specific type of tag, one where it's a string referencing some sort of grouping of objects... after all, `Mention` is also a "tag" in our system but we're calling out `Hashtag` as having a very different user than `Hashtag` (or `Tag`) does.  I thought that was compelling.

**Comment by evanp** [comment]
Is there an example somewhere? Or is this about right?

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://tags.pub/mozfest",
  "name": "#mozfest",
  "content": "Mozilla Festival"
}
```

**Comment by evanp** [comment]
Also, how do I get the collection of activities or objects that have a particular hashtag? I don't think it should be `inbox` or `outbox`.

'tagged' ? 'tagged-by'? 'tagged-in'?

**Comment by evanp** [comment]
There's a similar problem with finding the collection of activities that have an `Object` as their `object` property. For example, the edit history of an Article.

**Comment by cwebber** [comment]
> Also, how do I get the collection of activities or objects that have a particular hashtag? I don't think it should be inbox or outbox.
 
I guess I was going to say do a GET against `https://tags.pub/mozfest` w/ the the AS2 mimetype and you'd get back a collection, but you wouldn't get back a collection necessarily... (you could maybe do a composite type of `["Hashtag", "OrderedCollection"]` but I dunno how people would feel about it).

Regardless the proper conversation for this now is probably [this issue](https://github.com/swicg/general/issues/6).  Note that @Gargron and company have implemented tags in Mastodon; maybe speak with them?
