### ISSUE TITLE
Perhaps move Likes/Shares Collection to an AS2 extension

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#236]
As discussed on the call today, this may or may not make sense given this resolution:

> RESOLVED: vocabulary extensions unrelated to the protocol aspects of AP should be handled as AS2 extensions and not as part of AP

**Comment by cwebber** [comment]
As I said on the call, likes/shares are *mentioned in the protocol* in terms of how Like/Share works in a federated context, so they're part of the protocol.  They can (and should) stay and keep this resolution.

Removing them from the spec will break the spec.  -1.

**Comment by rhiaro** [comment]
Seem pretty integrated into the AP protocol to me.

Even given that the Likes and Shares collections may be useful to other systems, doesn't mean it's any more difficult for those other systems to use them from the AP vocab than from an extension vocab.

**Comment by strugee** [comment]
@cwebber I'm a little unclear as to what you mean by "they're mentioned in the protocol"? You mean the side effects?

To me there's two issues here:

1. Collections of what the actor has liked/shared
2. How activities actually end up in those collections

I'd argue that (2) is definitely a part of the ActivityPub protocol, but (1) is not. Audience targeting isn't an ActivityPub extension because it's something useful to all AS2 consumers and producers; instead, ActivityPub specifies _how_ audience targeting is carried out. I can see a use for an AS2 extension that says "there's a Likes collection here, there's a Shares collection there," and doesn't specify how activities actually end up in there.

That all being said I don't feel terribly strongly about this so if the WG wants to close anyway that's fine by me.

**Comment by strugee** [comment]
Also to clarify my intention was that if we _did_ move this into an extension we'd make it mandatory to implement that extension. Maybe just not worth the effort, though? Dunno.

**Comment by jaywink** [comment]
Strong feeling that like/share are central to a social protocol. They form fundamental central parts of how people communicate on social networks. 

Removal -1 too.

**Comment by strugee** [comment]
@jaywink I wonder if you read https://github.com/w3c/activitypub/issues/236#issuecomment-314530464? Again, we wouldn't be "removing" it, just moving where it's defined in the spec.

**Comment by cwebber** [comment]
> Also to clarify my intention was that if we did move this into an extension we'd make it mandatory to implement that extension. Maybe just not worth the effort, though? Dunno.

If we'd do that, we'd also have to do it for inbox, outbox, followers, following, etc.  I don't think it's worth this effort to separate it.  ActivityPub is the driving force for including these.

**Comment by strugee** [comment]
Okay. As I said I don't feel strongly about this so I'm fine closing it.
