### ISSUE TITLE
Link to OAuth-Server-Metadata has broke

### ISSUE THREAD

**Issue by arcanicanis** [w3c-social/activitypump#237]
It seems that the location for the reference "OAuth-Server-Metadata" has moved, leaving a 404 in it's place. The new address appears to be: https://tools.ietf.org/html/draft-ietf-oauth-discovery-06

**Comment by strugee** [comment]
Fixed by #230 (I think?)

**Comment by arcanicanis** [comment]
Yes, that would seem to resolve it. Not sure why I didn't check first before opening a new issue.

**Comment by strugee** [comment]
@Takyoji no problem! GitHub's web interface isn't exactly great at encouraging that kinda thing anyway.
