### ISSUE TITLE
mediaUpload: only post to outbox if it's a Create activity?

### ISSUE THREAD

**Issue by puckipedia** [w3c-social/activitypump#239]
`mediaUpload`, when posting any object, also posts it into the outbox. This is an issue, because you can only upload one file at a time. So you can't make e.g. a 4-picture post?

Per IRC:
```
<puckipedia> maybe if it's a Create activity, post it into the outbox, else just give it an ID?
<cwebber2> so you'd need an extra boolean in the form
<cwebber2> puckipedia: so make a {Video} as opposed to {Create: {Video}} ?
<puckipedia> well, if you send it as {Create: {Video}} it's post it into the outbox. if you send {Video} it only gives it an ID
<cwebber2> right, the id of the Video only
<cwebber2> but not post it wrapped in the Create to the outbox
```

**Comment by cwebber** [comment]
I'll get this integrated.  Thanks for raising the issue @puckipedia :)

**Comment by strugee** [comment]
Linking to https://www.w3.org/wiki/Socialwg/2017-07-11-minutes#ActivityPub for posterity where we discussed a lot of things that didn't get captured in this issue.

**Comment by cwebber** [comment]
I'm starting to lean towards us dropping mediaUpload, since it's not clear we'll get the semantics right in time and it's at risk?

**Comment by cwebber** [comment]
we can always do as an extension

**Comment by cwebber** [comment]
```
<eprodrom> RESOLVED: Resolve https://github.com/w3c/activitypub/issues/239 by                      
           removing mediaUpload and specified behavior from ActivityPub spec                       
           proper, move to extension via SocialCG process
```

**Comment by cwebber** [comment]
I will make a new document proposing behavior and bring to the SocialCG tomorrow.

**Comment by rhiaro** [comment]
I dumped the text from AP to https://www.w3.org/wiki/SocialCG/ActivityPub/MediaUpload for refinement by the CG (and added the `uploadMedia` property to https://www.w3.org/wiki/ActivityPub_extensions#uploadMedia).
