### ISSUE TITLE
"Follow your nose" referencing of user endpoints unspecified

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#24]
Presumably an implementation seeing the `actor` field of an activity or some other addressing is able to use that address to find the inbox/outbox endpoints of said user.  However, our documentation does not specify how this happens, probably because previously this was specified to use webfinger.

Assuming we are taking a "follow your nose" type approach, there needs to be some way to extract those endpoints from the referenced page.  I would suggest that the method of extracting endpoints be based on the content type of this URL: we should be able to these fields from an RDFa or microformats implementation, or alternately if there's an activitystreams actor representation, we could observe the inbox/outbox fields from that.

What do you think?

**Comment by cwebber** [comment]
Actually, what we should almost certainly do is [embed JSON-LD in the HTML](http://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents) itself.  This meshes with the approach we're already taking.

**Comment by elf-pavlik** [comment]
http://w3c-social.github.io/activitypump/#actor-objects

Already uses *outbox* and *inbox* properties. They would just need proper definitions under ActivityPump namespace #30 

Another option could take path similar to rel="micropub" and rel="webmention" which stay registered with http://microformats.org/wiki/existing-rel-values (IMO it doesn't allow it's short form use in HTTP headers!  https://github.com/aaronpk/Micropub/issues/1 & https://github.com/converspace/webmention/issues/38)

**Comment by xray7224** [comment]
I agree with @cwebber that embedded JSON-LD as he linked is the way we ought to go, it seems the natural fit for what we have already.

I was going to suggest that if the client has `application/ld+json` in their `Accept` header then the server *can* respond with just the JSON-LD but I don't know how useful that would be in practice unless we required it which could cause problems with static sites. Because of that I will currently just add it in as the only method is embedding it in the HTML as the link describes.

**Comment by xray7224** [comment]
I have added a commit on this, I'm not sure if it's sufficient yet. I'm also not sure i like all the discovery being on that level of the actor (I know it is elsewhere in the document). I might prefer if it was in a "links" section or something.

**Comment by rhiaro** [comment]
Endpoint addresses as embedded JSON won't work where JS is disabled. Can we use html <link rel= as well?

**Comment by cwebber** [comment]
We agreed on how to do this at the most recent Face to Face (in San Francisco).  Closing this, future activity will be tracked in #50
