### ISSUE TITLE
spec nits

### ISSUE THREAD

**Issue by ghost** [w3c-social/activitypump#247]
In several places in the spec the examples reference an 'author'. This does not seem to be defined in any of the activitypub or activitystreams specifications. I'm assuming this was an early iteration which was later changed to 'actor' but some clarification/correction would be appreciated.

**Comment by strugee** [comment]
@zotlabs you're talking about prose, right? So fb0a2e8516d9f59e1276b2e2d5a1f9cee9da4253 doesn't fix what you're thinking of?

**Comment by strugee** [comment]
@zotlabs filed #248 to fix this.

**Comment by ghost** [comment]
That's the issue and the fix. Anybody have a link where I can see the current rev? All I have is the last published spec from May.

**Comment by cwebber** [comment]
@zotlabs Editor's Draft is here https://w3c.github.io/activitypub/

**Comment by ghost** [comment]
Thanks for that. Closing.
