### ISSUE TITLE
Are Oauth 2.0 bearer tokens required for reading a public outbox?

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#25]
Say you're curious about Sensible Sam's ramblings, and you're reading from a mobile client.  You haven't subscribed to Sam yet, and Sam hasn't subscribed to you.  You have no private messages from Sensible Sam... you just want to see his latest public messages.  Is an OAuth bearer token required?

I would think not, but we need clarification.

**Comment by elf-pavlik** [comment]
does outbox serve as *default stream* which one can pull for updates if dosn't want to get notifications pushed?

**Comment by xray7224** [comment]
I agree, this should not be the case, we need to make it very clear.
