### ISSUE TITLE
Smilodon implementation report

### ISSUE THREAD

**Issue by rowanlupton** [w3c-social/activitypump#275]
https://test.activitypub.rocks/download-report/5bxi3pp3vh5bzkkfaa65rw3lisgeutk6fahnpkuc5ccr4e5jqkwa

**Comment by cwebber** [comment]
Yay, thank you!  Take a look at the [implementation reports page](https://activitypub.rocks/implementation-report/) at the bottom especially, and double check it looks right... I added a few fields that the test suite doesn't ask (but probably should).

Thank you for your submission!  Very excited to have it included!
