### ISSUE TITLE
Update distbin.com implementation report plz

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#277]
In the last week, I have implemented the following 'features' for distbin.com. Will you update the implementation report at https://activitypub.rocks/implementation-report/ ?

* [`client:submission:discovers-url-from-profile`](https://distbin.com/activities/14020ff5-289a-49df-9fe0-f4fd93865bfe)
* [`server:security-considerations:do-not-post-to-localhost`](https://distbin.com/activities/4edc1418-fc92-476c-9b17-562b5c8ec5e6)
* [`server:security-considerations:filter-incoming-content`](https://distbin.com/activities/4edc1418-fc92-476c-9b17-562b5c8ec5e6)
* [`client:submission:recursively-add-targets`](https://distbin.com/activities/5e4f5f9b-90e5-43fc-94cd-7e2c832a81a3)
* [`client:submission:recursively-add-targets:limits-depth`](https://distbin.com/activities/5e4f5f9b-90e5-43fc-94cd-7e2c832a81a3)

**Comment by cwebber** [comment]
Done!  Thank you! :)
