### ISSUE TITLE
Don't try to dictate storage strategies for the server for bto and bcc properties

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#280]
Section 6.1 says "The server MUST remove the bto and/or bcc properties, if they exist, from the ActivityStreams object before **storage and delivery**". This is a problem because:

-   The bto/bcc properties may be used for access control on the object
-   The server may need to show bto/bcc properties to the author at a later point

Rather than specifying that these properties must be removed before storage, we should specify only **delivery**.

Additionally, a note in section B (security considerations) could be added to indicate that the bto and bcc properties should only be readable by the author. Something like:

```
B.11 bto and bcc properties

The bto and bcc properties are for private addressing of activities. Implementers
should take care to expose these properties of an activity to the author only.
```

**Comment by cwebber** [comment]
Addressed in d292ce89d30fbd54511b0cf2fa41253eea5f126a.
