### ISSUE TITLE
places.pub implementation report

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#282]
https://test.activitypub.rocks/download-report/qzvh2npz7f7aryea2aghjoherh2nzsi57jryn5h3o3qzs4yp7voq

**Comment by cwebber** [comment]
It's pulled in!  ty ty ty!

**Comment by cwebber** [comment]
BTW, as you may remember from the call, there are some items I forgot to include in the implementation report... we have enough to go to PR/Rec but would be good to capture what tags.pub and places.pub includes for the ones currently marked "missing":  https://activitypub.rocks/implementation-report/

(You can hover over the test names for descriptions)

Thanks thanks!
