### ISSUE TITLE
Document use of HTTP Signature

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#283]
There needs to be a description somewhere, like in a note, for how to use HTTP Signature with AP.

**Comment by nightpool** [comment]
https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization, I think is the document you're looking for?

**Comment by cwebber** [comment]
Yeah maybe could use more description, but that's linked to from the spec!  LMK if there are more things you think should be added to it... or let's work it out on IRC and then add to the wiki page together!

**Comment by evanp** [comment]
@nightpool that's close, but we need to also specify how to resolve a keyId into a public key. Right now I think it's:

- Fetch the object at the keyId
- Get the publicKey property (an object)
- Check that publicKey.owner == keyId
- Use publicKey.publicKeyPem as public key value

**Comment by cwebber** [comment]
Okay, the page says the first two but I suppose not the last two!

**Comment by evanp** [comment]
I think referring to WebPayments is enough. We should probably also note that you need to include that vocabulary!

**Comment by rokj** [comment]
> https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization, I think is the document you're looking for?

I think this is not enough, it should include some example howto create signature like which headers to use, howto create signature. Simple working example using bash commands would suffice.
