### ISSUE TITLE
Tutorial images mess with the layout width on mobile

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#284]
Google Pixel, Firefox Nightly built a day or two ago, portrait.

**Comment by nightpool** [comment]
![img_4845](https://user-images.githubusercontent.com/233815/33186113-b7e3de0c-d04c-11e7-925e-0bba0c403f66.PNG)

Screenshot from iPhone for reference

**Comment by cwebber** [comment]
Fixed, thanks!
