### ISSUE TITLE
Illustration contrast

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#285]
We received some feedback that the contrast on the images for the ActivityPub tutorial was too low.  I'm hesitant about changing these far from @mray's original design; I think they were very intentional about their decisions in the original graphics so that the following properties were true:

 - The colors helped convey contextual information that's useful in being able to read the images
 - The color scheme, and level of contrast, leads the characters to be somewhat racially ambiguous, which I think is a win for diversity reasons; if we try to up the contrast too much, the characters will look white, and I think that would be a loss of another kind.
 - mray also build their images based on my original ascii art; I originally designed those ascii art images in such a way that they are not *required* to understand the surrounding text, they mearly convey some additional useful information.

Nonetheless, I understand where the accessibilty concern comes from.  In the latest Editor's Draft, I've adjusted the issues to both a) try to improve contrast and b) try to preserve mray's original design.  This is the best I was able to do it... see here:

 - [original](https://www.w3.org/TR/activitypub/illustration/tutorial-1.png)
 - [adjusted](https://w3c.github.io/activitypub/illustration/tutorial-1.png)

If folks are fine with this, I'd be happy moving these to be the official images used, though I think we'd need process help to get the images changed at this point.

**Comment by ghost** [comment]
I'm fine with that. I just recommend changing the contrast consistently.

**Comment by cwebber** [comment]
Looking at the images that are on the server now, I think this was done?
