### ISSUE TITLE
Implementation report: PeerTube

### ISSUE THREAD

**Issue by Chocobozzz** [w3c-social/activitypump#287]
Hi :)

https://test.activitypub.rocks/download-report/oul5rjmtat2gsw7ylxoavjawooh6lmfskxkatc6vpeg2htar33qa

**Comment by Chocobozzz** [comment]
Did not understand the `notes` field was to explain what is the project.

Could you replace it by: 

```
Federated (ActivityPub) video streaming platform using P2P (BitTorrent)
directly in the web browser with [WebTorrent](https://github.com/feross/webtorrent). 

Under heavy development, implementation might be improved in the future :)
```

?

Thanks

**Comment by cwebber** [comment]
Yikes, sorry this took so long!  But it's pushed up now! \o/

Thank you for your report! :D
