### ISSUE TITLE
BaseURI needed for `source` property

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#288]
The [ActivtyStream specification](https://www.w3.org/TR/activitystreams-vocabulary/#properties) lists `"https://www.w3.org/ns/activitystreams#"` as the Base URI for its listed properties. However, the [ActivityPub spec](https://www.w3.org/TR/activitypub/#source-property) does not specify if the same should be used for the `source` property.

I believe this is important for JSON-LD implementors.

**Comment by cwebber** [comment]
Since ActivityPub uses ActivityStreams as its data model, I think this is implicitly the case?  Am I wrong?

**Comment by cjslep** [comment]
Now that I've been pretty exposed to ActivityPub, it does seem obviously so. But when trying to approach the document with no background knowledge and no intention of implementing JSON-LD, it was not entirely clear to me.

**Comment by evanp** [comment]
I documented the fact that all AP properties are now included in the AS2 namespace, so there's no need for a namespace prefix.

https://www.w3.org/wiki/ActivityPub/Primer/Namespace

I don't think this issue rises to the level of an error that should be documented in the Errata, so I believe this should be closed.

**Comment by aschrijver** [comment]
Maybe https://github.com/w3c/activitypub/blob/gh-pages/activitypub-context.jsonld should be removed from this repo. I was confused before by not finding `source` in that. Everything else in that AP json-ld file is contained in https://github.com/w3c/activitystreams/blob/master/ns/activitystreams.jsonld including `source`.
