### ISSUE TITLE
Clarify whether "Actor Objects" properties are Functional

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#290]
The additional properties added to the ActivityStream types in the [Actor Objects](https://www.w3.org/TR/activitypub/#actor-objects) section does not explicitly mark any of them as functional. There is also no indication whether this is intentional.

The default guidance from the [ActivityStreams properties](https://www.w3.org/TR/activitystreams-vocabulary/#properties) section is:

> Properties marked as being "Functional" can have only one value. Items not marked as "Functional" can have multiple values.

This affects the following properties:

- inbox
- outbox
- following
- followers
- liked
- streams
- preferredUsername
- endpoints
- proxyUrl
- oauthAuthorizationEndpoint
- oauthTokenEndpoint
- provideClientKey
- signClientKey
- sharedInbox

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/clarify-whether-actor-objects-properties-are-functional/223

**Comment by gobengo** [comment]
I interpret any property not explicitly labeled functional as not being functional

**Comment by evanp** [comment]
We reviewed this ticket. I've updated the Primer on the W3C wiki to cover best practices for publishers and consumers to deal with array values in these properties.

https://www.w3.org/wiki/ActivityPub/Primer/Cardinality_of_properties

With that documentation, I think this issue is closed.

**Comment by snarfed** [comment]
+1, thanks for this:

> A guideline for implementers:  
> - Publishers should not include array values for these properties, since there is no way for a consumer to decide which value to choose.
> - Consumers should be able to process a property with an array value, and should choose an array element to process, or process all. Note that this is poorly-defined behaviour!

Notably, AP logic and behavior depends on some of these values in nontrivial ways, eg `inbox` and especially `sharedInbox`. We could maybe infer reasonable behavior for some, eg deliver to all inboxes as @gobengo mentioned verbally, but multiple `sharedInbox` values is less clear.

**Comment by melvincarvalho** [comment]
> Publishers should not include array values for these properties

@evanp Could you clarify what is meant by "these properties"?  Which properties specifically?

**Comment by snarfed** [comment]
@melvincarvalho I expect he meant all of the Actor properties mentioned in the original issue description ^.
