### ISSUE TITLE
7.1: More guidance on `deduplication` needed

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#292]
Section 7.1 of the [ActivityPub](https://www.w3.org/TR/activitypub/#delivery) specification states:

> Servers MUST de-duplicate the final recipient list.

With no additional information.

Therefore, different implementations tasked with deduplicating the following for delivery (I am using `actor` IDs in lieu of their respective `inbox` IDs for clarity):

```
{
  "to": [ "https://example.com/cj", "https://example.com/sally", "https://example.com/club" ],
  "bto": [ "https://example.com/cj", "https://example.com/bob" ],
  "cc": [ "https://example.com/astrid", "https://example.com/bob" ],
  "bcc": [ "https://example.com/sally", "https://example.com/astrid", "https://example.com/group" ],
  "audience": [ "https://example.com/club", "https://example.com/group" ],
}
```

Could wind up sending with various combinations depending on how de-duping is done:

- To / BTo over CC / BCC
- To / CC over BTo / BCC
- Audience over all others
```
{
  "to": [ "https://example.com/cj", "https://example.com/sally" ],
  "bto": [ "https://example.com/bob" ],
  "cc": [ "https://example.com/astrid" ],
  "bcc": [],
  "audience": [ "https://example.com/club", "https://example.com/group" ],
}
```

or

- To / BTo over CC / BCC
- BTo / BCC over To / CC
- Audience least important
```
{
  "to": [ "https://example.com/sally", "https://example.com/club" ],
  "bto": [ "https://example.com/cj", "https://example.com/bob" ],
  "cc": [],
  "bcc": [ "https://example.com/astrid", "https://example.com/group" ],
  "audience": [],
}
```

or

- Randomly pick one
```
{
  "to": [ "https://example.com/cj", "https://example.com/club" ],
  "bto": [],
  "cc": [ "https://example.com/bob" ],
  "bcc": [ "https://example.com/sally", "https://example.com/astrid", "https://example.com/group" ],
  "audience": [],
}
```

Each of these would trigger different behavior in the fedweb.

**Comment by nightpool** [comment]
the "final recipient list" list, from context, is understood to mean the list of people you *deliver* the activity too. The activity itself is never modified. it's just saying you shouldn't HTTP POST the same activity to the same user multiple times.

**Comment by nightpool** [comment]
here's a more "algorithmic" description of what it's trying to say, if it helps you:

 - receive activity A for delivery
 - create a list called the "recipients list" by concatenating the values of `to`, `cc`, `bto`, `bcc`, and `audience` from activity A. 
 - for each target in the recipients list, look up it's JSON-LD representation: if it's a Collection or OrderedCollection, remove it and add each of it's members to the recipient list after looking up *their* JSON-LD representation
 - (optionally, do the previous step multiple times)
 - if an actor appears multiple times in the recipients list, remove all but one. if the `actor` of activity A exists in the recipient list, remove it. 
 - for each target in the recipients list, HTTP Post activity A to the URL specified by its `inbox` property

**Comment by cjslep** [comment]
Ah I see -- this makes much more sense now. Thank you for the clarification!

Also, I noticed in the [Client-to-server part](https://www.w3.org/TR/activitypub/#remove-bto-bcc-before-delivery) of the spec it does clarify to remove the bto/bcc from the ActivityStream object before delivery. But that is easy to do in addition to the rough algorithm you outline.
