### ISSUE TITLE
Clarify whether "type" is a required property

### ISSUE THREAD

**Issue by sebilasse** [w3c-social/activitypump#293]
When I wrote [these JSON schemas for ActivityPub](https://github.com/redaktor/ActivityPubSchema) it was not entirely clear if `type` is a "required property" or a "property where implementors should provide a fallback" – several examples in the Activity Vocabulary do not have a `type` property.

The spec. says
> All objects have the following properties: `[...] type`

**Comment by nightpool** [comment]
4.1. Object, from the Activity Streams 2.0 spec, says:

> All properties are optional (including the id and type).

But the ActivityPub spec puts a further restriction on this, saying:

>All objects have the following properties:
>
>id
>>The object's unique global identifier (unless the object is transient, in which case the id MAY be omitted)

>type
>>The type of the object.

**Comment by nightpool** [comment]
Therefore, we can be given to understand this as an additional restriction the AP spec imposes on top of the AS2 spec, such that not every valid ActivityStreams object is a valid ActivityPub object.

**Comment by gobengo** [comment]
Yeah, @cwebber do you really mean to do that? Would you be willing to add the same language to ActivityPub?

> All properties are optional (including the id and type)

(we talked in socialwg several times about how it was a bit weird that `{}` is a valid AS2 document. And it is. And it's also kind of awesome. You can at least try to interpret any JSON object as AS2. great)

**Comment by cwebber** [comment]
It's kind of awesome I guess-ish?  It's cool that it's theoretically something you can pass across the system, but I really want to give "meaning" to the objects being passed around the network.  In my applications I dispatch on behavior based on the type.  Not having a type provided makes figuring out how to dispatch... strange.

As for id being "required except when transient", I think this is in a sense handing out "sane advice", because of course if you want something transient you either want some urn or a fragment id or a blank node, but if you want something to be definitely retrievable you want a retrievable uri.

So my vote would be: leave it as is.

**Comment by aschrijver** [comment]
What I am confused about is the example in [ActivityStreams par 4.4](https://www.w3.org/TR/activitystreams-core/#activity) where figure 17 ostensibly shows an extended `Activity` type with overlap, that is both a `Like` and a `https://schema.org/LikeAction` and the `type` is a json array reflecting that.

Yet in the example there is no overlap. None of the `LikeAction` fields are present. Also I would expect the `@context` to also have reference to `LikeAction`.

(Maybe I should create an issue in AS repo for this?)

**Comment by nightpool** [comment]
@aschrijver 

> None of the LikeAction fields are present

does LikeAction have any required fields? i would expect it doesn't.

> Also I would expect the @context to also have reference to LikeAction

because `https://schema.org/LikeAction` is a full URI, there's no need to use `@context`, which only specifies how to map short-hand properties to full URIs

**Comment by aschrijver** [comment]
Thanks for clarification @nightpool No, it does not have required fields, but example would be clearer if some field was present, I think.

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/clarify-whether-type-is-a-required-property/221

**Comment by evanp** [comment]
Based on this conversation, and our read of the document, it looks like AP adds additional requirements on top of AS2's somewhat permissive structure.

It looks like `id` MAY be omitted if the object is transient, but there is no such provision for `type`, so we think this is required.

I've documented this on the AP Primer here:

https://www.w3.org/wiki/ActivityPub/Primer/Required_properties

**Comment by ap-socialhub** [comment]
This issue has been mentioned on **SocialHub**. There might be relevant details there:

https://socialhub.activitypub.rocks/t/should-we-fork-as-ap-specs-to-codeberg-create-vnext-drafts/3022/23
