### ISSUE TITLE
Delivery to 'followers' clarification

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#295]
It's a little unclear from the spec what the behavior should be for delivery to an actor's `followers` collection. Using this `Note` created by Mallory for Erik's followers as an example (from the spec):

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "id": "https://example.net/~mallory/87374",
  "actor": "https://example.net/~mallory",
  "object": {
    "id": "https://example.com/~mallory/note/72",
    "type": "Note",
    "attributedTo": "https://example.net/~mallory",
    "content": "This is a note",
    "published": "2015-02-10T15:04:55Z",
    "to": ["https://example.org/~john/"],
    "cc": ["https://example.com/~erik/followers",
           "https://www.w3.org/ns/activitystreams#Public"]
  },
  "published": "2015-02-10T15:04:55Z",
  "to": ["https://example.org/~john/"],
  "cc": ["https://example.com/~erik/followers",
         "https://www.w3.org/ns/activitystreams#Public"]
}
```

> An activity is delivered to its targets (which are actors) by first looking up the targets' inboxes and then posting the activity to those inboxes. Targets for delivery are determined by checking the ActivityStreams audience targeting; namely, the to, bto, cc, bcc, and audience fields of the activity.

> The inbox is determined by first retrieving the target actor's JSON-LD representation and then looking up the inbox property.

If the followers' IRI is in the `to`, `bto`, `cc`, `bcc`, or `audience` fields, then this will result in implementations calling the `cc` IRIs with GET requests. In the example above, Mallory's server will call Eric's server to get the list of followers he has.

> The followers collection MUST be either an OrderedCollection or a Collection and MAY be filtered on privileges of an authenticated user or as appropriate when no authentication is given.

So this GET request could be blocked entirely, or successfully list every single follower. If it successfully lists every single follower, then the sending server will try to POST this to all of their `inbox`es as part of the delivery algorithm. So if I am following Erik, I will have Mallory's `Create` `Note` posted to my `inbox` if my implementation made the collection world-readable.

However, if an implementation keeps Erik's follower collection secret for everyone except Erik, then only John will receive the message. Neither Erik (who was not targeted) nor his followers (who are hidden). So how would this be resolved to get to Erik's followers, or would it be undeliverable?

As far as I can tell, the delivery section is explicit that only *actors* can be *targets* of delivery, and *actors* are defined to have `inbox` and `outbox` for handling POST/GET HTTP requests. The `followers` collection is not an *actor* so it does not make sense to call that endpoint with anything other than an HTTP GET to read it, and the spec doesn't suggest anything other than GETting it as a list. The only exception to this seems to be `sharedInbox` which explicitly says it is an optional endpoint for delivery. Furthermore, in this undeliverable case, if I (Erik's follower) went to look at Mallory's `outbox`, Mallory's server has no way of knowing I am in Erik's `followers` and to whitelist showing me this activity.

**Comment by cjslep** [comment]
Note this is still a point I have not yet found a resolution for. Are collection endpoints entirely supposed to be delivered *only* by inbox forwarding? My original concern still stands, just imagine the example above uses ~~`https://foo.bar/~erik/followers`.~~ `inReplyTo: "https://example.com/~john/note/72"`.

Additionally, putting more thought into this, inbox forwarding means I can do this to get another victim site `foo.bar` to spam *all of the follower collections they have* if enumerable:

```
{
  type: "Create",
  object: {
    type: "Note",
    content: "Please follow me!",
  }
  inReplyTo: "foo.bar/123",
  to: "foo.bar/addison",
  cc: [
    "foo.bar/popularPerson1/followers",
    "foo.bar/popularPerson2/followers",
    ....
  ]
}
```

Inbox forwarding says:

- [x] This is the first time the server has seen this Activity.
- [x] The values of to, cc, and/or audience contain a Collection owned by the server.
- [x] The values of inReplyTo, object, target and/or tag are objects owned by the server.

And voila, I get my spammy message delivered to anyone following a user on victim site `foo.bar`.

**Comment by cjslep** [comment]
I've been informed via IRC that Hubzilla is resistant to this kind of spam/DDOS attack by introducing additional non-standard constraints about to whom inbox forwarding will occur. I'm not sure if Mastodon or Pleroma is vulnerable, and I am not the type to go out and test for it in the wild.

I would like to standardize on behavior, otherwise each implementation doing their own thing means developers will have no idea what kind of messages will actually be delivered to which collections. This would effectively fragment parts of the fediverse.

**Comment by nightpool** [comment]
I've already told you on irc that mastodon is not vulnerable

**Comment by cjslep** [comment]
I wasn't in the channel when you responded. Thanks for clarifying here!

**Comment by nightpool** [comment]
Anyway, the spec specifically mentions this:

```
The server MAY filter its delivery targets according to implementation-specific rules
(for example, spam filtering).
```

so i'm not too worried on what's going on. The specific logic on mastodon is that it will only forward to a users followers if your message is in reply to a post made by that user.

**Comment by cjslep** [comment]
Gotcha, thanks. That was exactly what I was looking for, I'll close this issue.
