### ISSUE TITLE
Client-To-Server Interactions: Accept/Reject

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#296]
Section *7.5 Server to Server Interactions: Follow Activity* says:

> The Accept or Reject MAY be generated automatically, or MAY be the result of user input (possibly after some delay in which the user reviews).

However, there is no corresponding guidance anywhere in *6. Client to Server Interactions* for both `Accept` and `Reject` Activities, so organizationally it is non-intuitive to have to go to section 7.5 to learn that:

> Servers MAY choose to not explicitly send a Reject in response to a Follow, though implementors ought to be aware that the server sending the request could be left in an intermediate state.

And since there is no explicit guidance on the *Client to Server* section, a spec-compliant implementation could also not deliver `Accepts` as well. (Since the *MUST* in *6.11 Delivery* seems to be violated in quite a few places).

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/client-to-server-interactions-accept-reject/218

**Comment by evanp** [comment]
This is a useful note. I've added further documentation on the Follow, Accept, and Reject activities to the Primer to make it clearer what checks should be done, ideally, as well as what side effects the activities have.

https://www.w3.org/wiki/ActivityPub/Primer/Follow_activity
https://www.w3.org/wiki/ActivityPub/Primer/Accept_activity
https://www.w3.org/wiki/ActivityPub/Primer/Reject_activity

Given this additional documentation, I'm going to set this issue to pending.

**Comment by evanp** [comment]
This has been pending for 1 month. I'm going to close this ticket.
