### ISSUE TITLE
Another 6.11 Delivery Ambiguity

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#301]
When Sam posts their `Create` activity through a client to a Server:

```
{
  "type": "Create",
  "object": [
    {
      "type": "Note",
      "content": "Bland information",
      "to": "foo.com/foo",
    },
    {
      "type": "Note",
      "content": "Super sensitive discussion",
      "to": "bar.com/bar",
    }
  ]
}
```

Is the expectation that both `foo.com` and `bar.com` would then receive the entirety of the above message, allowing a rogue operator of `foo.com` to be able to capture the super sensitive discussion?

**Comment by cwebber** [comment]
I think this is really pretty much the same issue as #302, just a particular aspect of it.  Let's consolidate this conversation there.
