### ISSUE TITLE
Client Create: Order of copying recipients ambiguity

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#302]
Due to the glorious flexibility that is ActivityStreams, an Activity could have multiple `object` properties (since it is [not marked as functional](https://www.w3.org/TR/activitystreams-vocabulary/#properties)).

The spec says:

> A server SHOULD copy any recipients of the Create activity to its object upon initial distribution, and likewise with copying recipients from the object to the wrapping Create activity.

This very lightly implies, but really does not specify, the order of this copying. Which is important. If implementors do not pick up on this subtlety, then this results in different behavior when given:

```
{
  "type": "Create",
  "to": "example.com/baz",
  "object": [
    {
      "type": "Note",
      "to": "example.com/foo",
    },
    {
      "type": "Note",
      "to": "example.com/bar",
    }
  ]
}
```

Which of the following results is the correct one? If there is no ambiguity resolution here, then within the federation Clients and Servers may not be able to federate correctly.

A) Activity to objects, then objects to the activity.

```
{
  "type": "Create",
  "to": [
    "example.com/baz",
    "example.com/foo",
    "example.com/bar"
  ],
  "object": [
    {
      "type": "Note",
      "to": [
        "example.com/foo",
        "example.com/baz",
      ],
    },
    {
      "type": "Note",
      "to": [
        "example.com/bar",
        "example.com/baz",
      ]
    }
  ]
}
```

B) Objects to activity, then activity to objects.

```
{
  "type": "Create",
  "to": [
    "example.com/baz",
    "example.com/foo",
    "example.com/bar"
  ],
  "object": [
    {
      "type": "Note",
      "to": [
         "example.com/baz",
         "example.com/foo",
         "example.com/bar"
       ],
    },
    {
      "type": "Note",
      "to": [
         "example.com/baz",
         "example.com/bar",
         "example.com/foo"
      ],
    }
  ]
}
```

It seems like A is the logical choice, to me. However, this is then exposed to the issue I outline in #301

**Comment by cwebber** [comment]
Thanks for raising this.  I agree that most people are not thinking about or are even aware that multiple objects are possible for the `object` field (I'm not sure if, in practice, anyone is actually using multiple objects).  If I'm wrong about this, I would be interested to kn

> Which of the following results is the correct one? If there is no ambiguity resolution here, then within the federation Clients and Servers may not be able to federate correctly.

We should clarify terminology (and I think this is what you meant); this is a client-to-server issue (it's before distribution) but "within the federation" I think you mean that we're hoping that multiple clients should be able to speak to different servers over the client-to-server api and if they behave differently, that's a problem.

I'm not sure which behavior is right... looking at Pubstrate's code (which does not expect multiple objects...!) I would think that if I updated without thinking about it that I would do B.  I'm not sure if A is more logical, because in receiving the Create, all recipients are informed of both Notes?

**Comment by cwebber** [comment]
You raised a particular potential security issue in #301... I think my answer would be that if you're putting two objects in the same Create, you should expect that you're delivering them together (if you even expect the ability to deliver two objects in the same Create at all... which is technically allowed, but again is something I think no servers currently support!)

**Comment by nightpool** [comment]
I don't think there's a privacy issue here. Addressing/delivery in Activitypub is defined with respect to *activities*, not objects. If i'm reading correctly, the use of the to/cc properties on Object is basically provided as a convenient shorthand for c2s clients only.

**Comment by nightpool** [comment]
I agree that A is more intuitive, but when you read the whole paragraph in context:

```
A mismatch between addressing of the Create activity and its object is likely to
lead to confusion. As such, a server SHOULD copy any recipients of the Create
activity to its object upon initial distribution, and likewise with copying recipients
from the object to the wrapping Create activity. Note that it is acceptable for the
object's addressing to be changed later without changing the Create's addressing
(for example via an Update activity).
```

It's clear that B is implied.

**Comment by cjslep** [comment]
ACK @cwebber, I didn't realize no other implementation supports multiple `object` in an Activity. Is that non-conformant to the ActivityStream spec, or am I just overreacting?

@nightpool I agree that activities are central to ActivityPub and not objects. But could you explain why there is not a privacy issue here?

My reasoning is that the client-to-server convenience easily misleads expectations. For example, if a client sends
```
{
  "type": "Create",
  "object": [
    {
      "type": "Note",
      "content": "Bland information",
      "to": "foo.com/foo",
      "to": "bar.com/bar",
    },
    {
      "type": "Note",
      "content": "Super sensitive direct message",
      "to": "bar.com/bar",
    }
  ]
}
```

The _intent_ of the client to me reads "Send 'Bland information' to `foo` and `bar`, and the sensitive information only to `bar`". But in practice it will be sent to both. The shorthand is deceptive in this regard. Its convenience may mislead other developers. I can't force them all to understand that ActivityPub is Activity-centric. Therefore, to me, this breach of expectation could manifest as a privacy issue in the misled-dev's eyes.

In practice right now, no one is leveraging multiple `object` (thanks cwebber for this info). However, the library I am currently working on treats `object` like any other functional field (like `orderedItems`) so I wanted to be proactive in highlighting this. Since my lib tries to abstract away as much of the spec into a neat but flexible black box, I will have to be proactive in passing along these kinds of gotchas to the library's users as I cannot expect them to be this intricately familiar with the spec.

**Comment by nightpool** [comment]
Yeah, I can see that being an issue. I don't know what the best solution here is—i think we need more implementation experience with the c2s spec before we're able to resolve this conclusively one way or another.

best case i guess is for the server doing the copying to error out if it detects a mismatch like this

**Comment by evanp** [comment]
This topic has been open for several years. I think the general practice has settled down to using only one `object` in an activity, even if it's technically allowed in the spec.

First, I added guidance on using multiple `object` values here:

https://www.w3.org/wiki/Activity_Streams/Primer/Cardinality_of_properties#object

Second, I added a note to the AP primer that says the best ways to manage this situation for both clients and servers:

https://www.w3.org/wiki/ActivityPub/Primer/Copying_addresses_between_Activity_and_object

**Comment by nightpool** [comment]
I think it's worth adding an informative note here that in the presence of
multiple activities, the operation described should be considered a union
set operation across all of the relevant recipients, since that seems to
match the intent of the spec most closely.

**Comment by evanp** [comment]
@nightpool sorry, that doesn't make sense to me. Did you look at the primer pages?
