### ISSUE TITLE
7.1 Delivery to Collections not owned by the server

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#306]
I think I have found the root cause of so much of my confusion around the federating delivery model. It stems from [this section](https://www.w3.org/TR/activitypub/#delivery):

> The inbox is determined by first retrieving the target actor's JSON-LD representation and then looking up the inbox property. If a recipient is a Collection or OrderedCollection, then the server MUST dereference the collection (with the user's credentials) and discover inboxes for each item in the collection. 

Given the following partial activity being sent by the user at `example.com/dakota` and the server at `example.com` is processing it for delivery:

```
{
  "type": "Create",
  "to": [
    "example.com/avery",
    "example.com/avery/followers",
    "foo.net/jordan",
    "foo.net/jordan/followers",
    "bar.social/elliot",
    "bar.social/elliot/followers"
  ]
}
```

In my mind, the above paragraph reads that the server at `example.com` MUST dereference the following collections with the user's credentials for inbox discovery:

1. `example.com/avery/followers`
2. `foo.net/jordan/followers`
3. `bar.social/elliot/followers`

(The `jordan` and `elliot` users will also be dereferenced using credentials, so questions about credential-passing apply to them as well. For now though, I want to focus on the behaviors of `Collection`s)

The first one makes sense and is straightforward for the `example.com` server. The other two raise the following questions:

* What is the exact method of passing `example.com/dakota`s credentials to `foo.net` and `bar.social` in order to determine whether these ActivityPub references are actors or collections?
* What is the expected behavior for when a server cannot even determine if `foo.net/jordan/followers` or `bar.social/elliot/followers` are `Collection`/`OrderedCollection` (ie it gets a 403 forbidden response)?

Basically I am considering 3 options:

1. Try to dereference all collections, magically passing credentials to servers `foo.net` and `bar.social` (but I'm not sure how this is done). Interpretation: "Follow the letter of the spec"
2. Try to dereference all collections, without passing credentials to the other servers. Interpretation: "I can't pass credentials so I am not spec compliant, but I will still do as much as I can"
3. Avoid collections entirely (assumes all followers/following may be private) and only deliver to actors/sharedInbox. Interpretation: "Since I can't pass credentials, make a clean break from the spec here instead of attempting to do it incorrectly"

Only option 1 adheres to the letter of the spec, but unless there's a way to reliably pass credentials that I am missing then I think implementors will move on to 2 or 3 for practicality. I think options 2 and 3 adhere to different interpretations of how-to-diverge-if-unable-to-implement-to-the-letter, but unless one of the two is blessed then having both of these in practice could result in a broken federation. Note that section 7.1.2 does not resolve this, because of the ambiguity here:

> When Activities are received in the inbox, the server needs to forward these to recipients that the origin was unable to deliver them to.

Each server is free to impose on its peer how *it guesses the other* was unable to deliver to collections. Here's how:

Let `foo.net` follow the 2nd philosophy above. It will attempt to dereference all collections without passing credentials to the other servers, and will deliver to those collection's members. Upon receiving an item in a `foo.net` inbox, it executes 7.1.2 and won't deliver to users in `foo.net/<user>/follower` because it is publicly accessible without credentials. Under the 7.1.2 guidance it assumes other servers are like it.

Let `bar.social` follow the 3rd philosophy. It will not attempt to dereference any collections owned by other servers (or throw them away entirely if it finds itself with one). Upon receiving an item in a `bar.social` inbox, it executes 7.1.2 and will deliver to all of the collections it owns. Under the 7.1.2 guidance it assumes other servers are like it.

Since neither server can actually tell what the other server actually tried to resolve, activities from `bar.social` to `foo.net` will never be delivered to actors in collections owned by `foo.net`. And in the case `bar.social` collections are publicly dereferenceable, then activities from `foo.net` will be double-delivered to actors in collections owned by `bar.social`.

To summarize:
1. What is the way to pass credentials to another server when attempting to dereference actors/`Collection` (since the originating server may not know if an IRI is one or the other)?
2. If there is no answer to the above, then what *is* the expected behavior (Option 2 or 3)?

**Comment by nightpool** [comment]
>Each server is free to impose on its peer how it guesses the other was unable to deliver to collections. Here's how:

[No, because 7.1.2 specifies exactly how to do forwarding delivery.](https://www.w3.org/TR/activitypub/#inbox-forwarding) The section quoted was just intro text.

**Comment by nightpool** [comment]
>What is the way to pass credentials to another server when attempting to dereference actors/Collection (since the originating server may not know if an IRI is one or the other)?

This is not answered in the spec because it was still in flux and there wasn't enough implementation experience at the time, so it's covered on this page instead: https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization

The "Authentication and Authorization" section of ActivityPub links to this document:

>ActivityPub uses authentication for two purposes; first, to authenticate clients to servers, and secondly in federated implementations to authenticate servers to each other.
>
>Unfortunately at the time of standardization, there are no strongly agreed upon mechanisms for authentication. Some possible directions for authentication are laid out in the [Social Web Community Group Authentication and Authorization best practices report.](https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization)

**Comment by cjslep** [comment]
Gotcha, thanks, this is very helpful.

However, I still have a lingering concern:

If `example.com` successfully dereferences a collection of `foo.net` and sends an Activity to those members, wouldn't it be possible for `foo.net` to then follow 7.1.2 and still double-deliver to that same collection?

* First time seeing the Activity
* Collection is owned by `foo.net`
* (Assume its a reply)

Thus, `foo.net` sends to that collection, and so does `example.com` since its publicly dereferenceable?

**Comment by nightpool** [comment]
yes but receiving servers are required to deduplicate so ¯\\\_(ツ)_/¯

**Comment by cjslep** [comment]
Alright, good to know that I'm not spamming / getting spammed due to impl bugs, and is expected behavior. I'll close this issue.
