### ISSUE TITLE
microblog.pub implementation report

### ISSUE THREAD

**Issue by tsileo** [w3c-social/activitypump#308]
Hey!
Here is  the link for my implementation report: https://test.activitypub.rocks/download-report/ltgl2tpl2buckagsmzzauitz4xrionhibvfpapdg2vp3owbfu4uq

Let me know if you need any information.

Thanks!

**Comment by cwebber** [comment]
Pushed up, thanks!  As you can see on https://activitypub.rocks/implementation-report/ there were a couple of server errors for a couple of items, which were probably errors on my end when writing the tests... if you want to check them and let me know if you can verify that the behavior is correct, I'll update those.  Thanks for the report, sorry it took so long!
