### ISSUE TITLE
test suite down

### ISSUE THREAD

**Issue by ppwfx** [w3c-social/activitypump#311]
Hey, 

test.activitypub.rocks is down..

**Comment by fenwick67** [comment]
It's either down again or still down

**Comment by cwebber** [comment]
Back up again.  Thanks for letting me know.

**Comment by elazar** [comment]
Appears to be down again? I'm getting a 502.

**Comment by gobengo** [comment]
@cwebber Is the test suite powered by? https://gitlab.com/dustyweb/activitypub.rocks

If so, will you or someone else who knows guix make a Dockerfile in there to build and run it? If so, I can host a mirror/backup.

**Comment by ebuckley** [comment]
It appears that the test suite is down again

edit: and it's back again, thanks!

**Comment by pauljohncleary** [comment]
502 again

**Comment by cwebber** [comment]
Argh.  Brought it back up.  If it fails again I'll try writing a script to auto-restore it when it falls over.

@gobengo it's based on https://gitlab.com/dustyweb/pubstrate but I *could* make a dockerfile of it.  The next time it fails, I'll give that a whirl.

**Comment by SignpostMarv** [comment]
let's encrypt cert has failed to renew, rendering the site unavailable.

**Comment by mayel** [comment]
The test suite is down. +1 for a dockerfile!
Thanks :)

**Comment by mpfaff** [comment]
Still down...

**Comment by SignpostMarv** [comment]
@mpfaff (and anyone else that comes looking) see: https://github.com/w3c/activitypub/issues/330#issuecomment-556324396
