### ISSUE TITLE
jsonld schema clarification

### ISSUE THREAD

**Issue by ppwfx** [w3c-social/activitypump#313]
Hey,

me and @cjslep were thinking about generating the ActivityPub golang types from the .jsonld specification. 
As far as I understand jsonld provides type definitions for domain specific entities. Unfortunately I can't figure out how jsonld is doing it in the case of AcitivityPub/Streams.

I would have expected, something like this
[http://schema.org/Person.jsonld](http://schema.org/Person.jsonld)

But the only jsonld definition I was able to find so far is the following (which is only associating and assigning types to identifiers)
[https://www.w3.org/ns/activitystreams.jsonld](https://www.w3.org/ns/activitystreams.jsonld)

How is the latter document expected to be interpreted?

Are there any jsonld specifications like the one provided by schema.org?

Cheers

**Comment by gobengo** [comment]
> generating the ActivityPub types from the .jsonld specification

Can you elaborate on that? 'generating ... the types' how? in what format? Like generating code? documentation?

I'm definitely curious as I have been all up in this the last couple days writing this program that scrapes the AS2 vocabulary html to generate something kinda like that `.jsonld` file, but with all the rest of the information too like description, properties, parent class, etc. My program's output is also JSON-LD, but includes more data! (maybe some day that one can point to this one as a `link[rel=alternate]` or `rdfs:seeAlso`)

Scraper:
https://github.com/gobengo/activitystreams2-spec-scraped

Sample Output:
https://github.com/gobengo/activitystreams2-spec-scraped/blob/master/data/activitystreams-vocabulary/1528589057.json

Is this useful to you?

**Comment by ppwfx** [comment]
> Can you elaborate on that? 'generating ... the types' how? in what format? Like generating code? documentation?

Sorry, golang types.

> Is this useful to you?

That's what I was looking for! How complete is it?

**Comment by gobengo** [comment]
It's really complete as of this morning! Has all the terms I think:
Activity Types, Actor Types, Object and Link Types, and Properties.

I only scrape The activitystreams-vocabulary page.
So I just noticed I don't have the terms from the ativitystreams-core, e.g.
Activity, Collection, Actor, Object, Link (the base classes). But I will
add them over next couple days.

**Comment by ppwfx** [comment]
Sorry if it's annoying, but I had a closer look and it raised a couple of questions

Where is `activityTypes` defined? 
When you use `type` and `id`, shouldn't it be `@type` and `@id`?
Where is the `href` property within `subClassOf` definend ?

There is a little typo `"subClassOf": "rdfs:subClassof",`  should be `rdfs:subClassof`, same for `subPropertyof` :P

IMHO Another little suggestion, it would be nice if you wouldn't use type associations, as it makes it hard to figure out where the properties are actually defined, especially if you rename them, as in the case of `notes`.

I really like the way http://schema.org/Person.jsonld did it as it's really coherent, maybe it's something you can orient one :)

**Comment by gobengo** [comment]
> Where is activityTypes defined?

Do you mean like in the JSON-LD context? It's not. The value is effectively a blank node. I'll reorganize the output to be more semantically justifiable for 0.1.0.

> When you use type and id, shouldn't it be @type and @id?

The [ActivityStreams 2.0 context](https://www.w3.org/ns/activitystreams.jsonld) maps 'type -> @type' and 'id -> @id'.

> Where is the href property within subClassOf definend ?

It's 'as:href' from the [ActivityStreams 2.0 context](https://www.w3.org/ns/activitystreams.jsonld)

> There is a little typo "subClassOf": "rdfs:subClassof", should be rdfs:subClassof, same for subPropertyof :P

Thank you for catching this. I have [fixed](https://github.com/gobengo/activitystreams2-spec-scraped/commit/bc9b9324c65a4f0e3582605d1fa9d67222c15562) it in 0.7.1

> IMHO Another little suggestion, it would be nice if you wouldn't use type associations, as it makes it hard to figure out where the properties are actually defined, especially if you rename them, as in the case of notes.

https://github.com/gobengo/activitystreams2-spec-scraped/issues/7

I will publish something like that. One of the design goals with AS2 (and why AS2 itself uses many term maps) was to make AS2 data approachable and eays to use by web developers who don't know about JSON-LD and, frankly, don't want to.

From "Serialization":
> This specification describes a JSON-based [RFC7159] serialization syntax for the Activity Vocabulary that conforms to a subset of [JSON-LD] syntax constraints but does not require JSON-LD processing.

When dealing with AS2 data in JavaScript, any time a property name has a colon (`:`) in it, it requires extra bracket syntax to deal with and can be frustrating to devs used to simple dot notation. I'm trying to carry that design goal forward. It's sort of expected that anyone savvy enough to know about and want LD semantics is willing to re-~compact~frame this JSON object into a shape they prefer (e.g. using [JSON-LD Processing Algorithms](https://json-ld.org/spec/latest/json-ld-api/)).

I will add a feature to make this reshaping easier from the CLI, e.g. `activitystreams-spec-scraped --compacted=<customContext>`. Watch https://github.com/gobengo/activitystreams2-spec-scraped/issues/8

> I really like the way http://schema.org/Person.jsonld did it as it's really coherent, maybe it's something you can orient one :)

Thanks for the inspiration.

**Comment by ppwfx** [comment]
alright, cool! Im watching :)

> One of the design goals with AS2 (and why AS2 itself uses many term maps) was to make AS2 data approachable and eays to use by web developers who don't know about JSON-LD and, frankly, don't want to.

Hm.. I think developers should be expected to know JSON-LD, as many services use entities from multiple definitions. Following e.g. the mastodon context for a user. I think isn't valid JSON-LD.. but it's one of the most popular implementations..

```json
"@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "sensitive": "as:sensitive",
      "movedTo": "as:movedTo",
      "Hashtag": "as:Hashtag",
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji",
      "focalPoint": {
        "@container": "@list",
        "@id": "toot:focalPoint"
      },
      "featured": "toot:featured",
      "schema": "http://schema.org#",
      "PropertyValue": "schema:PropertyValue",
      "value": "schema:value"
    }
  ],
```

**Comment by gobengo** [comment]
@21stio I made some updates based on the above. I hope it makes things more valuable to you:

* Added [core types](https://github.com/gobengo/activitystreams2-spec-scraped/blob/master/data/activitystreams-vocabulary/1528589057-compacted.json#L1101)
* Added JSON-LD types and semantics to just about everything
* Published [a version with no term mappings other than AS2, just curies](https://github.com/gobengo/activitystreams2-spec-scraped/blob/master/data/activitystreams-vocabulary/1528589057-compacted.json).

**Comment by ppwfx** [comment]
nice! I'll give it a try to generate golang types from it later on, thanks man :)

another question, what kind of encoding is this, is it some kind of xml flavour?
https://www.w3.org/2002/07/owl#

**Comment by nightpool** [comment]
why do you think Mastodon isn't valid json-ld?

(sorry for the late reply, my email was broken for a couple days and i'm still catching up)

**Comment by ppwfx** [comment]
well as I'm new to JSON-LD I'm not a 100% sure, but I'm asking myself, where the `as` in e.g. `movedTo": "as:movedTo"` comes from.. 

The first time I saw `movedTo": "as:movedTo"`, my intuition made me believe `as` would be a keyword that allows you to declare identifiers.. by now I know that's a namespace prefix and I can't find `movedTo` anywhere in the ActivityStreams context

**Comment by nightpool** [comment]
@21stio as is a compact prefix for activitystreams, it's defined in the context here:

**Comment by nightpool** [comment]
@21stio right, it's a compact namespace prefix. It's saying: define `movedTo` as `https://www.w3.org/ns/activitystreams#movedTo`

movedTo isn't anywhere in the activitystreams context because it doesn't need to be, it's fully defined by its uri. Having an RDF schema like http://schema.org/Person.jsonld is nice, because it can give documentation or extended validation, but it's not required: *any* URI is a valid JSON-LD term. the "context" is just a mapping from short-hand identifiers (like `as` or `movedTo`) to URIs.

**Comment by ppwfx** [comment]
I always thought, by defining a (json) object in the context, an association mapping is created, which assigns a new identifier (key) to something that is already declared (value).

Hm.. okay, but what's the point of adding a term to an external namespace?

**Comment by nightpool** [comment]
>I always thought, by defining a (json) object in the context, an association mapping is created, which assigns a new identifier (key) to something that is already declared (value).

That's somewhat right—the thing that's already declared is "as:movedTo". even though it's not mentioned explicitly in any context anywhere else, it's a perfectly valid way to refer to the URI https://www.w3.org/ns/activitystreams#movedTo. It's exactly the same as a definition like `"Accept": "as:Accept"` from the activitystreams context document. It's just a shortcut that allows you to use the term without explicitly referring to the namespace.

>Hm.. okay, but what's the point of adding a term to an external namespace?



Because we proposed movedTo as an as2 extension, so we put it in the as2 namespace. (this was before the current extension process, as i understand it things would be done differently in the future)

**Comment by ppwfx** [comment]
> Because we proposed movedTo as an as2 extension, so we put it in the as2 namespace. (this was before the current extension process, as i understand it things would be done differently in the future)

Ah okay, now I get it. That was the missing piece. Thanks for the extensive explanation!

**Comment by gobengo** [comment]
@nightpool Do you have a link to any definition of `as:movedTo`. If it's useful, would be good to define it in an extension that is *not* under the as URL so if others want to use it, they can do so as a community extension with base url different than as (given newer extension process). If you point me to a definition, I can start that extension.

**Comment by gobengo** [comment]
@21stio After above discussion, are there unresolved concerns about the original intent of this Issue?

**Comment by nightpool** [comment]
I sent a definition to cwebber back in November, because I don't have permission to edit the wiki page. We were in the middle of trying to formalize the new extension process though, so I think it got dropped. You can read it here: https://gist.github.com/nightpool/21fb737babb2f8714d911236e21b05e7

**Comment by gobengo** [comment]
@nightpool Thank you. Oy, the wiki is an ironically centralized place to define extensions. I'm planning on setting up a namespace for community extensions under `https://extensions.activitystreams2.com` and created https://github.com/gobengo/activitystreams2-extensions/issues/1

**Comment by ppwfx** [comment]
@gobengo no unsolved concerns
