### ISSUE TITLE
Specify public key format

### ISSUE THREAD

**Issue by aaronpk** [w3c-social/activitypump#315]
Currently, Mastodon and Pleroma are publishing public keys on profiles in different formats. I discovered this when I tried to load a Pleroma public key using PHP's built-in openssl, and it failed.

Compare:

[@Gargron](https://mastodon.social/users/Gargron.json)

```json
"publicKey": {
"id": "https://mastodon.social/users/Gargron#main-key",
"owner": "https://mastodon.social/users/Gargron",
"publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvXc4vkECU2/CeuSo1wtn\nFoim94Ne1jBMYxTZ9wm2YTdJq1oiZKif06I2fOqDzY/4q/S9uccrE9Bkajv1dnkO\nVm31QjWlhVpSKynVxEWjVBO5Ienue8gND0xvHIuXf87o61poqjEoepvsQFElA5ym\novljWGSA/jpj7ozygUZhCXtaS2W5AD5tnBQUpcO0lhItYPYTjnmzcc4y2NbJV8hz\n2s2G8qKv8fyimE23gY1XrPJg+cRF+g4PqFXujjlJ7MihD9oqtLGxbu7o1cifTn3x\nBfIdPythWu5b4cujNsB3m3awJjVmx+MHQ9SugkSIYXV0Ina77cTNS0M2PYiH1PFR\nTwIDAQAB\n-----END PUBLIC KEY-----\n"
},
```

[@0x1C3B00DA](https://edolas.world/users/0x1C3B00DA.activity+json)

```json
"publicKey": {
"id": "https://edolas.world/users/0x1C3B00DA#main-key",
"owner": "https://edolas.world/users/0x1C3B00DA",
"publicKeyPem": "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEArOZcTGQ8CQW1Z4aY8okyfaZrGndOcVr2SPAOOmU/C7pDr7mMbOnY\nlA8lUAeUvk294v3j69BBLI5El9x+KcroT99qyAxioLS0W1T60zi+2OfcHoD5apSG\nkWdXKLJkIW0FVnX67eY18TrKKvhoFi7iGtHW+C0XKTkb7DNDqg3pVJj56lDJDn3v\ndUWekKzw4PcKPB4/AR1LCnGPMhRyTsg6kjemw3S95zlw39/TNsNkHCch6332GeaJ\noUkwg1bAnVlAGNszAj8ZL/rPfvPIeHzSFOUfVkeAb4faChrhplcos0ah+b1xoZHm\nBCDxzyMxSkUAQa/q8k5Jp+qE6l6Z+02hXQIDAQAB\n-----END RSA PUBLIC KEY-----\n\n"
},
```

It would be great if the encoding format was specified so that we don't continue to have implementations use differing formats.

**Comment by cwebber** [comment]
I can't load  using Racket's crypto library either, which is also using openssl, but I think its own ASN.1 library to parse the key data.

`datum->pk-key: d2i_PUBKEY: wrong tag [asn1 encoding routines:ASN1_CHECK_TLEN:218529960]`

Insert my standard complaint about the impenetrability of ASN.1 / PEM encoded keys, and how I wish we were all using canonical s-exps instead.

**Comment by cwebber** [comment]
The mastodon key loads fine though.

**Comment by cwebber** [comment]
I wonder if there is an error in the ASN.1 encoding in however Pleroma is generating / rendering its keys?

I tried looking in the Pleroma's codebase for where the keys may be generated or rendered to PEM format but I couldn't figure out where it was.

**Comment by nightpool** [comment]
i thought we decided pleromas keys were pkcs#1, not asn?

**Comment by kaniini** [comment]
they are pkcs#1, Mastodon renders pkcs#8.  we can change the key format, but supporting both ways is probably ideal.

**Comment by kaniini** [comment]
sorry I meant x509.

**Comment by aschrijver** [comment]
I am also confused to how `publicKey` format is actually defined. Currently:

- The namespace `https://w3id.org/security/v1` redirects to a [JSON-LD schema](https://web-payments.org/contexts/security-v1.jsonld) from web-payments.org
- The website `https://w3id.org` has minimal documentation on permanent ID's and adding a PR to their site (i.e. not related to AP)
- The [web-payments spec](https://web-payments.org/vocabs/security) doesn't have a notation where `publicKey` is a json object holding other keys (nor does the JSON-LD schema define this).

So like @aaronpk  I am very much in favour of having this documented more clearly :)

**Comment by nightpool** [comment]
@aschrijver not sure what you mean.... https://web-payments.org/vocabs/security#publicKey does have an example?

**Comment by nightpool** [comment]
And the JSON-LD schema backs this up...
```json
    "publicKey": {
      "@id": "sec:publicKey",
      "@type": "@id"
    },
```

**Comment by aschrijver** [comment]
Whoa, you are right. Overlooked it in the doc. Thx! And I'll have to read the json-ld spec better for the schema thing.

**Comment by aschrijver** [comment]
There seems to be an error in the example at https://web-payments.org/vocabs/security#publicKey where the included key text at `publicKeyPem` indicates the private key, not the public key.

**Comment by tx0c** [comment]
> https://web-payments.org/vocabs/security#publicKey 

wonder was this issue addressed, this link is no longer accessible, why not include a copy example in this repo instead? not relying on another link?

**Comment by TallTed** [comment]
You might look to https://web.archive.org/web/20221218063101/https://web-payments.org/vocabs/security#publicKey

That said, note that the document there is an archive of a draft, produced by the W3C Web Payments Community Group which ["closed on 2020-12-18"](https://www.w3.org/community/webpayments/), so relying on its content may not be the best idea for current projects.

**Comment by tx0c** [comment]
> You might look to https://web.archive.org/web/20221218063101/https://web-payments.org/vocabs/security#publicKey

if the content is not reliable, where is a current reliable link of public key format #315

**Comment by TallTed** [comment]
I think [this](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html#publicKeyMultibase) is where that document evolved to ... which includes changes to the public key properties, each of which has a different format definition.

**Comment by evanp** [comment]
This is all part of the HTTP Signature profile for ActivityPub, so I'm going to defer to that document.

swicg/activitypub-http-signature#7 covers the PEM format.

https://github.com/swicg/activitypub-http-signature
