### ISSUE TITLE
Restrict ActivityStreams actor field

### ISSUE THREAD

**Issue by lanodan** [w3c-social/activitypump#316]
Currently ActivityStreams is way too much liberal for it to be understood completely by implementations, and I think we can start by putting some restrictions on the usage of the ``actor`` field.

Note:
* type in lowercase and not in code block refers to typing in languages, for example a String
* ``Type`` capitalized and in a code block refers to the ActivityStreams actor’s Type.

As far as I know, theses are the usage of the types by implementation:
* String (pleroma, mastodon)
* Array of String(s) (plume)
* Array of Objects (peertube)
  * with in the ``Type`` field: ``Person``, ``Group``

I think it should be restricted to the current usage, and I think requiring a ``Person`` in a Array of Objects would be sane.

**Comment by gobengo** [comment]
I do not agree that it is too liberal. It's a data syntax. It should be
quite expressive to allow for describing a wide range of data. If you are
consuming data with this syntax, and it's shaped in a way you don't want to
handle, just throw an error or don't handle it. Why limit the
expressiveness of the standard for everyone?

**Comment by cjslep** [comment]
ActivityStreams is built on JSON-LD which permits the json being:

- An IRI (that when fetched is an ActivityStream type)
- A JSON object (that is an ActivityStream type)
- A JSON array (of IRIs, JSON objects, or a mix of both, and can be any mix of ActivityStream types)

This can be difficult to process, and this isn't limited to the `actor` field. This is true of any non-functional definition in the ActivityStreams spec (and functional ones are either IRIs or JSON objects).

This kind of difficult problem is exactly why I built [go-fed/activity/vocab](https://github.com/go-fed/activity/tree/master/vocab), you'll find this complication mentioned explicitly in the README.

Edit: Also note that implementations *should* preserve any **extensions** present on ActivityStream objects (ie not drop unsupported fields). However, if I recall correctly it does not say anything about the **core** types which means implementations may not be at liberty to just drop this default complexity.

**Comment by nightpool** [comment]
ActivityStreams inherits it's syntax from JSON-LD, and I don't think further changes to the syntax are within the scope of the errata process.

**Comment by nightpool** [comment]
Furthermore, restricting the actor field to a Person would be very confusing, as there are five different Actor Types defined in ActivityStreams, for a very good reason! why privilege one over the other? https://www.w3.org/TR/activitystreams-vocabulary/#actor-types

**Comment by nightpool** [comment]
Just realized that this issue is on the ActivityPub repo, not ActivityStreams. for more information about the syntax of as2 documents, please see https://www.w3.org/TR/activitystreams-core/ (It does define a subset of the JSON-LD representation that you must use, for compatibility with pure-json processors, but that's mainly related to compaction, not limiting the expressiveness like was proposed here)

**Comment by cwebber** [comment]
I appreciate the attempt to clarify details about actors, but `type` (really an alias for `@type`, and I wish that alias had never happened and that everyone used `@type`) means something special in json-ld... adding Type wouldn't mean anything.

The range of actors available in the `actor` field is intentionally left wide-open, because anything in ActivityPub can become an actor by mere virtue of having an `inbox`.

I don't think this is really up for debate in ActivityPub, since this is also an activitystreams and json-ld issue... those are the data models we use.  As such I'm closing this.

**Comment by lanodan** [comment]
Not really wanting to reopen this, just clarification.

> Why limit the expressiveness of the standard for everyone?

Because a data is meant to be understood by others, otherwise it would make no sense to even have a standard. And currently it results in quite a mess to be correctly interpreted and used.

Also I put this issue on ActivityPub and not ActivityStreams because I can understand that ActivityStreams could be used outside of ActivityPub and so have different use-cases.

> Furthermore, restricting the actor field to a Person would be very confusing, as there are five different Actor Types defined in ActivityStreams, for a very good reason! why privilege one over the other? https://www.w3.org/TR/activitystreams-vocabulary/#actor-types

I’m not dropping the others, just wanting a SHOULD/MUST to have at least one ``Person`` when actor is an Array of Objects.

> I appreciate the attempt to clarify details about actors, but type (really an alias for @type, and I wish that alias had never happened and that everyone used @type) means something special in json-ld... adding Type wouldn't mean anything.

Never said anything about adding, I think you got confused by me wanting to use typing like there is in programs just for explaining my issue because I didn’t want to go read a pile of specifications to use the right vocabulary.
