### ISSUE TITLE
Implementation Report: go-fed

### ISSUE THREAD

**Issue by cjslep** [w3c-social/activitypump#318]
Project Name: go-fed
Report: https://test.activitypub.rocks/download-report/jlkprc5hmhemz6ges7fgpeesyxdmrfnapiv4qohwrp667ragnysa

Thank you!

**Comment by cwebber** [comment]
Pushed up, thanks!  As you can see on https://activitypub.rocks/implementation-report/ there were a couple of server errors for a couple of items, which were probably errors on my end when writing the tests... if you want to check them and let me know if you can verify that the behavior is correct, I'll update those.  Thanks for the report, sorry it took so long!
