### ISSUE TITLE
Express ActivityPub Server

### ISSUE THREAD

**Issue by dariusk** [w3c-social/activitypump#321]
A reference server written in Node.js using [Express.js](http://expressjs.com/) that intentionally implements a very small subset of ActivityPub S2S features. Creates "headless" ActivityPub Actors that can be subscribed to and will publish Notes to subscribers. 

https://test.activitypub.rocks/download-report/xlqx7ze72iuakmv4o4df6d2hzpmdmkkjjrdpp7kksh4yfo6lfz3a

**Comment by ThisIsMissEm** [comment]
What's the expected outcome of this issue?

**Comment by dariusk** [comment]
This was part of the original test suite process, we were asked to put test suite results as an open issue here to inform people. I don't believe there is any intended outcome.

**Comment by evanp** [comment]
I'm going to note this as closed. This server has been an important part of the fediverse!
