### ISSUE TITLE
PubGate implementation report

### ISSUE THREAD

**Issue by autogestion** [w3c-social/activitypump#329]
https://test.activitypub.rocks/download-report/etot26mraqrnfq5qnztmjyilof6gluzuqfej5ivck452ibam3qiq
Thank you!

ps. looks like certificate on test suit expired (

**Comment by rasos** [comment]
Yes, several certificates expired, also for tags.pub. places.pub seems completely offline. 
We would like to investigate using ActivityPub for sharing events and venue descriptions.

**Comment by evanp** [comment]
This test suite is no longer being used, and we're no longer collecting implementation reports, which were really only necessary before the specification was formalized. If you'd like to check out new testing for AP, see [Testing Task Force](https://github.com/swicg/ap-test-suite-taskforce).

For lists of live implementations, it may be useful to look at https://fedidb.org/software . We may also want to investigate setting up a list maintained by the CG.

**Comment by evanp** [comment]
I created #446 to think about this issue.
