### ISSUE TITLE
Split the specification up

### ISSUE THREAD

**Issue by xray7224** [w3c-social/activitypump#33]
Currently the specification is one big document that has lots of components to it. This makes it difficult for an individual to implement, while we need to ensure the specification is flexible and good enough to be used for big social networks, we should, if possible, also make it accessible for people to implement so they can run this on their own site and interoperate.

The Indieweb folk have something similar by having what they call [Indiemark](http://indiewebcamp.com/IndieMark).

**Comment by akuckartz** [comment]
:+1:

**Comment by rhiaro** [comment]
Started at https://github.com/w3c-social/activitypump/blob/master/implementation.md
