### ISSUE TITLE
Add link to socialhub.network on activitypub.rocks

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#331]
There was some question about having a forum for AP implementers. Apparently there's one already on socialhub.network. That might be useful to link to directly.

**Comment by 360fun** [comment]
Great! :)
Seems like it has been created by the developers of Pixelfed (https://github.com/pixelfed) and Prismo (https://gitlab.com/mbajur/prismo):

https://socialhub.network/about
![image](https://user-images.githubusercontent.com/844090/49906623-f9794000-fe72-11e8-9891-145cc9589746.png)

**Comment by cwebber** [comment]
I'll get the link up shortly, probably tomorrow!  In the meanwhile, thanks for working on this!

**Comment by mbajur** [comment]
Hey there! mxb from Prismo in here, ping me if you need anything :)

oh, and @360fun - link to prismo is wrong ;) We're on gitlab https://gitlab.com/mbajur/prismo

**Comment by 360fun** [comment]
> Hey there! mxb from Prismo in here, ping me if you need anything :)
> 
> oh, and @360fun - link to prismo is wrong ;) We're on gitlab https://gitlab.com/mbajur/prismo

sorry I pasted the wrong one :P now is fixed! ;)

**Comment by 360fun** [comment]
> I'll get the link up shortly, probably tomorrow! In the meanwhile, thanks for working on this!

News? ;)

**Comment by 360fun** [comment]
Hi again @cwebber ! :D Can we begin this 2019 with a beautiful link added to the [activitypub.rocks](https://activitypub.rocks/) homepage? ;) Thanks! ♥

**Comment by 360fun** [comment]
Stuck. :(

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/add-link-to-socialhub-network-on-activitypub-rocks/178

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/add-link-to-socialhub-network-on-activitypub-rocks/205

**Comment by 360fun** [comment]
Finally the official forum has come!!! 😻😻😻

**Comment by akuckartz** [comment]
@evanp Is there anything left to do here or can this issue be closed?

**Comment by evanp** [comment]
This happened a long time ago.
