### ISSUE TITLE
Restrict inbox posting

### ISSUE THREAD

**Issue by TiMESPLiNTER** [w3c-social/activitypump#332]
Maybe I missed something but the AcitivtyPub standard does not describe a method for restricting inbox posting in anyway if I'm correct.

That would mean that like with email anybody could send anything to my inbox. Is it up to the client to restrict inbox postings for certain types and/or certain users (for examples if I want that only  users I'm following are allowed to post into my inbox)?

So maybe I want to allow the people I'm following post media into my inbox and all other users should only be allowed to post me `Note` activities.

Is this all up to my implementation of the ActivityPub protocol?

**Comment by nightpool** [comment]
yep! for example, see B.6

> Spam is a problem in any network, perhaps especially so in federated networks. While no specific mechanism for combating spam is provided in ActivityPub, it is recommended that servers filter incoming content both by local untrusted users and any remote users through some sort of spam filter.

**Comment by nightpool** [comment]
of course, there are lots of reasons someone might want to reject or filter something besides a spam filter, this is just one example

**Comment by TiMESPLiNTER** [comment]
Alright thanks for the clarification. Wasn't sure if a correct activity posted into my inbox from a "unknown actor" should be considered as spam as compared to email an email from an unauthorized e-mail address doesn't have to be spam.

But makes sense that way. 🙂

**Comment by mkljczk** [comment]
It would be nice to have a standardized way to specify for example white/blacklisted domains or receive information that this actor is not allowed after sending a post

**Comment by nightpool** [comment]
I've been thinking about sending Reject activities for errors in delivery (sending a private message to a user who only accepts private messages from followers, for example)

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/restrict-inbox-posting/171

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/restrict-inbox-posting/202

**Comment by evanp** [comment]
So, this is a common misperception. We included two errata for ActivityPub to make this clear:

https://www.w3.org/wiki/ActivityPub_errata

Section 6.11 is about delivery for the ActivityPub API, and section 7.1.1 is about the ActivityPub federation protocol. Here's the text of the errata: 

>    Section 6.11 should read, "Federated servers SHOULD perform delivery on all Activities posted to the outbox according to outbox delivery. Servers MAY filter activities for privacy, abuse mitigation, or other reasons."

>    Section 7.1.1 should read: "When objects are received in the outbox (for servers which support both Client to Server interactions and Server to Server Interactions), the server SHOULD target and deliver to: The to, bto, cc, bcc or audience fields if their values are individuals or Collections owned by the actor. Servers MAY filter activities for privacy, abuse mitigation, or other reasons."

I think that satisfies the needs of this issue. Please let us know if there's anything else. These changes have been made to the current [editor's draft](https://w3c.github.io/activitypub/) and barring big changes will be part of the next published version of AP.

**Comment by evanp** [comment]
Closing this after 7 days.
