### ISSUE TITLE
Why did you come up with a dedicated Person type?

### ISSUE THREAD

**Issue by ppwfx** [w3c-social/activitypump#333]
Hey,

I just got a little question about your thought process. Why did you choose to have your own `Person` type (defined here `https://www.w3.org/ns/activitystreams.jsonld`) rather than extending an existing one (e.g. `https://schema.org/Person.jsonld`)?

This isn't meant to be a critic, I'm just curious.

cheers

**Comment by nightpool** [comment]
This is probably more correctly a question for https://github.com/w3c/activitystreams, activitypub is a protocol implemented on top of the activitystreams vocabulary.

**Comment by ppwfx** [comment]
ah my bad, thanks for the clarification

cheers
