### ISSUE TITLE
Make it clearer what the test suite is

### ISSUE THREAD

**Issue by remram44** [w3c-social/activitypump#334]
I am writing an ActivityPub-enabled server, and a test suite would be very useful. However your "test suite" only presents a bunch of checkboxes, then offers to submit an issue in this repository. What happens afterwards I don't know.

It would be nice if it was clearer on the site whether the checklist is all there is (in which case it should probably be called "checklist", not "test suite"), or if some sort of actual automated validation of a server is available.

**Comment by nightpool** [comment]
my understanding is that there is automated validation of clients but not
servers

**Comment by remram44** [comment]
I see! That's unfortunate for me. Thanks for the quick reply.

I still think it might be good if that was stated on the website.

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/make-it-clearer-what-the-test-suite-is/200

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/make-it-clearer-what-the-test-suite-is/210

**Comment by remram44** [comment]
Still broken link :sweat_smile:

**Comment by evanp** [comment]
There has been a lot of progress on this topic in the last year, with development of new testing frameworks and toolkits. This work is coordinated through the [ActivityPub Testing Task Force](https://github.com/swicg/ap-test-suite-taskforce) of the Social Web Community Group. That's probably the best place to track this kind of activity.

**Comment by evanp** [comment]
Closing after 7 days.
