### ISSUE TITLE
Shouldn't activitypub.rocks rock some more?

### ISSUE THREAD

**Issue by aschrijver** [w3c-social/activitypump#335]
I am a fan of ActivityPub spec, and love :heart: all the work you guys have put into this standard. Mucho Kudos! ActivityPub rocks! Unfortunately [activitypub.rocks](https://activitypub.rocks/) ... rocks not so much.

I've read the last [minutes](https://www.w3.org/wiki/SocialCG/2018-12-12/minutes) of the [Social Web Incubator Community Group](https://www.w3.org/wiki/SocialCG) where there was talk of an AP forum (preferably based on AP) and on-the-fly [SocialHub Network](https://socialhub.network/) (Discourse) was discovered (and https://github.com/w3c/activitypub/issues/331 created).

IMHO what ActivityPub direly needs is some central place where people can track its development and implementations, find articles that were written about pros and cons of the spec, find out about the tons of implementation decisions of implementers (e.g. wrt auth), maintaining compatibility, etc. 

I hear there are about 40 AP projects ongoing (source: can't find it anymore, but was some guy on Mastodon mentioning).

Currently finding where AP stands requires Googling, DDG'ing, GH/GL search, Mastodon #activitypub hashtag (hoping you're not hit with https://github.com/tootsuite/mastodon/issues/8113), etc. In other words: really hard to get an overview.

Not saying that activitypub.rocks should provide this central place where one is informed, though it is one of the first places you'll find when searching for AP.

Are there plans to make this the go-to place for AP (non-spec) info? Would be great to see a (community-driven) site there and (bit later) an AP-driven forum..

**Comment by hellekin** [comment]
Note that the [Decentralized Internet & Privacy](https://fosdem.org/2019/schedule/track/decentralized_internet_and_privacy/) devroom at FOSDEM 2019 is organizing an ActivityPub round table, and gathering AP editors and implementors to prepare it. See https://forum.enough.community/t/activitypub-round-table/134

**Comment by 360fun** [comment]
that's great, I really hope we can move this forward: we need it ASAP! :)

**Comment by aschrijver** [comment]
A great idea has popped up in the fediverse, by @cjslep to dogfood the fediverse itself to manage AP evolution, described [in this article](https://cjslep.com/c/blog/an-activitypub-philosophy).

**Comment by strypey** [comment]
I just want to +1 the proposal by @cjslep. I've been maintaining a [watchlist of AP implementations](https://gitlab.com/fediverse/fediverse.gitlab.io/wikis/watchlist-for-activitypub-apps)  for the ongoing dev of fediverse.party. The exact number of implementations depends on what you count (eg just working ones, or in-progress/ proposed ones too?), but there are currently about 60 items on that list. That's already way too many for every implementer to have to communicate with every other one to get smooth inter-operation working, and keep it working.

This work has also involved commenting in or creating issues proposing new AP implementations (eg for [Dreamwidth](https://github.com/dreamwidth/dw-free/issues/2337) and [FOSSAsia's Open Event](https://github.com/fossasia/open-event-server/issues/5518)). I usually link to activitypub.rocks but I'm always asked where they can find more info about how to implement AP in general, and for their use cases in particular.

EDIT: typos

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/shouldnt-activitypub-rocks-rock-some-more/177

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/shouldnt-activitypub-rocks-rock-some-more/199

**Comment by evanp** [comment]
This mostly exists! One thing that I've been doing is moving activitypub.rocks issues to the GitLab repo for activitypub.rocks. However, I'm not sure this ticket really makes sense for that.

We have socialhub.activitypub.rocks, which seems like the core of this issue. Can we close this issue?

**Comment by aschrijver** [comment]
Yes, this can be closed. Improving the website is a long-standing thing. Most recent is [this initiative](https://socialhub.activitypub.rocks/t/activitypub-rocks-portal-from-standards-movement-to-grassroots-fedi/3577) on SocialHub.
