### ISSUE TITLE
Discussing the evolution of the activitypub.rocks site: links, onboarding, and layout

### ISSUE THREAD

**Issue by rigelk** [w3c-social/activitypump#345]
Hello,

Following the recent [APConf in Prague](https://redaktor.me/apconf/), I tried going through the resources at hand for new ActivityPub implementers, [reviewing what we could improve to ease the onboarding](https://socialhub.activitypub.rocks/t/discussing-onboarding-for-developers/61). activitypub.rocks plays a major role in this, being the main landing page for the protocol.

In the meantime, a [forum](https://socialhub.activitypub.rocks/) has been created for the protocol (at the time of this writing it still is under construction and therefore unannounced). It could play a major role at organizing the information long-term for varied audiences, but would not replace ap.rocks as a landing page, which means we have to properly link to the relevant parts of the forum for ap.rocks.

Now, I would normally suggest the modifications through a PR directly against the code, but I was unable to run the site code. Moreover, the last [SocialCG meeting](https://www.w3.org/wiki/SocialCG/2019-09-28) lead me to write down my suggestions here instead before deciding anything:

- a top bar featuring the main links, so as make the most important information stand out:
  - a link to the spec
  - a link to the forum
  - a link to the known implementations: https://socialhub.activitypub.rocks/c/software
  - a link to (a) future guide(s) aimed at implemeters? That could also be done in the "Implementers" section below, but having twice the information doesn't hurt.
- a rewritten "implementers" section that points to the relevant forum sections rather than the defunct test.activitypub.rocks.
- a visible rss feed button in the news section

I made a demonstration at https://rigelk.gitlab.io/activitypub.rocks/ that I initially meant as a full rewrite of ap.rocks to be more hackable (omitting the implementation reports page). Its code is available at https://gitlab.com/rigelk/activitypub.rocks.

---

**Questions:** do you find the suggested modifications to the site valuable? Do you have other modifications in mind?

---

a mirror issue was created on the dustycloud/activitpub.rocks tracker: https://gitlab.com/dustyweb/activitypub.rocks/issues/11
this issue incidentally tries to achieve part of what https://github.com/w3c/activitypub/issues/335 diagnosed, and follows-up on https://github.com/w3c/activitypub/issues/331

**Comment by gobengo** [comment]
> Questions: do you find the suggested modifications to the site valuable? Do you have other modifications in mind?

It looks good! And yeah the modifications seem helpful.

They could probably also be made on the existing site.
I'd expect there to many differing opinions on this, but I do think 'hackability' is important in increasing maintainability of these community resources. If we want to add these improvements to the current site, someone has to knows scheme + html + css + maybe js. I'm not one of those people because I'm not going to learn scheme just for this.

I posit that the less number of languages are involved in repo, the larger the set of contributors will be (somewhat paradoxically). Since generally this is a program that is a web page and maybe also a web server, it's likely the case that html, css, js, are pretty hard prerequisites. Why add scheme (or python, or ruby, or perl)?

I applaud your efforts. I think hackability/maintainability + continuous improvement of some of these community resources is important.

Other thoughts:
* Is the RSS feed you added maintained by hand right now? (i.e. to add news you have to edit the html/markdown and also the rss xml)
* Can your repo be run as a web server locally without GitLab Pages magic?

I made a similar project for activitypub.com that may have useful parts too, using (in my circles) a more common web app stack of node.js + React. https://github.com/gobengo/activitypub.com.

**Comment by rigelk** [comment]
@gobengo Thanks! I sincerely hope the maintainability issue gets solved, but in the meantime it would be great to see some if not all of the changes I suggested implemented.

What holds the current implementation standing vs. a new implementation, is the "implementation reports" page, which generates a table of the implementation reports generated by test.activitypub.rocks. It's not so hard to do but requires some time to code. Before I do it, it would be nice having some more support on the idea.

---

Answering your other thoughts:

> the RSS feed you added maintained by hand right now? (i.e. to add news you have to edit the html/markdown and also the rss xml)
> Can your repo be run as a web server locally without GitLab Pages magic?

Since I use [Hugo](https://gohugo.io/) as a base, it deals already with generating the RSS, and yes, it can run as a web server locally during development (just with `hugo server -D`). That's how I use it :) Quite a few static site generators do that already, so I'm not really in favor of Hugo just for that. What makes Hugo interesting is that it is multiplatform, being just a single Go executable.

> I made a similar project for activitypub.com that may have useful parts too, using (in my circles) a more common web app stack of node.js + React. [gobengo/activitypub.com](https://github.com/gobengo/activitypub.com).

I'm okay with rewriting it for a NodeJS static site generator - it makes more sense to me but I know some people are allergic to anything JS. Aside from that, I think having the landing page work without JS is a requirement here. Optional JS parts for demos are okay (?), but that can be included as an optional web component developped in a third party repository.

**Comment by rigelk** [comment]
![Screenshot_2019-10-10  · ActivityPub Rocks ](https://user-images.githubusercontent.com/6329880/66581664-ca118d80-eb80-11e9-9e15-cb99e2df4b97.png)

I ended up implementing the table generation. cc @cwebber

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/discussing-the-evolution-of-the-activitypub-rocks-site-links-onboarding-and-layout/170

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/discussing-the-evolution-of-the-activitypub-rocks-site-links-onboarding-and-layout/193

**Comment by 360fun** [comment]
Oh yeah! 🥳 I've been waiting this moment for almost **1 year**!!! 🤩
You made it even better than I proposed in the beginning! 😻 🌳🌳🌳

**Comment by ap-socialhub** [comment]
This issue is similar to [Discussing the evolution of the activitypub.rocks site](https://socialhub.activitypub.rocks/t/discussing-the-evolution-of-the-activitypub-rocks-site/142) on SocialHub. Please follow up there!

**Comment by evanp** [comment]
Since there's already a mirror issue on GitLab, and since we're moving all the activitypub.rocks issues there, I'm going to close this issue.
