### ISSUE TITLE
The test.activitypub.rocks site is down

### ISSUE THREAD

**Issue by yvolk** [w3c-social/activitypump#347]
As I see now, the web site is down: https://test.activitypub.rocks/

Just wanted to add [AndStatus](http://andstatus.org/) Android client app to the list of apps that support ActivityPub C2S. 
More details on current implementation in AndStatus are here: [Basic implementation of "client to server" ActivityPub protocol](https://github.com/andstatus/andstatus/issues/499)

**Comment by strugee** [comment]
See https://socialhub.activitypub.rocks/t/the-activitypub-test-suite/290/2

**Comment by yvolk** [comment]
@strugee Thank you for the link, I followed up there. By the way, did Pump.io team implement ActivityPub C2S protocol, at last? ;-)

**Comment by strugee** [comment]
@yvolk no problem! To be perfectly frank with you I kind of drifted away from pump.io a few years ago - I still provide security support, but that's pretty much it these days. I really should just take what's there and do a release, but I've also been saying that for about a year and a half now so who knows :grimacing: :sweat_smile:

**Comment by sebilasse** [comment]
Yes, we informed the responsible person 4 years ago but nobody else got access to the domain.
See also https://socialhub.activitypub.rocks/t/https-test-activitypub-rocks-certifiicate-has-expired/2233/4

@cpmoser did https://github.com/yuforium/activity-streams-validator and maybe APdebug will help too:
https://socialhub.activitypub.rocks/t/student-dev-making-the-first-steps-with-activitypub-and-doing-a-video/2401/4

**Comment by evanp** [comment]
Closing in favour of #337
