### ISSUE TITLE
Decouple fork as standalone repository

### ISSUE THREAD

**Issue by erlend-sh** [w3c-social/activitypump#364]
This repo should be decoupled from its old https://github.com/erincandescent/activitypump origin.

A maintainer of this repo just needs to contact GitHub support and request a decoupling.

**Comment by akuckartz** [comment]
@erlend-sh Why do you think that this should be done?

**Comment by erlend-sh** [comment]
Just for basic cleanup, so stuff like this isn't displayed:
<img width="468" alt="Screenshot 2023-01-18 at 16 23 06" src="https://user-images.githubusercontent.com/583842/213211977-845a9904-74f2-453f-89b8-a3475b8c45e8.png">

Lessens confusion regarding whether or not this is *the* repo people should be dealing with.

**Comment by nightpool** [comment]
No, i believe this is intentional to show the history of the protocol.

**Comment by evanp** [comment]
I agree; I don't think we're going to do this.
