### ISSUE TITLE
Guidance on fragments in ids

### ISSUE THREAD

**Issue by snarfed** [w3c-social/activitypump#367]
Hi all! @evanp inspired me with his AS2 issue triaging this morning, so I'm filing this issue here that's confused a number of us for a while now. Not sure if it belongs here or in the AS2 repo; feel free to move it there if appropriate!

AP/AS2 activities and objects are often inlined in various places as bare string ids, eg in `inReplyTo`, `object`, and other fields. To interact with them, AP implementations often fetch them over HTTPS. However, some AP implementations use `#` fragments in their URL ids, including Mastodon (https://github.com/mastodon/mastodon/issues/13879 , https://github.com/mastodon/mastodon/issues/5770), friendica historically (https://github.com/friendica/friendica/issues/8700), sadly my own Bridgy Fed (https://github.com/snarfed/bridgy-fed/issues/427), and others. [Also this SocialHub thread with no conclusion.](https://socialhub.activitypub.rocks/t/problems-posting-to-mastodon-inbox/801)

It's unclear how to fetch and handle ids with fragments like this, since the fragment isn't transmitted to the server in the HTTP request. Currently there isn't really anything on this in either AP or AS2. [AS2's example 32](https://w3c.github.io/activitystreams/core/#example-32) uses a fragment URL as an id, but doesn't mention them otherwise, including in the [AS2 vocab spec](https://w3c.github.io/activitystreams/vocabulary/). Similarly, [AP's example 13](https://w3c.github.io/activitypub/#example-13-an-article) has a fragment URL in `attributedTo`, but otherwise no mention.

Should we prohibit fragments in ids? Should we specify how to handle and fetch them? Something something mumble JSON-LD? Something else entirely?

Thanks in advance!

**Comment by nightpool** [comment]
> Should we prohibit fragments in ids?

What would be the argument for prohibiting them? We would be making thousands of servers and some official spec examples incompatible—why?

> Should we specify how to handle and fetch them? 

Is there currently any incompatibility or confusion in different implementations here? The steps for fetching them seem obvious to me—just request the resource in question and find the subobjects with the right id. but maybe there's some ambiguity I'm not seeing?

**Comment by snarfed** [comment]
> What would be the argument for prohibiting them? We would be making thousands of servers and some official spec examples incompatible—why?

Absolutely agreed!

> Is there currently any incompatibility or confusion in different implementations here? The steps for fetching them seem obvious to me—just request the resource in question and find the subobjects with the right id. but maybe there's some ambiguity I'm not seeing?

For starters, some of them don't exist at all, eg Mastodon likes afaik, eg https://indieweb.social/users/snarfed#likes/706926 . Maybe I don't know enough about subobject fetching/resolution, but https://indieweb.social/users/snarfed is just an actor. Which may be fine, probably not all ids are required to be fetchable.

More broadly though, if this really is settled and entirely workable as is, that would be great! And probably worth documenting at least to some degree in AP and/or AS2. As is, I've seen it cause confusion in multiple places and projects, since I don't know that how to fetch/resolve fragment ids is clearly specified in either spec.

(Unless it's a JSON-LD thing...? Which would still be a problem since JSON-LD is supposed to be optional, right?)

**Comment by evanp** [comment]
So, there is at least one way that I know of for dereferencing an URL fragment for a JSON document, using JSON Pointer: https://datatracker.ietf.org/doc/html/rfc6901#section-6

It doesn't sound like Mastodon is using that, though.

From what I'm reading from the linked thread, the Mastodon team thinks that an identifier that is unique but not dereferenceable is better than none at all.

I don't know what to say about that. It's not what the spec says, so it's technically non-compliant.

I added a Primer for ActivityPub to the W3C wiki, and noted this behaviour by Mastodon.

https://www.w3.org/wiki/ActivityPub/Primer/Object_identifiers

**Comment by nightpool** [comment]
> For starters, some of them don't exist at all, eg Mastodon likes afaik, eg https://indieweb.social/users/snarfed#likes/706926

That's a good example. When I think about fragment identifiers I mainly think about the actor's `#main-key`, which is definitely possible to look up since it's returned in the actor's JSON.


> From what I'm reading from the linked thread, the Mastodon team thinks that an identifier that is unique but not dereferenceable is better than none at all.

After rereading the thread in question from 3 years ago, I think a partially mitigating factor here is that we never intended like activities to be accessible or enumerable by anybody except the two actors immediately involved, and a lot of the issue comes from projects expecting those likes to be presented more publicly. But we make an exception for users who look at the `likes` collection of any specific post. It's a weird complicated privacy thicket, and this unresolvable ID helps us navigate it slightly better than we would be able to otherwise

**Comment by evanp** [comment]
@nightpool Is there any chance you could update that page with the procedure to dereference the fragments if people want to do that?

**Comment by melvincarvalho** [comment]
> > For starters, some of them don't exist at all, eg Mastodon likes afaik, eg https://indieweb.social/users/snarfed#likes/706926
> 
> That's a good example. When I think about fragment identifiers I mainly think about the actor's `#main-key`, which is definitely possible to look up since it's returned in the actor's JSON.
> 
> > From what I'm reading from the linked thread, the Mastodon team thinks that an identifier that is unique but not dereferenceable is better than none at all.
> 
> After rereading the thread in question from 3 years ago, I think a partially mitigating factor here is that we never intended like activities to be accessible or enumerable by anybody except the two actors immediately involved, and a lot of the issue comes from projects expecting those likes to be presented more publicly. But we make an exception for users who look at the `likes` collection of any specific post. It's a weird complicated privacy thicket, and this unresolvable ID helps us navigate it slightly better than we would be able to otherwise



> It's unclear how to fetch and handle ids with fragments like this, since the fragment isn't transmitted to the server in the HTTP request.

For compatibility with the broader web, it's essential to support fragments. When a document is requested, the response should include all the fragments or anchors within it. After receiving the document, the fragment can be matched with it, typically as a key in the JSON.

It's critical to remember that a single web page can contain multiple items, such as a person or a key. This multiplicity is quite common in the wider web.

**Comment by melvincarvalho** [comment]
> Is there currently any incompatibility or confusion in different implementations here? The steps for fetching them seem obvious to me—just request the resource in question and find the subobjects with the right id. but maybe there's some ambiguity I'm not seeing?

this is very good.

There's 3 concept right now in mastodon:

1. The profile document:  /users/nightpool
2. The key /users/nightpool#main-key
3. The Person /users/nightpool#??

It's unfortunate that (1) and (3) are the same.  In a very clean design they would be differnent, e.g. /users/nightpool#me is typically used in, for example, Solid.

@nightpool I have a question for you.  How much would break if a mastodon instance would be to add this part on the end of the @id?  ie users denoted by /users/nightpool#me -- would mastodon cope, or would several components need rewriting?

**Comment by snarfed** [comment]
Sure, we generally do know how to resolve and extract elements from a fragment id in an HTML or JSON document, but sadly the AP spec doesn't yet say to do that, and more importantly afaik current AP implementations generally don't follow it, on either the serving or client sides. Looking at the examples discussed above:

- Mastodon like ids, eg https://indieweb.social/users/snarfed#likes/706926 , are entirely fabricated, to help with interop. There's no `likes/706926` key in the https://indieweb.social/users/snarfed JSON.
- Same with Bridgy Fed creates and updates, eg https://snarfed.org/#update-2023-01-01T02:03:04 . (The response there is HTML.)
- For public keys, eg https://cybre.space/users/nightpool#main-key, the key material does exist, but it's in `.publicKey`, _not_ `.main-key`.

I expect there are many other similar examples, and getting everyone to do "correct" id resolution inside JSON activities etc would be a substantial change for implementors. I guess we could try though!

**Comment by melvincarvalho** [comment]
If #main-key is already handled, then processors know how to process fragments.  Which is very good news for interoperability.  Fixing some of the examples in the spec could be a way to guide implementers, since I think examples may be informational.  The URIs that lead nowhere are not necessarily fatal, rather the URIs that do de-reference gain through semantic interoperability.

**Comment by melvincarvalho** [comment]
> So, there is at least one way that I know of for dereferencing an URL fragment for a JSON document, using JSON Pointer: https://datatracker.ietf.org/doc/html/rfc6901#section-6

It's a bit easier than this normally, just:

```js
object.fragid
```

There's some subtlety around nested objects which may require a recursive algorithm.

One thing that might be a good CG work item would be to write out the simple algorithm, and create a library implementation to fish out a fragment object from JSON.  This is a relatively small task but with high educational value.

**Comment by melvincarvalho** [comment]
Here is a simple algorithm to fetch a fragment id object from a JSON-LD object:

Algorithm:
1. Define the function `getFragment(json, fragmentId)`.
2. Check if the given JSON object has an `@id` property that matches the `fragmentId`.
3. If it matches, return the current JSON object.
4. If it doesn't match and the JSON object is an array, iterate over each item in the array and recursively call the `getFragment` function with the current item and `fragmentId`.
5. If the JSON object is an object (not an array), iterate over each property in the object and recursively call the `getFragment` function with the current property value and `fragmentId`.
6. If none of the above conditions are met, return `null`.

Here's the corresponding JavaScript code:

```javascript
function getFragment(json, fragmentId) {
    if (json['@id'] === fragmentId) {
        return json;
    }

    for (let key in json) {
        if (json.hasOwnProperty(key)) {
            let value = json[key];
            if (Array.isArray(value)) {
                for (let i = 0; i < value.length; i++) {
                    let result = getFragment(value[i], fragmentId);
                    if (result) {
                        return result;
                    }
                }
            } else if (typeof value === 'object') {
                let result = getFragment(value, fragmentId);
                if (result) {
                    return result;
                }
            }
        }
    }

    return null;
}
```

You can use this function like this:

```javascript
let json = { /* Your JSON-LD object */ };
let fragmentId = '#myFragment';
let fragment = getFragment(json, fragmentId);
console.log(fragment);
```

This function will return the first object it finds with a matching `@id`. If no such object is found, it will return `null`. This function handles nested objects and arrays.

This is a starting point that may not include every edge case.

**Comment by snarfed** [comment]
> If #main-key is already handled, then processors know how to process fragments. Which is very good news for interoperability.

Not necessarily. My point was that keys in AS2 actors don't currently follow either "fetch the matching top-level key" or the JSON-LD/`@id` recursive algorithm in https://github.com/w3c/activitypub/issues/367#issuecomment-1549971082. They're not far off, but they use `id` instead of `@id`, and the full URI instead of just the fragment.

More importantly, I highly doubt any existing AP implementation does that kind of generic full resolution. All of the AP signing and validation code I've seen hard-codes the `.publicKey.publicKeyPem` path.

**Comment by melvincarvalho** [comment]
> More importantly, I highly doubt any existing AP implementation does that kind of generic full resolution. All of the AP signing and validation code I've seen hard-codes the `.publicKey.publicKeyPem` path.

I expect this will work well enough, in almost all cases

**Comment by melvincarvalho** [comment]
Actually #fragids are already supported 

https://www.w3.org/TR/activitypub/

See examples 11 and 13

```json
  "to": ["https://rhiaro.co.uk/#amy"]
```

This is good news.  So you just have to follow the spec.  It may be possible to add more detail in the primer.

**Comment by evanp** [comment]
So, I've add a page to the Primer for managing IDs:

https://www.w3.org/wiki/ActivityPub/Primer/Object_identifiers

**Comment by snarfed** [comment]
@evanp this looks great. Thank you for writing it!

**Comment by melvincarvalho** [comment]
Thanks for putting the page together

> Publishers should avoid using fragments in object identifiers for ActivityPub, because there is not a standard defined for dereferencing them

But I'm I very big -1 on this.  Fragids are the mechanism by which the whole of linked data works, including the whole of Solid and WebID.  So this would completely break W3C RECs which are already supported by AP.

Rather both fragids and non-fragids should be supported, with fragids preferred.

@pchampin any thoughts on this?  I think there needs to be quite a bit of formal push back here.

**Comment by snarfed** [comment]
I like this in spirit! Fragids are clearly powerful and useful in other places, as you describe.

Having said that, I have to agree with @evanp here. As he correctly points out, the reality of the fediverse today is that ActivityPub doesn't actually specify fragment id handling at all (examples notwithstanding), LD is entirely optional, and as we've seen from experience, only maybe 1 in 10 fediverse implementations currently do any kind of LD processing at all, much less any fragid handling beyond hard-coding `#publicKey`. Beyond that, fragids in current AP use are few and inconsistent at best; afaict we haven't found a single real example in the wild here other than `#publicKey`.

Again, I'm all for optional, forward-looking frag id handling! But given where the ecosystem is, and how far we are from a process to make big normative changes to AP, I don't think we can recommend it yet for anyone who expects any kind of meaningful interop.

**Comment by melvincarvalho** [comment]
Perhaps as a compromise the Primer could take a neutral stance.  Both are documented in the spec.  A small (1k) library could easy extract an object from a fragid from a page.  Let's not make AP less powerful and less interoperable, if we can avoid it.  Dont forget the whole of solid is yet to come online, and it would be nice to interop and for users to have their own personal data stores, this would be valuable for indieweb too.

**Comment by silverpill** [comment]
>Beyond that, fragids in current AP use are few and inconsistent at best; afaict we haven't found a single real example in the wild here other than #publicKey.

@snarfed At the very least, usage of fragments is recommended by [FEP-521a](https://codeberg.org/fediverse/fep/src/branch/main/fep/521a/fep-521a.md) and [FEP-0837](https://codeberg.org/fediverse/fep/src/branch/main/fep/0837/fep-0837.md). FEP-521a is being implemented by several projects, so the guidance on fragment IDs is urgently needed.

Regarding the Primer page:

>In ActivityPub, fragments are sometimes used when the implementer wants to refer to a part of an object or collection without creating a fully dereferenceable URL for that part. For example, referring to the publicKey of an actor by <actor ID>#publicKey. 

Is `#publicKey` fragment actually used anywhere? Most implementations I have seen use `#main-key` to identify RSA public key.

>1. Check whether the fragment is the name of a top-level property of the document. This is a common technique in ActivityPub.
>2. Check whether the fragment is a standard path to a property in the document, for example using [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) or [Linked Data Fragments](https://linkeddatafragments.org/specification/linked-data-fragments/).
>3. If no resolution mechanism works, treat the object identifier as an opaque, unresolvable string.

This doesn't seem to answer the question of how to resolve `<actor ID>#main-key`. Am I missing something?

---

Here' the resolution algorithm implicitly recommended by FEP-521a and FEP-0837:

1. Strip the fragment from the ID and dereference the remaining part.
2. Recursively check all nested objects until you find an object with `id` property matching the original ID.

This algorithm works for key IDs containing the `#main-key` fragment, and I think it's "good enough".

I suggest re-opening this issue and/or updating the Primer page.

**Comment by ap-socialhub** [comment]
This issue has been mentioned on **SocialHub**. There might be relevant details there:

https://socialhub.activitypub.rocks/t/fep-521a-representing-actors-public-keys/3380/15

**Comment by snarfed** [comment]
> Is `#publicKey` fragment actually used anywhere? Most implementations I have seen use `#main-key` to identify RSA public key.

Ah, sorry! You're right, I only meant the JSON field there, not the fragment. You're right, `#main-key` is probably most common, maybe followed by `#key` as Bridgy Fed publishes.

> I suggest re-opening this issue and/or updating the Primer page.

I'm +0 on this, and for using the FEP-521a/0837 logic. Thank you for weighing in!

**Comment by melvincarvalho** [comment]
> Recursively check all nested objects until you find an object with id property matching the original ID.

This is correct.  In practice it will be 0 or 1 level deep.  If you really want to go recursive, we can do that too, with a simple common library, something similar to:

```javascript
function findNestedObjectById(objects, id) {
  if (objects === null || typeof objects !== 'object') {
    return null
  }

  if (objects.id === id || objects['@id'] === id) {
    return objects
  }

  if (Array.isArray(objects)) {
    for (const obj of objects) {
      const result = findNestedObjectById(obj, id)
      if (result) {
        return result
      }
    }
  } else {
    for (const key in objects) {
      const child = objects[key]
      if (typeof child === 'object' || Array.isArray(child)) {
        const result = findNestedObjectById(child, id)
        if (result) {
          return result
        }
      }
    }
  }

  return null
}
```

**Comment by silverpill** [comment]
@melvincarvalho Is there any authoritative document that recommends this approach, or it is just considered "best practice" among implementers?

**Comment by melvincarvalho** [comment]
There are many W3C RECs that use Linked Data which use fragment IDs.  I think all of them do.  Also the WWW architecture document mentions it.

https://www.w3.org/TR/webarch/#fragid

**Comment by silverpill** [comment]
[FEP-521a](https://codeberg.org/fediverse/fep/src/branch/main/fep/521a/fep-521a.md#key-ids) was updated with the following text:

>Resolution of a URI containing a fragment identifier is performed in two steps:
>1. Resolve URI without a fragment identifier.
>2. Find a nested object where id (or `@id`) property contains the full URI.

**Comment by ap-socialhub** [comment]
This issue has been mentioned on **SocialHub**. There might be relevant details there:

https://socialhub.activitypub.rocks/t/fep-ceee-instance-level-actor-discovery-using-webfinger/3861/16
