### ISSUE TITLE
Provide a better way to follow users from other instances or other services

### ISSUE THREAD

**Issue by rcsilva83** [w3c-social/activitypump#373]
Today there is no standard and easy way for one user follow a user from other instance from the same service or from other service. Mastodon guides the user through a workflow involving copy-and-paste, which is a bad UX specially to newcomers from centralized services.

In [this issue](https://github.com/mastodon/mastodon/issues/19679) on Mastodon's repository there is a discussion about a possible solution for this problem by using web-based protocol handlers. I think it would be great if this becomes a Fediverse standard present on all services that support ActivityPub.

**Comment by BANOnotIT** [comment]
I was thinking of URI scheme that represents Activity objects that can be interpreted by clients. My general idea was to isolate activity type from other properties so that applications can decide how to handle that. [Here's](https://github.com/activitypub-schema/proposal/) my effort.

**Comment by evanp** [comment]
There is a good conversation going on at https://codeberg.org/fediverse/fediverse-ideas/issues/1 for ways to solve this problem. That might be the best venue for this discussion. This kind of standardisation is important for the ''fediverse'', but is a layer on top of ActivityPub itself. There may be multiple complementary solutions to the problem.

**Comment by rcsilva83** [comment]
Makes sense, @evanp . I'll close this issue.
