### ISSUE TITLE
`audience` isn't for addressing

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#383]
The AS2 vocabulary doc [says](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-audience):

```
Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.
```

It's not the people it's addressed to; it's the people who could be interested.

The AP doc includes `audience` among the actual [addressing](https://www.w3.org/TR/activitypub/#client-addressing) properties:

```
the server will only forward new Activities to addressees in the to, bto, cc, bcc, and audience fields
```

This is a mistake.

**Comment by DeadWisdom** [comment]
Ahh, this clears things. What is the imagined use-case for the audience field, then? Would it be used for suggested content?

**Comment by evanp** [comment]
Because this property is used so widely in AP, it seems like the cat is out of the bag, and AP processors should be able to use it. However, because its semantics are not well defined, it should be handled with care.

I created [a new primer document on addressing](https://www.w3.org/wiki/ActivityPub/Primer/Addressing) that covers the 5 addressing properties, including `audience`. I think that should resolve issues with this property.
