### ISSUE TITLE
Clarity on behaviour with multiple `Announce` activities for the same object

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#386]
The `Announce` activity type is typically used for "share", "retweet", "boost" or "repost" functionality on the social web.

In many social systems, it's reasonable to repost the same object multiple times (for example, a reminder of an upcoming event). Because Mastodon doesn't allow multiple `Announce` activities, although they're not forbidden in the ActivityPub spec, we need some extra guidance on what to do with repeated `Announce` activities.

**Comment by evanp** [comment]
Quoting @trwnh from #384:

> Although I have to raise another point of contention: when was it decided that Announce should be idempotent with respect to shares? This is starting to feel like implementation decisions are being raised into the spec itself. For example, if Tumblr decides to implement reblogs as Announce then they will want to support multiple shares most likely. And the original intent with https://github.com/w3c/activitypub/issues/381 was to clarify cases where a "like" is a kind of post, not a binary signal. This is also why I brought up in https://github.com/w3c/activitypub/issues/381 that there should be more clarity on the split between a "resource" and a "procedure".

https://github.com/w3c/activitypub/issues/384#issuecomment-1691926030

**Comment by evanp** [comment]
I wrote a Primer page on `Announce`:

https://www.w3.org/wiki/ActivityPub/Primer/Announce_activity

I focused on the interoperability between implementations that expect idempotent shares (one share per object per actor), versus those that allow multiple shares per object per actor.

**Comment by nightpool** [comment]
Does Mastodon actually disallow multiple announcements? I thought we just
had an advisory lock that would deduplicate announcements posted twice in
short succession.

(EDIT: Actually, I'm not even sure if that exists for Announce like it does for Undo activities)

**Comment by nightpool** [comment]
(as claimed in the wiki post, just want to make sure we're not publishing
misinfo since I haven't actually seen anyone claim anywhere that multiple
Announcements are fully disallowed by Mastodon)

**Comment by evanp** [comment]
I'm satisfied with this process, and I think we can follow up in the Primer if we need further discussion.
