### ISSUE TITLE
Primer page on testing ActivityPub implementations

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#387]
Document how to test an AP implementation.

**Comment by steve-bate** [comment]
Just FYI. I've put together a server-independent ActivityPub test suite and I've used it to test several servers, including onepage.pub. The approach is similar to the proposal Johannes submitted to NLnet. The repository README.md points to additional documentation about the framework.

https://github.com/steve-bate/activitypub-testsuite

**Comment by evanp** [comment]
All right! We have a testing primer page here:

https://www.w3.org/wiki/ActivityPub/Primer/Testing

**Comment by evanp** [comment]
I think that this is complete. We have a primer page that covers a lot of testing issues. Any further refinement can happen on the primer in the wiki.
