### ISSUE TITLE
Data Portability Draft: Move limitations are understated

### ISSUE THREAD

**Issue by steve-bate** [w3c-social/activitypump#389]
It seems to me that the `Move` limitations are understated compared to domain portability. For example, posts cannot be moved. If the prior server goes down all that content is lost. Although some server implementations allow Note/Status export, even that may be restricted by an administrator. For example, they may only allow public posts to be exported. In other words, you are subject to whatever restrictions the administrator of the source server has in place.

Although tooling would be required, migrating posts with domain portability is possible. (As you mention in the domain portability limitations, there may be issues with some server implementations because of implementation-specific URI patterns, which I consider to be anti-pattern, but it's common practice).

**Comment by evanp** [comment]
@steve-bate thanks for the comment and suggestion. This is one of the major disadvantages of the "Move" technique, so it's good to highlight it. I've added the limitation to the draft report, which hopefully resolves this issue.

**Comment by nightpool** [comment]
The limitation of not moving content is not an inherent limitation of the Move activity—in theory you could imagine a server responding to a Move activity by rewriting object URLs, and you could imagine a server (i think zot has something like this) that would create a "live backup" of your account by duplicating the posts that you make on another server in real time, or by restoring the posts from a backup. Combining these two would create an effective leader/follower failover solution where you could seamlessly promote the "follower" account and rewrite the URLs to point to the same content on a different domain.

**Comment by steve-bate** [comment]
> The limitation of not moving content is not an inherent limitation of the Move activity—in theory you could ...

I agree. The AS `Move` activity is an abstract action/verb and could theoretically be implemented in many different ways and used for many different purposes. The document describes "Mastodon-style" `Move`, which has the issues I described.

Zot is interesting. I'd like to understand better what it's doing but the documentation I've seen isn't very detailed and I haven't looked into the source code. The document does say...

> the mobility of existing content is not a top priority. This may or may not take place at a later stage. The most important things we want to keep are your identity and your friends. 

It does seem like rewriting the URLs of every post created by a relocated actor across all cached copies in all instances (and all links to those posts) would be technically challenging and resource-intensive. If you know of an effective way to do it, it sounds like a great FEP candidate.

Even then, all the social issues of what content is *allowed* to move remain.

**Comment by steve-bate** [comment]
> I've added the limitation to the draft report, which hopefully resolves this issue.

Thanks @evanp !
