### ISSUE TITLE
Clarity on our own domain

### ISSUE THREAD

**Issue by aschrijver** [w3c-social/activitypump#397]
:point_right: _We MUST get clarity on all the different Fediverse-related concepts and their relationships._

Detail and background on this issue is in the SocialHub topic [FEP Process: Guaranteeing an open and decentralized ecosystem](https://socialhub.activitypub.rocks/t/fep-process-guaranteeing-an-open-and-decentralized-ecosystem/3602/23?u=aschrijver).

We hear many people say that AP is too flexible, or that it isn't a standard you can readily implement to "be part of the Fediverse" and that the specs present more of a framework. There's talk that there's a kind of "core" or foundational part to the protocol, and then there's the extension mechanism. Best practices for extensions are being defined, but there's still much confusion and many open issues. Much of the confusion is likely caused by unclear terminology and mental picture how various concepts fit together.

In the SocialHub post I pose that defining our own domain may help create a common understanding. Define terminology that can be used consistently from now on. Copying a snippet from the post as an example:

>All kinds of assertions can be listed this way about AS/AP and trigger discussion to improve the domain model. For instance if I'd just brainstormingly gave a kick-off of this exercise, I might type stuff like:
>
>- A **Pluggable Protocol** _can_have_ **Protocol Extensions**
>- **ActivityPub** _is_a_ **Pluggable Protocol**
>- A **Protocol Extension** _is_defined_by_ an **Extension Specification**
>- An **Extension Specification** _defines_ **Message Formats**
>- An **Extension Specification** _defines_ **Message Exchange Patterns**
>- An **Extension Specification** _provides_ a machine-readable **Message Context**
>- _etcetera_ ..

**Comment by evanp** [comment]
This seems like an interesting issue to address, but it's not immediately clear how this would apply directly to the ActivityPub spec.

Would this be better as a SWICG task or note? Especially questions about the relationship between protocols and extensions, and what those entail?

**Comment by aschrijver** [comment]
Perfect. Continued in https://github.com/swicg/general/issues/37
