### ISSUE TITLE
PDF version of standard

### ISSUE THREAD

**Issue by AaronNGray** [w3c-social/activitypump#428]
Is it possible to provide a PDF version of the draft standard ?

**Comment by nightpool** [comment]
you can print to PDF from both Chrome and Firefox. I think respec should
come with built in @print stylesheets, but if there are improvements we can
upstream those.

**Comment by TallTed** [comment]
> you can print to PDF from both Chrome and Firefox

And on macOS, from any browser that supports the system's print dialog/features.

**Comment by tesaguri** [comment]
As a precedent, documents from the OWL Working Group have non-normative PDF versions, e.g. <https://www.w3.org/TR/2012/REC-owl2-quick-reference-20121211/>. The PDF versions seem to have been exported from a Web browser, however.

**Comment by evanp** [comment]
I'll investigate if the W3C hosts PDF versions of specification documents, and if we can, I'll create a PDF version.

We'll also need a link to the PDF version from the main HTML version.

**Comment by evanp** [comment]
@AaronNGray given that there are many ways for a reader to do this, what's the incentive for creating a PDF on the authoring side?

**Comment by AaronNGray** [comment]
@evanp Yes, I have used the browser printing facility. I have just used an embeeded link on RFC's and a lot of W3C in the past. But using a browser is fine I did not realize there was internal printing media type markup. I will cloe this issue, thanks.
