### ISSUE TITLE
List of ActivityPub implementations

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#446]
It may be useful for users or developers to find a list of implementations. Maybe we should maintain that through github? The W3C wiki? SocialHub? Other?

**Comment by bumblefudge** [comment]
feel free to assign me, I feel like the testing TF should probably take this on

**Comment by snarfed** [comment]
cc @jernst @steve-bate re https://feditest.org/

**Comment by steve-bate** [comment]
We're currently testing 39 different AP-related implementations. That doesn't include some of the MissKey and Mastodon forks. We'll be publishing the results of our WebFinger testing on https://feditest.org/ soon.

**Comment by silverpill** [comment]
Several such lists already exist, [delightful-fediverse-apps](https://codeberg.org/fediverse/delightful-fediverse-apps) is the most comprehensive I've seen

https://delightful.club/delightful-fediverse-apps/

**Comment by evanp** [comment]
> Several such lists already exist, [delightful-fediverse-apps](https://codeberg.org/fediverse/delightful-fediverse-apps) is the most comprehensive I've seen
> 
> https://delightful.club/delightful-fediverse-apps/

So, that might be a good bit of source material. We could fork and duplicate in the swicg namespace, or copy to the W3C wiki, or just link to it from the SocialCG home page. All of these seem like a good way for us to raise up this work.

**Comment by bumblefudge** [comment]
I'd say link to fedidb and delightful.club from github.com/swicg org readme/pinned message, and/or wiki !

**Comment by evanp** [comment]
I added the the Delightful and FediDB lists to the W3C wiki page for AP, here: https://www.w3.org/wiki/ActivityPub and to the README.md for this repository.

I think that should satisfy the needs of this particular issue. If any of these lists become unmaintained or drift from the purpose described, we should revisit, but that can come up as issues later.
