### ISSUE TITLE
The MIME media type `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` is mandatory in ActivityStreams and optional in ActivityPub

### ISSUE THREAD

**Issue by cristianolongoodhl** [w3c-social/activitypump#447]
Please Indicate One: 
 * [*] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue: in Section 2 of the [Activity Streams 2.0 recommendation](https://www.w3.org/TR/activitystreams-core/#h-syntaxconventions) an _Activity Streams Document_ is defined as 

> a JSON document whose root value is an Activity Streams Object [...] whose MIME media type is " application/activity+json". 

Instead, the ActivityPub specification in [Section 3.2](https://www.w3.org/TR/activitypub/#x3-2-retrieving-objects) indicates the MIME media type  ` application/ld+json; profile="https://www.w3.org/ns/activitystreams"` as mandatory. 

Considering ActivityPub as an extension of ActivityStreams2, the latter media type should be mandatory.

**Comment by nightpool** [comment]
This was done to add compatibility with linked data notifications, a separate standard by the W3C that was undergoing development at the same time. ActivityPub indicates that implementers should treat both MIME types interchangeably.

Unfortunately, while AFAIK no widely-deployed systems rely on the aforementioned LDN compatibility, and it seems to have been a bit of a dead-end, we cannot change the normative requirements of the spec at this time.
