### ISSUE TITLE
XEP-like extensions

### ISSUE THREAD

**Issue by avidseeker** [w3c-social/activitypump#448]
ActivityPub has been successfully adopted across various platforms, but lacks specs on optional features and extensions. I think a system similar to XMPP's XEP system is brilliant for this task. This way, clients and servers can freely choose what to implement, while still keeping the core of main ActivityPub features and functions.

# Example: hide read posts
Various clients has been suggested to implement syncing read content. Some of them implement it. Some don't. Having some extension spec like AEP-0007 for example, would make the protocol unified so that when two Fediverse services (say: Mastodon and Lemmy) have the same post read, any Fediverse client would mark it as read. Of course, just like XEPs, servers and clients can choose to implement such feature or not.

**Comment by snarfed** [comment]
Hmm! Are you familiar with [FEPs](https://codeberg.org/fediverse/fep)? Or the [proposed AS2 extension process](https://swicg.github.io/extensions-policy/) ([background](https://www.w3.org/wiki/Activity_Streams/Primer/Extensions))?

**Comment by avidseeker** [comment]
lol, I've been having a hard day of suggesting stuff that already exists: https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/thread/O52EPUXS3UEBTONKEYSI4U66OR5MDDZW/

But I'll blame this on how useless search engines became.
