### ISSUE TITLE
bto and bcc not included

### ISSUE THREAD

**Issue by xray7224** [w3c-social/activitypump#45]
In the implementation document you say:
> When your outbox receives an activity (or content-object?) with an audience specified in to or cc properties, your server dereferences these URLs (continuing until URIs for users (Actors) are found in the case of groups/collections) and discovers their inbox endpoints.

`bto` and `bcc` still exist I believe, if so they should also be included here.

**Comment by rhiaro** [comment]
`to` and `bto` were removed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/101. I've updated to mention `cc` and `bcc` instead.
