### ISSUE TITLE
ActivityPub.rocks SocialHub Email Server Down

### ISSUE THREAD

**Issue by howlettga** [w3c-social/activitypump#474]
Is this the owner maintainer of [socialhub.activitypub.rocks](https://socialhub.activitypub.rocks/)? The email server is down and doesn't send out any signup confirmation emails. For this reason, a new user cannot sign up. I can't find any means of contact outside of the SocialHub itself which I cannot access, so I am posting here.

**Comment by nightpool** [comment]
No, socialhub.activitypub.rocks is managed by the https://socialhub.activitypub.rocks/ admin team. You can contact @how@ps.s10y.eu on the fediverse with admin questions / troubleshooting issues.
