### ISSUE TITLE
What is expected behavior of Posting two Create Activities in a row?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#56]
orig: https://hypothes.is/a/QPNcIr_PQ_eyW2c9zoYF9Q

Does this 'trigger' two creates? Will the first succeed and the second... 4xx?

**Comment by akuckartz** [comment]
Why should the second one fail ?

**Comment by cwebber** [comment]
I don't understand what the problem here is... I think if you post two Create activities, two things get created.

**Comment by cwebber** [comment]
Feel free to reopen if I misunderstood!

**Comment by gobengo** [comment]
@cwebber @akuckartz I think I had in mind some world where you created two objects with the same ID or something. Obviously the spec can say "Don't include an id on the object of a create activity".

More to the point, I think the spec and thinking behind it would benefit a lot from each of the activity types in section 9.2 had examples.

**Comment by cwebber** [comment]
That's a good point... I've raised #62 on the point of specifying / not specifying an @id on client->server posts.
