### ISSUE TITLE
use as:Undo instead tons of Unfoo activities

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/activitypump#6]
To my understanding AS2.0 uses *as:Undo* instead creating tons of *Unfoo* activities
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-undo

**Comment by xray7224** [comment]
I really do like this idea, having "un"-everything verbs isn't ideal. I think we should switch to this.

**Comment by rhiaro** [comment]
+1

**Comment by akuckartz** [comment]
:+1:

**Comment by cwebber** [comment]
I think most Unfoo verbs were removed from ActivityStreams anyway, so yes, we should certainly follow this convention.

**Comment by cwebber** [comment]
Done.  Examples should be added, but examples to that entire section need to be added soon, so that's a separate issue.
