### ISSUE TITLE
Rename "favorites" collection to "likes"?

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#64]
The terminology works out to be more awkward in this context, but the ActivityStreams activity has moved from Favorite towards [https://www.w3.org/TR/activitystreams-vocabulary/#dfn-like Like] at some point.  Currently we have an optional "Favorites Collection", which now consists of "Like" objects.  Should we name it the "Likes Collection"?

Personally I think "Likes Collection" is super awkward terminology, so probably not, but I thought external input would be useful.

**Comment by cwebber** [comment]
Not to mention, I think pump.io might currently support "favorites" endpoints anyway?

**Comment by tsyesika** [comment]
I support renaming, i think whilst "Like" comes with it's own problems, removing the "favorite" "like" ambiguity is worth it. My proposition is "Collection of Likes"

**Comment by cwebber** [comment]
Okay, I've done this!
