### ISSUE TITLE
Responses on Activities?

### ISSUE THREAD

**Issue by tsyesika** [w3c-social/activitypump#67]
The specifications says:

> A response can be any content object. The object MUST have an additional inReplyTo property. This property should have the object that your reply is in response to.
> --- https://w3c-social.github.io/activitypub/#reply-objects

This excludes Activities themselves as being responses, I can think of many situations where a user might wish to post an Activity in reply to an object. For example: A user might write a blog post calling someone to action, perhaps to join them on a charity bicycle ride or to attend an event. The user might then post a "Ride" or an "Arrive" activity as a reply to the blog (depending on which action the blog is calling them to do).

**Comment by cwebber** [comment]
Wait, why can't Activities be responses?  Activities are subclasses of Objects in AS2's vocabulary.  Or does "content object" mean "an object that is not a subclass of activity"?

**Comment by tsyesika** [comment]
I'm unsure, it's a bit ambiguous, certainly Activity objects are subclasses of Objects but the spec is ambiguous as it says:

> Objects are the core concept around which both [ActivityStreams] and ActivityPub are built. Objects can be divided into three main categories: Activities, Content Objects and Actors, plus a small collection of objects which do not fit into the previous categories such as collections.

This suggests that Activities are not a subset of Content Objects however, the spec also says:

> There are objects which have a content property, the value of which is provided by the user. These can be for example note, blog, image, etc. 

The Activity does often have a "content" attribute. Are Activities Content objects and if so, we should clean up the ambiguity.

**Comment by cwebber** [comment]
@xray7224 Maybe that text entirely can be removed, and instead replaced with an explaination that posts in ActivityPub are usually some Activity verb wrapping some Object?  And then we can point to the [core classes](https://www.w3.org/TR/activitystreams-vocabulary/#types), which makes a better distinction there anyway, right?

**Comment by tsyesika** [comment]
Right, I agree, I also think the terminology of "Content Objects" should be scrapped, it doesn't serve a purpose. Lets stick to just "Object" I think?

**Comment by cwebber** [comment]
Sounds good to me, will make that change.

**Comment by cwebber** [comment]
Done in c46223c; let me know if you think that handles things well enough @xray7224!
