### ISSUE TITLE
Actors with no Followers/Following collections

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-social/activitypump#69]
Minor inconsistency between Section 7 (7.2: "Every actor MAY have a following collection") and Section 4.1 ("Actor objects MUST have, ..., `followers` and `following` collections"). The two should probably agree, whichever one is the correct one.

More importantly -- Should the MUST (for followers and following collections) be instead changed to a MAY? Given that Actors can be of several different types (Person, Group, Service, Application, etc), is requiring followers and following overly restrictive? 

For example, one can easily picture a Service or an Application not `following` anyone, and so on.

**Comment by cwebber** [comment]
It seems to me like `inbox` and `outbox` might be in the MUST category (plenty of the spec seems to depend on it... I'm having trouble thinking what might happen if these are left out), but `following` and `followers` maybe ought to be a MAY.  There are other reasons to perhaps not provide a "following" and "followers", which could be privacy reasons.

**Comment by cwebber** [comment]
Furthermore very few things seem to require interacting with the `following` and `followers` section, whereas `inbox` and `outbox` are more or less depended upon in various parts of the spec.

**Comment by cwebber** [comment]
Addressed in 676a70d; I've moved following/followers/url to the SHOULD section.
