### ISSUE TITLE
Separate federation protocol from client API

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#7]
Our charter for the W3C social WG is to produce three deliverables: social syntax, social API, and federation protocol.

I realize that the federation protocol is closely intertwined with the client API. However, I think it's part of our job to tease those apart and make two documents.

**Comment by cwebber** [comment]
I don't think it's wise to split this into two documents?  Does the charter say they actually have to be two different documents?

Right now the documentation does a good job of clarifying the boundaries of what's the social api and what's the federation API, maybe better than any of the other documents.  Maybe that could be improved further.

I have a fear that breaking this into two documents will make the function of the spec a lot less clear...

**Comment by akuckartz** [comment]
:-1: We are *not* forced to create different documents if a single one satisfies the requirements. We should *only* create two documents if that improves the result.

(We could produce two deliverables which turn out to be *identical*. I do not think that the charter forbids that...)

**Comment by evanp** [comment]
For one thing, I think it's entirely reasonable for social networks that are not federated to use a standard client API. For example, if a new social network is launched, using a standard API means that developers have very little work to do to port their existing tools to work with the new network.

If we entangle the client API with the federation protocol in a single document, we throw out the possibility of this benefit. So, let's not do that.

**Comment by cwebber** [comment]
@rhiaro is going to probably reorganize the document anyway to fit a common format between documents, so maybe we should find out how that would apply here?

**Comment by cwebber** [comment]
I think we aren't going this direction officially any more, though we might do some untangling as we go.  Instead, we'll more likely be adopting the spec towards the direction of @rhiaro's Social Web Protocols structure, which may include some of this structure as part of that.
