### ISSUE TITLE
Standardize on `gh-pages` branch

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-social/activitypump#70]
It looks like the most active development is happening directly on the `gh-pages` branch, since that's what's powering http://w3c-social.github.io/activitypub/

The `master` branch has fallen a bit behind, as a result. Which is fine, except it causes some confusion in contributors (for example, developers make PRs to `master`, like https://github.com/w3c-social/activitypub/pull/68, instead of to `gh-pages`).

I propose we delete the other branches (specifically `master`), and just use `gh-pages` as the main/default branch for the repo.

**Comment by cwebber** [comment]
It's a good call.  I've deleted master.  Thanks!

**Comment by dret** [comment]
it often helps to mention that in the repo's top-level README, and set gh-pages as the default branch.
