### ISSUE TITLE
How is Notification performed?

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#76]
> Notifications shall be sent to each of the following objects

What does sending a notification _to_ an _object_ mean, and what is sent? My default interpretation is:

> `POST` the appropriate Activity to the URI of the object.

Where the 'appropriate' Activity is the one that will ultimately be Delivered to object(s) owner(s).

Another possibility is the Activity should be `POST`ed to the object owner's inbox directly (rather than going via the object), but then this is the same as Delivery.

Every single object being able to expect and process a POST request containing an Activity (discarded, I presume, if that object isn't linked in there somewhere) sort of raises the implementation bar a tiny bit (vs. single endpoints for this kind of stuff), but maybe isn't that unreasonable.

Or perhaps Notification & Delivery can be collapsed? Hmm.

**Comment by cwebber** [comment]
Yes, I believe notification is the same as delivery.  Posting to a participant's inbox is how you make them aware of a message.  @xray7224 can clarify if I have that wrong.  (Not all messages are _to_ you, you might be cc'ed, but I think that delivery and notification is always the same thing.)

So probably the right thing to do is to collapse this.  What do you think, @xray7224 ?

**Comment by tsyesika** [comment]
Yeah, that's the way I think about it, the notification mechanism happens via posting the activity to the inbox. This probably should be made clear that it's the same mechanism as delivery.

+1 to collapsing this.

**Comment by rhiaro** [comment]
## Notification and Delivery

Notification and Delivery are two closely related acts. Notification involves determining the _target_ for delivery of a new Activity in order to propagate changes to linked objects throughout the social graph. Notification requires following the appropriate links between objects until you reach an _agent_ (the owner of an object). Then, Delivery is the act of inserting the Activity into the recipient agent's inbox.

### Notification

Notification is the process of propagating a new Activity throughout the social graph, so that recipient servers may:
- conduct any side-effects related to the Activity (for example, notification that a user has liked an object is used to update the object's like count);
- deliver the Activity to recipients of the original object, to ensure updates are propagated to the whole social graph

The target(s) for final delivery of an Activity are:
- an `actor` in `to`, `cc` or `bcc` fields
- the `actors` for all objects in the `object`, `target` or `inReplyTo` fields

Where any of these values are `Collections`, use every item in the `Collection` to determine appropriate `actor`s.

Exclude any `actor`s which are the same as the `actor` of the Activity being notified about.

**Comment by cwebber** [comment]
So Amy and I discussed and we would like to reorganize this section into gathering who we're targeting from the actual delivery, once we have that list.

So, there should be two sections:
- Targeting: aka determining which actors get it, including primary targeting (AS2 style to: cc: bcc: fields) and notifications targeting (determining targets based off of object, target, inReplyTo, Activity specific side effects, etc)
- Delivery:  Actual process of delivering objects to servers.

**Comment by rhiaro** [comment]
Resolved by latest updates
