### ISSUE TITLE
Requirements around the id requirements are not clear

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#78]
This doesn't make sense, because it doesn't clarify around client to server vs server to server, and it seems risky in a server to server context:

> A server receiving an object with no specified id should allocate an object ID in the user's namespace and attach it to the posted object.

Maybe we should clarify that in federation that incoming messages are expected to have an id?

**Comment by wilkie** [comment]
I think incoming messages MUST have an id. If you create an id upon receiving an object without one, the activity etc will not be replicated but rather created/cloned. That is, your server and another server will create different ids for that object and you'll have three distinct objects. You need some sort of id to maintain the origin of that object to truly federate it.

(in particular server-to-server. client-to-server will reasonably expect the server to create an id)

**Comment by tsyesika** [comment]
I agree that the that incoming messages must have an ID. We should make it very clear that client to server activity can't provide an ID, the server generate this themselves (i.e. not allow the client to define the ID). The server to server federation must however provide an ID on federated activities.

**Comment by melvincarvalho** [comment]
Why must a message have an ID?  It doesnt need one in Solid, for example.

Perhaps its a good practice tho.  Generating IDs is complex and increases implementation burden.

As part of a workflow a server can add an ID.  Isnt it the case that ID's are always added at _some_ point in the workflow?  I mean they must come from somewhere.  So why should the server be ruled out as a point.

Im coming here from a generalized federated perspective.  If there's going to be some stuff specific to acivity pump, that's fine.  But in terms of an interoperable standard, a wider context is useful.

**Comment by melvincarvalho** [comment]
I was also unclear on : 

> in the user's namespace

What does this mean?  

Users dont have namespaces.  You may associate a user with some data (ideal), a web page (kludge), a server (centralized).

**Comment by cwebber** [comment]
The last F2F indicated "we won't support id-less notifications; see #34.
