### ISSUE TITLE
How is the new URL returned after an update?

### ISSUE THREAD

**Issue by aaronpk** [w3c-social/activitypump#83]
When an update causes a post's permalink to change, how is the new URL returned? While I was implementing my Micropub endpoint, I realized I sometimes needed a way to return the new URL for the update operation. I've [updated the Micropub spec](http://micropub.net/draft/#response-1) accordingly, and wanted to pass this along since it's likely ActivityPub will need to handle this explicitly as well.

**Comment by cwebber** [comment]
I think there's often (but not always) a distinction between an "id" (which is unlikely to change) and a "url" (which might) in ActivityStreams / ActivityPub, so maybe that answers it... you can wholesale replace an object with "id" with one that has a different "url" field?

**Comment by cwebber** [comment]
I think I answered this question, so I'm closing it!  Let me know if I'm wrong.
