### ISSUE TITLE
ActivityPub needs an explicit Conformance section + 2119 reference

### ISSUE THREAD

**Issue by tantek** [w3c-social/activitypump#86]
ActivityPub needs an explicit Conformance section like https://www.w3.org/TR/micropub/#conformance

Perhaps subsume "2. Specification Profiles" into a "2. Conformance section", and move the existing "Specification Profiles" into "Conformance Classes" subsection under that.

Also that "2. Conformance" section should start with the usual reference to RFC 2119:

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC2119].

(see micropub spec source for actual markup to copy/paste)

**Comment by cwebber** [comment]
I've added this secdtion in 28473d6 but it isn't complete yet.  I need to rework to explain how specification profiles tie into conformance, as well as add exit criteria and test suite / reporting sections.

**Comment by cwebber** [comment]
This is done in 195797d, except that testing and implementation reports must still be done.  That will be tracked in issue #106.
