### ISSUE TITLE
Call out Micropub and SocialWebProtocols in ActivityPub spec

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#87]
In a strongly visible box, call out a reference to the Micropub spec as a relatedly similar specification, and reference Social Web Protocols as well.

**Comment by akuckartz** [comment]
:+1:

**Comment by cwebber** [comment]
So, it seems strange to me to reference both Social Web Protocols and Micropub.  Why not just Social Web Protocols, which references the whole shebang anyway?  This is what the Linked Data Notifications spec does.  So that's what I've done.

@aaronpk  It might make sense for Micropub to do the same, since currently Micropub only points to ActivityPub.. I think it would make more sense for Micropub to point at Social Web Protocols too.  Much cleaner!

**Comment by cwebber** [comment]
I did include MicroPub as well after some discussions on IRC, and I think the text looks nice now.
