### ISSUE TITLE
Spam (unsolicited, non-addressed delivery)

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#88]
Maybe this is obvious, but could be explicit?

If a server receives in the `inbox` content that is neither addressed to this user, nor that the user subscribed to, it MUST drop it.

This requires the server with the `inbox` must know about the user's `Following` list. (I'm calling this out explicitly because feasibly (in my ideal modular world) one user could publish their activities (like following someone) on one server, and pick up their messages on another server).
- Is it worth the receiver replying to the sender to say 'go away send no more' in case it's actually a mistake?
- This doesn't help prevent spam that _is_ addressed get to the user (a la email).
- We can make sure there's a great big invitation to plug in spam-prevention and shared blocklists somewhere here.
- Anything we can do to prevent/mitigate against servers sending spam in the first place?

**Comment by cwebber** [comment]
So, I think that messages which are Bcc'ed, just as with email, will end up looking like this, right?  And ActivtyStreams (and also ActivityPub) support this.  So I think probably no?

Delivering to an inbox and including the recipient in the To: is pretty trivial, and I think won't make a big influence on spam one way or another enough to drop Bcc.  But I'm open to thoughts.

Also, Evan wrote an anti-spam system for pump.io which was hosted at http://spamicity.info/ so such a thing could be done.  (I think it's still up but the ssl certs are invalid?)

**Comment by cwebber** [comment]
I'm closing because of the above given reasons.  Happy to talk about it though if you believe this is a mistake.

In the meanwhile I've opened issue #90.
