### ISSUE TITLE
Move or remove section 1.1

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#9]
It's confusing to start the document with the building blocks we _don't_ use. I don't think we need to include these in the document at all; if absolutely necessary, they can be moved to a non-normative appendix.

**Comment by xray7224** [comment]
Makes sense, agreed.

**Comment by akuckartz** [comment]
+1 for moving to appendix

**Comment by xray7224** [comment]
I think it's probably okay just to remove it, I agree with @evanp that we probably don't need to explain why we didn't choose other technologies in the document.
