### ISSUE TITLE
Separate document into ActivityPub and ActivitySub documents

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#91]
This is from discussion at the last F2F meeting.  We hope to split this document into ActivityPub (client to server) and ActivitySub (server to server) documents.

**Comment by rhiaro** [comment]
Closing based on new [resolution from 2016-08-16](https://www.w3.org/wiki/Socialwg/2016-08-16#resolution01) to keep them as one document with reference to LDN instead.
