### ISSUE TITLE
Allow application/ld+json; profile="http://www.w3.org/ns/activitystreams"

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#95]
I would like to be able to post to an AP inbox with the content type `application/ld+json; profile="http://www.w3.org/ns/activitystreams"` and have this treated as equivalent to `applicaton/activity+json`. Currently the spec only mentions `activity+json`. SHOULD treat them as equivalent like it says in AS2 would be nice.

**Comment by akuckartz** [comment]
:+1:

**Comment by rhiaro** [comment]
Per call on 2016-08-09 we discussed switching the default content type in AP to `application/ld+json; profile="http://www.w3.org/ns/activitystreams"` and saying that implementations MAY/SHOULD treat that as equivalent to `application/activity+json`.

**Comment by cwebber** [comment]
This is done.
