### ISSUE TITLE
Specify how ActivityStreams paging works in ActivityPub

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#97]

**Comment by melvincarvalho** [comment]
SeeAlso

https://lists.w3.org/Archives/Public/www-tag/2013Dec/0041.html

"- You asked for a large thing, this is the first page of it.  See Proposal [1]"

**Comment by cwebber** [comment]
@melvincarvalho That would be cool, though it doesn't look like 209 is standardized yet.  I think we could encourage it if it was, maybe in a future revision.

**Comment by melvincarvalho** [comment]
Agreed.  I am also looking for a paging solution.  Basically let's say I have a few 1000 items in a container / collection / inbox -- the question is how to break that up into manageable chunks.  Any solutions welcome! :)

**Comment by akuckartz** [comment]
I think it is sad that there still is no universal specification available for paging. Incompatible wheels are being reinvented again and again.

**Comment by cwebber** [comment]
It's sad that there's no universal linked data specification for paging (though I think ActivityStreams paging could work for other linked data sets anyway, so maybe that is one).  Nonetheless, it's not within our scope to wait for someone else to create something external; ActivityStreams paging already workw and works well.  I've referenced it in the spec now, and I think that resolves this.

**Comment by melvincarvalho** [comment]
Excellent.  While there may not be a universal solution pointers to anything at all could help guide developers (like me) that are searching for any kind of technique here.

Thanks I am assuming you mean:

https://www.w3.org/TR/activitystreams-core/#paging

Funnily enough I was just implementing schema.org CollectionPage today:

https://schema.org/CollectionPage

This is used on 50,000 - 100,000 pages acc. to the site.  I think we have a possibly naming clash here.  While I'm not raising an issue, I thought it might be useful to flag.  I dont believe that schema CollectionPage actually does paging (I might be wrong there) so this may possibly be a source of confusion.  If anyone has time to clarify here, on in another issue, just pipe in :)
